//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "PBGeneratedMessage.h"

@class BaseResponse, NSString, RoomBindAppList, RoomTools;

@interface GetChatRoomInfoDetailResponse : PBGeneratedMessage
{
    unsigned int hasBaseResponse:1;
    unsigned int hasAnnouncement:1;
    unsigned int hasChatRoomInfoVersion:1;
    unsigned int hasAnnouncementEditor:1;
    unsigned int hasAnnouncementPublishTime:1;
    unsigned int hasChatRoomStatus:1;
    unsigned int hasChatRoomBusinessType:1;
    unsigned int hasRoomTools:1;
    unsigned int hasAssociateOpenImroomName:1;
    unsigned int hasRoomBindAppList:1;
    unsigned int hasSpamStatus:1;
    unsigned int hasXmlAnnouncement:1;
    unsigned int chatRoomInfoVersion;
    unsigned int announcementPublishTime;
    unsigned int chatRoomStatus;
    unsigned int spamStatus;
    BaseResponse *baseResponse;
    NSString *announcement;
    NSString *announcementEditor;
    unsigned long long chatRoomBusinessType;
    RoomTools *roomTools;
    NSString *associateOpenImroomName;
    RoomBindAppList *roomBindAppList;
    NSString *xmlAnnouncement;
}

+ (id)parseFromData:(id)arg1;
- (void).cxx_destruct;
@property(retain, nonatomic, setter=SetXmlAnnouncement:) NSString *xmlAnnouncement; // @synthesize xmlAnnouncement;
@property(readonly, nonatomic) BOOL hasXmlAnnouncement; // @synthesize hasXmlAnnouncement;
@property(nonatomic, setter=SetSpamStatus:) unsigned int spamStatus; // @synthesize spamStatus;
@property(readonly, nonatomic) BOOL hasSpamStatus; // @synthesize hasSpamStatus;
@property(retain, nonatomic, setter=SetRoomBindAppList:) RoomBindAppList *roomBindAppList; // @synthesize roomBindAppList;
@property(readonly, nonatomic) BOOL hasRoomBindAppList; // @synthesize hasRoomBindAppList;
@property(retain, nonatomic, setter=SetAssociateOpenImroomName:) NSString *associateOpenImroomName; // @synthesize associateOpenImroomName;
@property(readonly, nonatomic) BOOL hasAssociateOpenImroomName; // @synthesize hasAssociateOpenImroomName;
@property(retain, nonatomic, setter=SetRoomTools:) RoomTools *roomTools; // @synthesize roomTools;
@property(readonly, nonatomic) BOOL hasRoomTools; // @synthesize hasRoomTools;
@property(nonatomic, setter=SetChatRoomBusinessType:) unsigned long long chatRoomBusinessType; // @synthesize chatRoomBusinessType;
@property(readonly, nonatomic) BOOL hasChatRoomBusinessType; // @synthesize hasChatRoomBusinessType;
@property(nonatomic, setter=SetChatRoomStatus:) unsigned int chatRoomStatus; // @synthesize chatRoomStatus;
@property(readonly, nonatomic) BOOL hasChatRoomStatus; // @synthesize hasChatRoomStatus;
@property(nonatomic, setter=SetAnnouncementPublishTime:) unsigned int announcementPublishTime; // @synthesize announcementPublishTime;
@property(readonly, nonatomic) BOOL hasAnnouncementPublishTime; // @synthesize hasAnnouncementPublishTime;
@property(retain, nonatomic, setter=SetAnnouncementEditor:) NSString *announcementEditor; // @synthesize announcementEditor;
@property(readonly, nonatomic) BOOL hasAnnouncementEditor; // @synthesize hasAnnouncementEditor;
@property(nonatomic, setter=SetChatRoomInfoVersion:) unsigned int chatRoomInfoVersion; // @synthesize chatRoomInfoVersion;
@property(readonly, nonatomic) BOOL hasChatRoomInfoVersion; // @synthesize hasChatRoomInfoVersion;
@property(retain, nonatomic, setter=SetAnnouncement:) NSString *announcement; // @synthesize announcement;
@property(readonly, nonatomic) BOOL hasAnnouncement; // @synthesize hasAnnouncement;
@property(retain, nonatomic, setter=SetBaseResponse:) BaseResponse *baseResponse; // @synthesize baseResponse;
@property(readonly, nonatomic) BOOL hasBaseResponse; // @synthesize hasBaseResponse;
- (id)mergeFromCodedInputStream:(id)arg1;
- (int)serializedSize;
- (void)writeToCodedOutputStream:(id)arg1;
- (BOOL)isInitialized;
- (id)init;

@end

