//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class GetEmoticonByMD5ListCGI, NSData, NSMutableArray;
@protocol GetEmotionFavMD5ListCGIDelegate;

@interface GetEmotionFavMD5ListCGI : NSObject
{
    BOOL _isGetting;
    unsigned int _lastIndex;
    id <GetEmotionFavMD5ListCGIDelegate> _delegate;
    NSMutableArray *_emojiList;
    NSMutableArray *_md5List;
    NSData *_reqBuff;
    GetEmoticonByMD5ListCGI *_batchEmojiInfosByMd5ListCgi;
}

- (void).cxx_destruct;
@property(retain, nonatomic) GetEmoticonByMD5ListCGI *batchEmojiInfosByMd5ListCgi; // @synthesize batchEmojiInfosByMd5ListCgi=_batchEmojiInfosByMd5ListCgi;
@property(nonatomic) unsigned int lastIndex; // @synthesize lastIndex=_lastIndex;
@property(retain, nonatomic) NSData *reqBuff; // @synthesize reqBuff=_reqBuff;
@property(retain, nonatomic) NSMutableArray *md5List; // @synthesize md5List=_md5List;
@property(retain, nonatomic) NSMutableArray *emojiList; // @synthesize emojiList=_emojiList;
@property(nonatomic) __weak id <GetEmotionFavMD5ListCGIDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) BOOL isGetting; // @synthesize isGetting=_isGetting;
- (id)convertMd5List:(id)arg1;
- (void)handleBatchEmojiDownLoadSuccess;
- (void)handleBatchEmojiDownLoadFailed;
- (void)requestAllEmojiInfoList;
- (void)startGetEmojiList;
- (void)dealloc;
- (id)init;

@end

