//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BaseGetHeadImage.h"

#import "BaseGetHeadImage-Protocol.h"
#import "MMCGIDelegate-Protocol.h"

@class NSMutableArray, NSString;

@interface GetHDHeadImage : BaseGetHeadImage <BaseGetHeadImage, MMCGIDelegate>
{
    BOOL _isWaiting;
    NSMutableArray *_taskArray;
}

- (void).cxx_destruct;
@property(nonatomic) BOOL isWaiting; // @synthesize isWaiting=_isWaiting;
@property(retain, nonatomic) NSMutableArray *taskArray; // @synthesize taskArray=_taskArray;
- (BOOL)saveData:(id)arg1 forTask:(id)arg2;
- (id)getHDImageDataFromTask:(id)arg1;
- (void)onDownloadPartFailForTask:(id)arg1;
- (void)ondownloadCompleteForTask:(id)arg1;
- (void)onDownloadPartOK:(id)arg1 task:(id)arg2;
- (void)OnResponseCGI:(BOOL)arg1 sessionId:(unsigned int)arg2 cgiWrap:(id)arg3;
- (void)sendNextTask:(id)arg1;
- (void)sendGetHDImageCgiRequest:(id)arg1 offset:(unsigned int)arg2 len:(unsigned int)arg3;
- (void)onTasksStart:(id)arg1;
- (void)dealloc;
- (id)initWithDelegate:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

