//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "PBGeneratedMessage.h"

@class NSMutableArray;

@interface GetNICAddrSvrSet : PBGeneratedMessage
{
    unsigned int hasGetNicAddrSvrCnt:1;
    int getNicAddrSvrCnt;
    NSMutableArray *mutableGetNicAddrSvrsList;
}

+ (id)parseFromData:(id)arg1;
- (void).cxx_destruct;
@property(retain, nonatomic) NSMutableArray *mutableGetNicAddrSvrsList; // @synthesize mutableGetNicAddrSvrsList;
@property(nonatomic, setter=SetGetNicAddrSvrCnt:) int getNicAddrSvrCnt; // @synthesize getNicAddrSvrCnt;
@property(readonly, nonatomic) BOOL hasGetNicAddrSvrCnt; // @synthesize hasGetNicAddrSvrCnt;
- (void)addGetNicAddrSvrs:(id)arg1;
- (void)addGetNicAddrSvrsFromArray:(id)arg1;
- (id)mergeFromCodedInputStream:(id)arg1;
- (int)serializedSize;
- (void)writeToCodedOutputStream:(id)arg1;
- (BOOL)isInitialized;
@property(retain, nonatomic) NSMutableArray *getNicAddrSvrs; // @dynamic getNicAddrSvrs;
- (id)getNicAddrSvrsList;
- (id)init;

@end

