//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "PBGeneratedMessage.h"

@class BaseRequest, NSString, PackagePreprocess;

@interface GetWxaAppCDNDownloadUrlRequest : PBGeneratedMessage
{
    unsigned int hasBaseRequest:1;
    unsigned int hasType:1;
    unsigned int hasAppid:1;
    unsigned int hasAppVersion:1;
    unsigned int hasVersionMd5:1;
    unsigned int hasPackageType:1;
    unsigned int hasOldAppVersion:1;
    unsigned int hasModuleName:1;
    unsigned int hasGzCompress:1;
    unsigned int gzCompress_:1;
    unsigned int hasPackagePreprocess:1;
    unsigned int type;
    unsigned int appVersion;
    unsigned int packageType;
    unsigned int oldAppVersion;
    BaseRequest *baseRequest;
    NSString *appid;
    NSString *versionMd5;
    NSString *moduleName;
    PackagePreprocess *packagePreprocess;
}

+ (id)parseFromData:(id)arg1;
- (void).cxx_destruct;
@property(retain, nonatomic, setter=SetPackagePreprocess:) PackagePreprocess *packagePreprocess; // @synthesize packagePreprocess;
@property(readonly, nonatomic) BOOL hasPackagePreprocess; // @synthesize hasPackagePreprocess;
@property(readonly, nonatomic) BOOL hasGzCompress; // @synthesize hasGzCompress;
@property(retain, nonatomic, setter=SetModuleName:) NSString *moduleName; // @synthesize moduleName;
@property(readonly, nonatomic) BOOL hasModuleName; // @synthesize hasModuleName;
@property(nonatomic, setter=SetOldAppVersion:) unsigned int oldAppVersion; // @synthesize oldAppVersion;
@property(readonly, nonatomic) BOOL hasOldAppVersion; // @synthesize hasOldAppVersion;
@property(nonatomic, setter=SetPackageType:) unsigned int packageType; // @synthesize packageType;
@property(readonly, nonatomic) BOOL hasPackageType; // @synthesize hasPackageType;
@property(retain, nonatomic, setter=SetVersionMd5:) NSString *versionMd5; // @synthesize versionMd5;
@property(readonly, nonatomic) BOOL hasVersionMd5; // @synthesize hasVersionMd5;
@property(nonatomic, setter=SetAppVersion:) unsigned int appVersion; // @synthesize appVersion;
@property(readonly, nonatomic) BOOL hasAppVersion; // @synthesize hasAppVersion;
@property(retain, nonatomic, setter=SetAppid:) NSString *appid; // @synthesize appid;
@property(readonly, nonatomic) BOOL hasAppid; // @synthesize hasAppid;
@property(nonatomic, setter=SetType:) unsigned int type; // @synthesize type;
@property(readonly, nonatomic) BOOL hasType; // @synthesize hasType;
@property(retain, nonatomic, setter=SetBaseRequest:) BaseRequest *baseRequest; // @synthesize baseRequest;
@property(readonly, nonatomic) BOOL hasBaseRequest; // @synthesize hasBaseRequest;
- (id)mergeFromCodedInputStream:(id)arg1;
- (int)serializedSize;
- (void)writeToCodedOutputStream:(id)arg1;
- (BOOL)isInitialized;
@property(nonatomic, setter=SetGzCompress:) BOOL gzCompress; // @synthesize gzCompress=gzCompress_;
- (id)init;

@end

