//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface RecordMsgLocationItem : NSObject
{
    int _m_scale;
    double _m_latitude;
    double _m_longitude;
    NSString *_m_nsLabel;
    NSString *_m_nsPoiName;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSString *m_nsPoiName; // @synthesize m_nsPoiName=_m_nsPoiName;
@property(retain, nonatomic) NSString *m_nsLabel; // @synthesize m_nsLabel=_m_nsLabel;
@property(nonatomic) int m_scale; // @synthesize m_scale=_m_scale;
@property(nonatomic) double m_longitude; // @synthesize m_longitude=_m_longitude;
@property(nonatomic) double m_latitude; // @synthesize m_latitude=_m_latitude;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)dealloc;
- (id)init;

@end

