//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableDictionary;

@interface MASShortcutMonitor : NSObject
{
    struct OpaqueEventHandlerRef *_eventHandlerRef;
    NSMutableDictionary *_hotKeys;
}

+ (id)sharedMonitor;
- (void).cxx_destruct;
@property(retain) NSMutableDictionary *hotKeys; // @synthesize hotKeys=_hotKeys;
@property struct OpaqueEventHandlerRef *eventHandlerRef; // @synthesize eventHandlerRef=_eventHandlerRef;
- (void)handleEvent:(struct OpaqueEventRef *)arg1;
- (BOOL)isShortcutRegistered:(id)arg1;
- (void)unregisterAllShortcuts;
- (void)unregisterShortcut:(id)arg1;
- (BOOL)registerShortcut:(id)arg1 withAction:(CDUnknownBlockType)arg2;
- (void)dealloc;
- (id)init;

@end

