//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "PBGeneratedMessage.h"

@class NSData, NSString, WXCPbVoipRelayData;

@interface WXCPbCSVoiceAckReq : PBGeneratedMessage
{
    unsigned int hasGroupId:1;
    unsigned int hasRoomid:1;
    unsigned int hasRoomkey:1;
    unsigned int hasCapInfo:1;
    unsigned int hasUserAbility:1;
    unsigned int hasMailAuthBuf:1;
    int roomid;
    unsigned int userAbility;
    NSString *groupId;
    long long roomkey;
    WXCPbVoipRelayData *capInfo;
    NSData *mailAuthBuf;
}

+ (id)parseFromData:(id)arg1;
- (void).cxx_destruct;
@property(retain, nonatomic, setter=SetMailAuthBuf:) NSData *mailAuthBuf; // @synthesize mailAuthBuf;
@property(readonly, nonatomic) BOOL hasMailAuthBuf; // @synthesize hasMailAuthBuf;
@property(nonatomic, setter=SetUserAbility:) unsigned int userAbility; // @synthesize userAbility;
@property(readonly, nonatomic) BOOL hasUserAbility; // @synthesize hasUserAbility;
@property(retain, nonatomic, setter=SetCapInfo:) WXCPbVoipRelayData *capInfo; // @synthesize capInfo;
@property(readonly, nonatomic) BOOL hasCapInfo; // @synthesize hasCapInfo;
@property(nonatomic, setter=SetRoomkey:) long long roomkey; // @synthesize roomkey;
@property(readonly, nonatomic) BOOL hasRoomkey; // @synthesize hasRoomkey;
@property(nonatomic, setter=SetRoomid:) int roomid; // @synthesize roomid;
@property(readonly, nonatomic) BOOL hasRoomid; // @synthesize hasRoomid;
@property(retain, nonatomic, setter=SetGroupId:) NSString *groupId; // @synthesize groupId;
@property(readonly, nonatomic) BOOL hasGroupId; // @synthesize hasGroupId;
- (id)mergeFromCodedInputStream:(id)arg1;
- (int)serializedSize;
- (void)writeToCodedOutputStream:(id)arg1;
- (BOOL)isInitialized;
- (id)init;

@end

