//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "PBGeneratedMessage.h"

@class NSString;

@interface WXCPbQcwxtalkHead : PBGeneratedMessage
{
    unsigned int hasUserName:1;
    unsigned int hasCmd:1;
    unsigned int hasSeqNo:1;
    unsigned int hasRet:1;
    unsigned int hasDebugCode:1;
    unsigned int hasRouteId:1;
    unsigned int hasUuid:1;
    int cmd;
    unsigned int seqNo;
    int ret;
    int debugCode;
    unsigned int routeId;
    unsigned int uuid;
    NSString *userName;
}

+ (id)parseFromData:(id)arg1;
- (void).cxx_destruct;
@property(nonatomic, setter=SetUuid:) unsigned int uuid; // @synthesize uuid;
@property(readonly, nonatomic) BOOL hasUuid; // @synthesize hasUuid;
@property(nonatomic, setter=SetRouteId:) unsigned int routeId; // @synthesize routeId;
@property(readonly, nonatomic) BOOL hasRouteId; // @synthesize hasRouteId;
@property(nonatomic, setter=SetDebugCode:) int debugCode; // @synthesize debugCode;
@property(readonly, nonatomic) BOOL hasDebugCode; // @synthesize hasDebugCode;
@property(nonatomic, setter=SetRet:) int ret; // @synthesize ret;
@property(readonly, nonatomic) BOOL hasRet; // @synthesize hasRet;
@property(nonatomic, setter=SetSeqNo:) unsigned int seqNo; // @synthesize seqNo;
@property(readonly, nonatomic) BOOL hasSeqNo; // @synthesize hasSeqNo;
@property(nonatomic, setter=SetCmd:) int cmd; // @synthesize cmd;
@property(readonly, nonatomic) BOOL hasCmd; // @synthesize hasCmd;
@property(retain, nonatomic, setter=SetUserName:) NSString *userName; // @synthesize userName;
@property(readonly, nonatomic) BOOL hasUserName; // @synthesize hasUserName;
- (id)mergeFromCodedInputStream:(id)arg1;
- (int)serializedSize;
- (void)writeToCodedOutputStream:(id)arg1;
- (BOOL)isInitialized;
- (id)init;
- (id)recvShortDesc;
- (id)sendShortDesc;
- (id)description;

@end

