//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "PBGeneratedMessage.h"

@class BaseRequest, CheckResUpdateRequest;

@interface EncryptCheckResUpdateAesReqData : PBGeneratedMessage
{
    unsigned int hasBaseRequest:1;
    unsigned int hasCheckResUpdateReq:1;
    BaseRequest *baseRequest;
    CheckResUpdateRequest *checkResUpdateReq;
}

+ (id)parseFromData:(id)arg1;
- (void).cxx_destruct;
@property(retain, nonatomic, setter=SetCheckResUpdateReq:) CheckResUpdateRequest *checkResUpdateReq; // @synthesize checkResUpdateReq;
@property(readonly, nonatomic) BOOL hasCheckResUpdateReq; // @synthesize hasCheckResUpdateReq;
@property(retain, nonatomic, setter=SetBaseRequest:) BaseRequest *baseRequest; // @synthesize baseRequest;
@property(readonly, nonatomic) BOOL hasBaseRequest; // @synthesize hasBaseRequest;
- (id)mergeFromCodedInputStream:(id)arg1;
- (int)serializedSize;
- (void)writeToCodedOutputStream:(id)arg1;
- (BOOL)isInitialized;
- (id)init;

@end

