//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class RACCompoundDisposable;

@interface NSObject (Aspects)
+ (id)aspect_hookSelector:(SEL)arg1 withOptions:(unsigned long long)arg2 usingBlock:(id)arg3 error:(id *)arg4;
+ (void)jp_fixMethodSignature;
+ (void)safe_swizzleClassMethod:(SEL)arg1 tarSel:(SEL)arg2;
+ (void)safe_swizzleMethod:(Class)arg1 srcSel:(SEL)arg2 tarClass:(Class)arg3 tarSel:(SEL)arg4;
+ (void)safe_swizzleMethod:(SEL)arg1 tarClass:(id)arg2 tarSel:(SEL)arg3;
+ (void)safe_swizzleMethod:(SEL)arg1 tarSel:(SEL)arg2;
+ (void)bk_registerDynamicDelegateNamed:(id)arg1 forProtocol:(id)arg2;
+ (void)bk_registerDynamicDelegateNamed:(id)arg1;
+ (void)bk_registerDynamicDataSourceNamed:(id)arg1;
+ (void)bk_registerDynamicDelegate;
+ (void)bk_registerDynamicDataSource;
+ (void)bk_linkProtocol:(id)arg1 methods:(id)arg2;
+ (void)bk_linkDelegateMethods:(id)arg1;
+ (void)bk_linkDataSourceMethods:(id)arg1;
+ (const CDStruct_0348af7d *)bk_delegateInfoForProtocol:(id)arg1;
+ (id)bk_delegateInfoByProtocol:(BOOL)arg1;
+ (void)bk_removeAllAssociatedObjects;
+ (id)bk_associatedValueForKey:(const void *)arg1;
+ (void)bk_weaklyAssociateValue:(id)arg1 withKey:(const void *)arg2;
+ (void)bk_atomicallyAssociateCopyOfValue:(id)arg1 withKey:(const void *)arg2;
+ (void)bk_associateCopyOfValue:(id)arg1 withKey:(const void *)arg2;
+ (void)bk_atomicallyAssociateValue:(id)arg1 withKey:(const void *)arg2;
+ (void)bk_associateValue:(id)arg1 withKey:(const void *)arg2;
+ (void)bk_cancelBlock:(id)arg1;
+ (id)bk_performBlock:(CDUnknownBlockType)arg1 onQueue:(id)arg2 afterDelay:(double)arg3;
+ (id)bk_performBlockInBackground:(CDUnknownBlockType)arg1 afterDelay:(double)arg2;
+ (id)bk_performBlock:(CDUnknownBlockType)arg1 afterDelay:(double)arg2;
+ (id)bk_observedClassesHash;
+ (id)tp_modelWithDictionary:(id)arg1;
+ (id)tp_modelWithJSON:(id)arg1;
+ (id)_tp_dictionaryWithJSON:(id)arg1;
+ (id)event_logging_alloc;
- (id)aspect_hookSelector:(SEL)arg1 withOptions:(unsigned long long)arg2 usingBlock:(id)arg3 error:(id *)arg4;
- (id)jp_methodSignatureForSelector:(SEL)arg1;
- (id)bk_ensuredDynamicDelegateForProtocol:(id)arg1;
- (id)bk_ensuredDynamicDelegate;
- (id)bk_dynamicDelegateWithClass:(Class)arg1 forProtocol:(id)arg2;
- (id)bk_dynamicDelegateForProtocol:(id)arg1;
- (id)bk_dynamicDelegate;
- (id)bk_dynamicDataSource;
- (void)bk_removeAllAssociatedObjects;
- (id)bk_associatedValueForKey:(const void *)arg1;
- (void)bk_weaklyAssociateValue:(id)arg1 withKey:(const void *)arg2;
- (void)bk_atomicallyAssociateCopyOfValue:(id)arg1 withKey:(const void *)arg2;
- (void)bk_associateCopyOfValue:(id)arg1 withKey:(const void *)arg2;
- (void)bk_atomicallyAssociateValue:(id)arg1 withKey:(const void *)arg2;
- (void)bk_associateValue:(id)arg1 withKey:(const void *)arg2;
- (id)bk_performBlock:(CDUnknownBlockType)arg1 onQueue:(id)arg2 afterDelay:(double)arg3;
- (id)bk_performBlockInBackground:(CDUnknownBlockType)arg1 afterDelay:(double)arg2;
- (id)bk_performBlock:(CDUnknownBlockType)arg1 afterDelay:(double)arg2;
- (id)bk_observerBlocks;
- (void)bk_setObserverBlocks:(id)arg1;
- (void)bk_addObserverForKeyPaths:(id)arg1 identifier:(id)arg2 options:(unsigned long long)arg3 context:(int)arg4 task:(id)arg5;
- (void)bk_removeAllBlockObservers;
- (void)bk_removeObserversWithIdentifier:(id)arg1;
- (void)bk_removeObserverForKeyPath:(id)arg1 identifier:(id)arg2;
- (void)bk_addObserverForKeyPaths:(id)arg1 identifier:(id)arg2 options:(unsigned long long)arg3 task:(CDUnknownBlockType)arg4;
- (void)bk_addObserverForKeyPath:(id)arg1 identifier:(id)arg2 options:(unsigned long long)arg3 task:(CDUnknownBlockType)arg4;
- (id)bk_addObserverForKeyPaths:(id)arg1 options:(unsigned long long)arg2 task:(CDUnknownBlockType)arg3;
- (id)bk_addObserverForKeyPath:(id)arg1 options:(unsigned long long)arg2 task:(CDUnknownBlockType)arg3;
- (id)bk_addObserverForKeyPaths:(id)arg1 task:(CDUnknownBlockType)arg2;
- (id)bk_addObserverForKeyPath:(id)arg1 task:(CDUnknownBlockType)arg2;
- (id)rac_channelToBinding:(id)arg1 options:(id)arg2;
- (id)rac_channelToBinding:(id)arg1;
@property(readonly) RACCompoundDisposable *rac_deallocDisposable;
- (id)rac_willDeallocSignal;
- (id)rac_observeKeyPath:(id)arg1 options:(unsigned long long)arg2 observer:(id)arg3 block:(CDUnknownBlockType)arg4;
- (id)rac_liftSelector:(SEL)arg1 withSignals:(id)arg2;
- (id)rac_liftSelector:(SEL)arg1 withSignalsFromArray:(id)arg2;
- (id)rac_liftSelector:(SEL)arg1 withSignalOfArguments:(id)arg2;
- (id)rac_valuesAndChangesForKeyPath:(id)arg1 options:(unsigned long long)arg2 observer:(id)arg3;
- (id)rac_valuesForKeyPath:(id)arg1 observer:(id)arg2;
- (id)rac_signalForSelector:(SEL)arg1 fromProtocol:(id)arg2;
- (id)rac_signalForSelector:(SEL)arg1;
- (id)tp_modelDescription;
- (BOOL)tp_modelIsEqual:(id)arg1;
- (unsigned long long)tp_modelHash;
- (id)tp_modelInitWithCoder:(id)arg1;
- (void)tp_modelEncodeWithCoder:(id)arg1;
- (id)tp_modelCopy;
- (id)tp_modelToJSONString;
- (id)tp_modelToJSONData;
- (id)tp_modelToJSONObject;
- (BOOL)tp_modelSetWithDictionary:(id)arg1;
- (BOOL)tp_modelSetWithJSON:(id)arg1;
- (id)pb_noop;
- (void)removeAssociatedObjects;
- (void)detachObjectForKey:(id)arg1;
- (id)getAttachedObjectForKey:(id)arg1;
- (void)attachObject:(id)arg1 forKey:(id)arg2;
- (const void *)computeKeyFromString:(id)arg1;
- (id)JSONRepresentation;
@end

