//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "PBCoding-Protocol.h"

@class NSArray, NSString;

@interface WARecommendInfo : NSObject <PBCoding>
{
    NSArray *recommendDatas;
}

+ (void)initialize;
+ (void)PBArrayAdd_recommendDatas;
- (void).cxx_destruct;
@property(retain, nonatomic) NSArray *recommendDatas; // @synthesize recommendDatas;
- (const void *)getValueTagIndexMap;
- (id)getValueTypeTable;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

