//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "PBGeneratedMessage.h"

@class WARemoteDebug_BaseReq;

@interface WARemoteDebug_DevSyncMessageReq : PBGeneratedMessage
{
    unsigned int hasBaseRequest:1;
    unsigned int hasMinSeq:1;
    unsigned int hasMaxSeq:1;
    unsigned int minSeq;
    unsigned int maxSeq;
    WARemoteDebug_BaseReq *baseRequest;
}

+ (id)parseFromData:(id)arg1;
- (void).cxx_destruct;
@property(nonatomic, setter=SetMaxSeq:) unsigned int maxSeq; // @synthesize maxSeq;
@property(readonly, nonatomic) BOOL hasMaxSeq; // @synthesize hasMaxSeq;
@property(nonatomic, setter=SetMinSeq:) unsigned int minSeq; // @synthesize minSeq;
@property(readonly, nonatomic) BOOL hasMinSeq; // @synthesize hasMinSeq;
@property(retain, nonatomic, setter=SetBaseRequest:) WARemoteDebug_BaseReq *baseRequest; // @synthesize baseRequest;
@property(readonly, nonatomic) BOOL hasBaseRequest; // @synthesize hasBaseRequest;
- (id)mergeFromCodedInputStream:(id)arg1;
- (int)serializedSize;
- (void)writeToCodedOutputStream:(id)arg1;
- (BOOL)isInitialized;
- (id)init;

@end

