//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface MultiTalkGroupMember : NSObject
{
    int _mStatus;
    int _mSdkStatus;
    int _mReason;
    int _mHoldStatus;
    int _memberId;
    NSString *_mUserName;
    NSString *_mInviteUserName;
    long long _mInviteTime;
    NSString *_openId;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSString *openId; // @synthesize openId=_openId;
@property(nonatomic) int memberId; // @synthesize memberId=_memberId;
@property(nonatomic) int mHoldStatus; // @synthesize mHoldStatus=_mHoldStatus;
@property(nonatomic) long long mInviteTime; // @synthesize mInviteTime=_mInviteTime;
@property(nonatomic) int mReason; // @synthesize mReason=_mReason;
@property(nonatomic) int mSdkStatus; // @synthesize mSdkStatus=_mSdkStatus;
@property(nonatomic) int mStatus; // @synthesize mStatus=_mStatus;
@property(copy, nonatomic) NSString *mInviteUserName; // @synthesize mInviteUserName=_mInviteUserName;
@property(copy, nonatomic) NSString *mUserName; // @synthesize mUserName=_mUserName;
- (id)description;

@end

