//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "PBGeneratedMessage.h"

@class NSString;

@interface BackupSessionInfo : PBGeneratedMessage
{
    unsigned int hasSessionTime:1;
    unsigned int hasUnReadCount:1;
    unsigned int hasUserName:1;
    unsigned int sessionTime;
    unsigned int unReadCount;
    NSString *userName;
}

+ (id)parseFromData:(id)arg1;
- (void).cxx_destruct;
@property(retain, nonatomic, setter=SetUserName:) NSString *userName; // @synthesize userName;
@property(readonly, nonatomic) BOOL hasUserName; // @synthesize hasUserName;
@property(nonatomic, setter=SetUnReadCount:) unsigned int unReadCount; // @synthesize unReadCount;
@property(readonly, nonatomic) BOOL hasUnReadCount; // @synthesize hasUnReadCount;
@property(nonatomic, setter=SetSessionTime:) unsigned int sessionTime; // @synthesize sessionTime;
@property(readonly, nonatomic) BOOL hasSessionTime; // @synthesize hasSessionTime;
- (id)mergeFromCodedInputStream:(id)arg1;
- (int)serializedSize;
- (void)writeToCodedOutputStream:(id)arg1;
- (BOOL)isInitialized;
- (id)init;

@end

