//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSView.h>

@class SVGImageView;

@interface LVChooseScreenCellSelectedView : NSView
{
    NSView *_topView;
    NSView *_leftView;
    NSView *_rightView;
    NSView *_bottomView;
    SVGImageView *_selectedImageView;
}

- (void).cxx_destruct;
@property(retain, nonatomic) SVGImageView *selectedImageView; // @synthesize selectedImageView=_selectedImageView;
@property(retain, nonatomic) NSView *bottomView; // @synthesize bottomView=_bottomView;
@property(retain, nonatomic) NSView *rightView; // @synthesize rightView=_rightView;
@property(retain, nonatomic) NSView *leftView; // @synthesize leftView=_leftView;
@property(retain, nonatomic) NSView *topView; // @synthesize topView=_topView;
- (id)initWithFrame:(struct CGRect)arg1;

@end

