//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "PBGeneratedMessage.h"

@class NSMutableArray, NSString;

@interface VoIPMtBannerMsg : PBGeneratedMessage
{
    unsigned int hasWxGroupid:1;
    unsigned int hasRoomid:1;
    unsigned int hasSdkGroupid:1;
    unsigned int hasMsgSeq:1;
    unsigned int hasTalkingStatus:1;
    unsigned int hasCreateUserName:1;
    unsigned int talkingStatus;
    NSString *wxGroupid;
    unsigned long long roomid;
    NSString *sdkGroupid;
    NSMutableArray *mutableUserStatusListList;
    unsigned long long msgSeq;
    NSString *createUserName;
}

+ (id)parseFromData:(id)arg1;
- (void).cxx_destruct;
@property(retain, nonatomic, setter=SetCreateUserName:) NSString *createUserName; // @synthesize createUserName;
@property(readonly, nonatomic) BOOL hasCreateUserName; // @synthesize hasCreateUserName;
@property(nonatomic, setter=SetTalkingStatus:) unsigned int talkingStatus; // @synthesize talkingStatus;
@property(readonly, nonatomic) BOOL hasTalkingStatus; // @synthesize hasTalkingStatus;
@property(nonatomic, setter=SetMsgSeq:) unsigned long long msgSeq; // @synthesize msgSeq;
@property(readonly, nonatomic) BOOL hasMsgSeq; // @synthesize hasMsgSeq;
@property(retain, nonatomic) NSMutableArray *mutableUserStatusListList; // @synthesize mutableUserStatusListList;
@property(retain, nonatomic, setter=SetSdkGroupid:) NSString *sdkGroupid; // @synthesize sdkGroupid;
@property(readonly, nonatomic) BOOL hasSdkGroupid; // @synthesize hasSdkGroupid;
@property(nonatomic, setter=SetRoomid:) unsigned long long roomid; // @synthesize roomid;
@property(readonly, nonatomic) BOOL hasRoomid; // @synthesize hasRoomid;
@property(retain, nonatomic, setter=SetWxGroupid:) NSString *wxGroupid; // @synthesize wxGroupid;
@property(readonly, nonatomic) BOOL hasWxGroupid; // @synthesize hasWxGroupid;
- (void)addUserStatusList:(id)arg1;
- (void)addUserStatusListFromArray:(id)arg1;
- (id)mergeFromCodedInputStream:(id)arg1;
- (int)serializedSize;
- (void)writeToCodedOutputStream:(id)arg1;
- (BOOL)isInitialized;
@property(retain, nonatomic) NSMutableArray *userStatusList; // @dynamic userStatusList;
- (id)userStatusListList;
- (id)init;

@end

