//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSData, NSMutableDictionary, NSString;

@protocol AuthCGIExt <NSObject>
- (void)onIDCRedirect:(NSMutableDictionary *)arg1;
- (void)onAuthNeedSMSCode:(NSString *)arg1 withAuthTicket:(NSString *)arg2;
- (void)onAuthNeedImageCode:(NSData *)arg1;
- (void)onAuthFaildWithWrongPasswordOrUsername;
- (void)onCertNeedUpdate;
- (void)onAuthNeedUpdate:(unsigned long long)arg1;
- (void)onAuthAlphaVersion:(NSString *)arg1;
- (void)onAuthKeyInfoInvalidOfUser:(NSString *)arg1 nickName:(NSString *)arg2;
- (void)onAuthPushLoginURL:(NSString *)arg1 errorMsg:(NSString *)arg2;
- (void)onAuthKickOutWithReason:(NSString *)arg1 errorMsg:(NSString *)arg2;
- (void)onAuthFaildForInvalidCGISessionID;
- (void)onAuthFaild:(NSString *)arg1;
- (void)onAuthOKOfUser:(NSString *)arg1 withSessionKey:(NSData *)arg2 withServerId:(NSData *)arg3 autoAuthKey:(NSData *)arg4 isAutoAuth:(BOOL)arg5;
- (void)onPreAuthOKOfUser:(NSString *)arg1 nickName:(NSString *)arg2;
@end

