//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class MessageData;

@protocol IMessageServiceFileExt <NSObject>

@optional
- (void)onFileDidCancelSilentDownloadWithMessage:(MessageData *)arg1;
- (void)onFileDidFinishSilentDownloadWithMessage:(MessageData *)arg1;
- (void)onFileDidCancelPredownloadWithMessage:(MessageData *)arg1;
- (void)onFileDidFailPredownloadWithMessage:(MessageData *)arg1;
- (void)onFileDidStartPredownloadWithMessage:(MessageData *)arg1;
- (void)onFileDidCancelUploadWithMessage:(MessageData *)arg1;
- (void)onFileDidFinishUploadWithMessage:(MessageData *)arg1;
- (void)onFileUploaded:(int)arg1 of:(int)arg2 withMessage:(MessageData *)arg3;
- (void)onFileDidCancelDownloadWithRecordMessage:(MessageData *)arg1;
- (void)onFileDidExpireDownloadWithRecordMessage:(MessageData *)arg1;
- (void)onFileDidFailDownloadWithRecordMessage:(MessageData *)arg1;
- (void)onFileDidFinishDownloadWithRecordMessage:(MessageData *)arg1;
- (void)onFileDownloaded:(int)arg1 of:(int)arg2 withRecordMessage:(MessageData *)arg3;
- (void)onFileDidCancelDownloadWithMessage:(MessageData *)arg1;
- (void)onFileDidFailDownloadWithMessage:(MessageData *)arg1;
- (void)onFileDidFinishDownloadWithMessage:(MessageData *)arg1 isPredownload:(BOOL)arg2;
- (void)onFileDownloaded:(int)arg1 of:(int)arg2 withMessage:(MessageData *)arg3;
@end

