//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "PBGeneratedMessage.h"

@class SKBuiltinBuffer_t;

@interface RemindFriendsInfo : PBGeneratedMessage
{
    unsigned int hasAdgroupId:1;
    unsigned int hasSourceInfo:1;
    unsigned int hasSelfInfo:1;
    unsigned int hasPaidInfo:1;
    unsigned int hasExtraInfo:1;
    unsigned int hasAdgroupId64:1;
    unsigned int adgroupId;
    SKBuiltinBuffer_t *sourceInfo;
    SKBuiltinBuffer_t *selfInfo;
    SKBuiltinBuffer_t *paidInfo;
    SKBuiltinBuffer_t *extraInfo;
    unsigned long long adgroupId64;
}

+ (id)parseFromData:(id)arg1;
- (void).cxx_destruct;
@property(nonatomic, setter=SetAdgroupId64:) unsigned long long adgroupId64; // @synthesize adgroupId64;
@property(readonly, nonatomic) BOOL hasAdgroupId64; // @synthesize hasAdgroupId64;
@property(retain, nonatomic, setter=SetExtraInfo:) SKBuiltinBuffer_t *extraInfo; // @synthesize extraInfo;
@property(readonly, nonatomic) BOOL hasExtraInfo; // @synthesize hasExtraInfo;
@property(retain, nonatomic, setter=SetPaidInfo:) SKBuiltinBuffer_t *paidInfo; // @synthesize paidInfo;
@property(readonly, nonatomic) BOOL hasPaidInfo; // @synthesize hasPaidInfo;
@property(retain, nonatomic, setter=SetSelfInfo:) SKBuiltinBuffer_t *selfInfo; // @synthesize selfInfo;
@property(readonly, nonatomic) BOOL hasSelfInfo; // @synthesize hasSelfInfo;
@property(retain, nonatomic, setter=SetSourceInfo:) SKBuiltinBuffer_t *sourceInfo; // @synthesize sourceInfo;
@property(readonly, nonatomic) BOOL hasSourceInfo; // @synthesize hasSourceInfo;
@property(nonatomic, setter=SetAdgroupId:) unsigned int adgroupId; // @synthesize adgroupId;
@property(readonly, nonatomic) BOOL hasAdgroupId; // @synthesize hasAdgroupId;
- (id)mergeFromCodedInputStream:(id)arg1;
- (int)serializedSize;
- (void)writeToCodedOutputStream:(id)arg1;
- (BOOL)isInitialized;
- (id)init;

@end

