//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, RACChannel;

@interface RACChannelProxy : NSObject
{
    RACChannel *_channel;
    id _value;
    id _target;
    NSString *_bindingName;
    void *_observationInfo;
}

+ (BOOL)automaticallyNotifiesObserversForKey:(id)arg1;
- (void).cxx_destruct;
@property void *observationInfo; // @synthesize observationInfo=_observationInfo;
@property(readonly, copy, nonatomic) NSString *bindingName; // @synthesize bindingName=_bindingName;
@property id target; // @synthesize target=_target;
@property(retain, nonatomic) id value; // @synthesize value=_value;
@property(readonly, nonatomic) RACChannel *channel; // @synthesize channel=_channel;
- (id)description;
- (void)dealloc;
- (id)initWithTarget:(id)arg1 bindingName:(id)arg2 options:(id)arg3;

@end

