//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSEvent, NSIndexPath, NSTableRowView, NSTableView;

@protocol JWCTableViewDelegate <NSObject>

@optional
- (NSTableRowView *)tableView:(NSTableView *)arg1 rowViewForRow:(long long)arg2;
- (void)tableView:(NSTableView *)arg1 didSelectRowAtIndexPath:(NSIndexPath *)arg2 withMouseEvent:(NSEvent *)arg3;
- (BOOL)tableView:(NSTableView *)arg1 shouldSelectSection:(long long)arg2;
- (BOOL)tableView:(NSTableView *)arg1 shouldSelectRowAtIndexPath:(NSIndexPath *)arg2;
@end

