//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "PBGeneratedMessage.h"

@class NSString;

@interface PSMStat : PBGeneratedMessage
{
    unsigned int hasMtype:1;
    unsigned int hasAtype:1;
    unsigned int mtype;
    NSString *atype;
}

+ (id)parseFromData:(id)arg1;
- (void).cxx_destruct;
@property(retain, nonatomic, setter=SetAtype:) NSString *atype; // @synthesize atype;
@property(readonly, nonatomic) BOOL hasAtype; // @synthesize hasAtype;
@property(nonatomic, setter=SetMtype:) unsigned int mtype; // @synthesize mtype;
@property(readonly, nonatomic) BOOL hasMtype; // @synthesize hasMtype;
- (id)mergeFromCodedInputStream:(id)arg1;
- (int)serializedSize;
- (void)writeToCodedOutputStream:(id)arg1;
- (BOOL)isInitialized;
- (id)init;

@end

