//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "PBCoding-Protocol.h"

@class NSMutableDictionary, NSString;

@interface OpenIMContactResource : NSObject <PBCoding>
{
    unsigned int funcFlag;
    unsigned int updateTime;
    NSString *acctType;
    NSString *language;
    NSMutableDictionary *wordings;
    NSMutableDictionary *urls;
    NSMutableDictionary *woringResources;
}

+ (void)initialize;
+ (void)PBArrayAdd_woringResources;
+ (void)PBArrayAdd_urls;
+ (void)PBArrayAdd_wordings;
+ (void)PBArrayAdd_language;
+ (void)PBArrayAdd_acctType;
+ (void)PBArrayAdd_updateTime;
+ (void)PBArrayAdd_funcFlag;
- (void).cxx_destruct;
@property(retain, nonatomic) NSMutableDictionary *woringResources; // @synthesize woringResources;
@property(retain, nonatomic) NSMutableDictionary *urls; // @synthesize urls;
@property(retain, nonatomic) NSMutableDictionary *wordings; // @synthesize wordings;
@property(retain, nonatomic) NSString *language; // @synthesize language;
@property(retain, nonatomic) NSString *acctType; // @synthesize acctType;
@property(nonatomic) unsigned int updateTime; // @synthesize updateTime;
@property(nonatomic) unsigned int funcFlag; // @synthesize funcFlag;
- (const void *)getValueTagIndexMap;
- (id)getValueTypeTable;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

