//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class IJSVGStyle, NSArray;

@interface IJSVGStyleSheetRule : NSObject
{
    NSArray *selectors;
    IJSVGStyle *style;
}

@property(retain, nonatomic) IJSVGStyle *style; // @synthesize style;
@property(retain, nonatomic) NSArray *selectors; // @synthesize selectors;
- (BOOL)matchesNode:(id)arg1 selector:(id *)arg2;
- (void)dealloc;

@end

