//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface IJSVGWriter : NSObject
{
}

+ (id)SVGPathStringForBezierPath:(id)arg1;
+ (id)rootElementForPath:(id)arg1;
+ (id)SVGDocumentForBezierPath:(id)arg1;
+ (id)SVGDocumentStringForBezierPath:(id)arg1;
+ (id)SVGDocumentStringForSVGGlyph:(id)arg1;

@end

