//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMService.h"

#import "IOpLogServiceExt-Protocol.h"
#import "IOpenIMOplogServiceExt-Protocol.h"
#import "MMService-Protocol.h"

@class GetContactLogic, GroupDB, MMCache, NSMutableArray, NSMutableDictionary, NSOperationQueue, NSRecursiveLock, NSString, RevokeAddMemberLogic;

@interface GroupStorage : MMService <IOpLogServiceExt, IOpenIMOplogServiceExt, MMService>
{
    GroupDB *m_groupDB;
    unsigned int m_uLoadedType;
    GetContactLogic *_getContactLogic;
    RevokeAddMemberLogic *m_revokeAddMemberLogic;
    NSMutableDictionary *m_dictGroupContacts;
    MMCache *m_groupMembersCache;
    MMCache *m_groupTopMsgsCache;
    BOOL m_hasClearData;
    BOOL _bUGRBuildSuccess;
    NSRecursiveLock *_m_groupLock;
    NSMutableDictionary *_dicShouldDeleteAllMsgAfterQuit;
    NSMutableArray *_m_UGRUpdateTaskQueue;
    NSOperationQueue *_m_UGRBuildTaskQueue;
    NSMutableArray *_getMemberDetailTasks;
    NSMutableArray *_getChatRoomInfoTasks;
    NSMutableArray *_arrGetGroupContactsDetail;
    NSMutableArray *_arrFailGroupContacts;
    NSMutableDictionary *_dicGroupContactsRetry;
    NSRecursiveLock *_retryLock;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSRecursiveLock *retryLock; // @synthesize retryLock=_retryLock;
@property(retain, nonatomic) NSMutableDictionary *dicGroupContactsRetry; // @synthesize dicGroupContactsRetry=_dicGroupContactsRetry;
@property(retain, nonatomic) NSMutableArray *arrFailGroupContacts; // @synthesize arrFailGroupContacts=_arrFailGroupContacts;
@property(retain, nonatomic) NSMutableArray *arrGetGroupContactsDetail; // @synthesize arrGetGroupContactsDetail=_arrGetGroupContactsDetail;
@property(retain, nonatomic) NSMutableArray *getChatRoomInfoTasks; // @synthesize getChatRoomInfoTasks=_getChatRoomInfoTasks;
@property(retain, nonatomic) NSMutableArray *getMemberDetailTasks; // @synthesize getMemberDetailTasks=_getMemberDetailTasks;
@property(retain, nonatomic) NSOperationQueue *m_UGRBuildTaskQueue; // @synthesize m_UGRBuildTaskQueue=_m_UGRBuildTaskQueue;
@property(nonatomic) BOOL bUGRBuildSuccess; // @synthesize bUGRBuildSuccess=_bUGRBuildSuccess;
@property(retain, nonatomic) NSMutableArray *m_UGRUpdateTaskQueue; // @synthesize m_UGRUpdateTaskQueue=_m_UGRUpdateTaskQueue;
@property(retain, nonatomic) NSMutableDictionary *dicShouldDeleteAllMsgAfterQuit; // @synthesize dicShouldDeleteAllMsgAfterQuit=_dicShouldDeleteAllMsgAfterQuit;
@property(retain, nonatomic) NSRecursiveLock *m_groupLock; // @synthesize m_groupLock=_m_groupLock;
- (void)sendRequest;
- (void)doNext;
- (void)addGroupContactToRetryQueue:(id)arg1;
- (void)SetGroupDetailWithUserName:(id)arg1 content:(id)arg2 withCompletion:(CDUnknownBlockType)arg3;
- (void)GetGroupTopMsgWithContact:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;
- (void)GetGroupDetailWithContact:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;
- (BOOL)shouldUpdateGroupTopMsg:(id)arg1;
- (void)UpdateGroupMemberDetailIfNeeded:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;
- (id)GetAllContactGroups;
- (id)GetAllGroups;
- (BOOL)GetGroupContactsFromSvr:(id)arg1 isForceGet:(BOOL)arg2;
- (BOOL)GetGroupContactsFromSvr:(id)arg1;
- (BOOL)DeleteGroupContactByUI:(id)arg1 ListType:(unsigned int)arg2 needNotify:(BOOL)arg3;
- (BOOL)RemoveGroupFromContactBook:(id)arg1 updateStatus:(unsigned long long)arg2;
- (BOOL)AddGroupToContactBook:(id)arg1 updateStatus:(unsigned long long)arg2;
- (void)ModifyGroupContact:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;
- (void)ModifyGroupMembers:(id)arg1 onlyInsertNew:(BOOL)arg2;
- (void)ModifyOpenIMGroupMember:(id)arg1;
- (void)SetGroupChatAnnouncementWithGroupUserName:(id)arg1 announceContent:(id)arg2 withCompletion:(CDUnknownBlockType)arg3;
- (void)GetGroupChatAnnouncementWithGroupUserName:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;
- (void)UpdateGroupChatMemberDetailWithGroupUserName:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;
- (BOOL)SetChatRoomSelfDisplayName:(id)arg1 DisplayName:(id)arg2 selfUsrName:(id)arg3 syncToServer:(BOOL)arg4;
- (BOOL)ModifyShouldShowGroupDisplayName:(BOOL)arg1 withGroupUsrName:(id)arg2 selfUsrName:(id)arg3 updateStatus:(unsigned long long)arg4;
- (BOOL)ModifyChatStatusNotifyOpen:(BOOL)arg1 withGroupUserName:(id)arg2 updateStatus:(unsigned long long)arg3;
- (BOOL)ModifyGroupBoxSwitch:(id)arg1 isOn:(BOOL)arg2 updateStatus:(unsigned long long)arg3;
- (BOOL)ModifyIsTop:(BOOL)arg1 withGroupUsrName:(id)arg2 updateStatus:(unsigned long long)arg3;
- (BOOL)ModifyGroupChatRemark:(id)arg1 withGroupUserName:(id)arg2;
- (BOOL)ModifyGroupChatName:(id)arg1 withGroupUserName:(id)arg2;
- (unsigned long long)GetGroupMemberCountWithGroupContact:(id)arg1;
- (unsigned long long)GetGroupMemberCountWithGroupUserName:(id)arg1;
- (id)GetMemberNameListWithGroupContact:(id)arg1;
- (id)GetGroupMemberListWithGroupContactForSearch:(id)arg1;
- (id)GetGroupMemberListWithGroupContact:(id)arg1 limit:(unsigned int)arg2 filterSelf:(BOOL)arg3;
- (id)GetGroupMemberListWithGroupUserNameForSearch:(id)arg1;
- (id)GetGroupMemberListWithGroupUserName:(id)arg1 limit:(unsigned int)arg2 filterSelf:(BOOL)arg3;
- (id)GetGroupContactList:(unsigned int)arg1 ContactType:(unsigned int)arg2;
- (id)GetGroupMemberContacts:(id)arg1;
- (id)GetGroupMemberContactsFromDB:(id)arg1;
- (id)GetGroupMemberContact:(id)arg1;
- (BOOL)IsGroupMemberContactExist:(id)arg1;
- (id)GetGroupContactsWithUserNames:(id)arg1;
- (id)GetGroupContact:(id)arg1;
- (BOOL)IsGroupContactExist:(id)arg1;
- (id)GetGroupContactWithNickName:(id)arg1;
- (BOOL)QuitGroup:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (BOOL)RevokeHistoryWithGroupUserName:(id)arg1 memberUserNameList:(id)arg2 msgData:(id)arg3 shouldRemoveMember:(BOOL)arg4 completion:(CDUnknownBlockType)arg5;
- (BOOL)DeleteGroupMemberWithGroupUserName:(id)arg1 memberUserNameList:(id)arg2 scene:(unsigned int)arg3 completion:(CDUnknownBlockType)arg4;
- (BOOL)InviteGroupMemberWithChatRoomName:(id)arg1 memberList:(id)arg2 historyInfo:(id)arg3 completion:(CDUnknownBlockType)arg4;
- (BOOL)AddGroupMembers:(id)arg1 withGroupUserName:(id)arg2 withExamineContent:(id)arg3 withHistoryInfo:(id)arg4 completion:(CDUnknownBlockType)arg5;
- (void)CreateGroupChatWithTopic:(id)arg1 groupMembers:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)resetGroupDB;
- (void)onServiceClearData;
- (void)onServiceInit;
- (id)init;
- (BOOL)UIQuitGroup:(id)arg1 deleteAllMsg:(BOOL)arg2;
- (BOOL)UIQuitGroup:(id)arg1 withConfirm:(BOOL)arg2 completion:(CDUnknownBlockType)arg3;
- (id)genOpenIMErrorString:(id)arg1;
- (int)handleCreateOpenIMChatRoomResponse:(id)arg1;
- (void)createOpenIMChatRoom:(id)arg1 WithMemberList:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (id)genCreateGroupErrorString:(id)arg1 needVerify:(char *)arg2;
- (int)handleCreateNormalChatRoomResponse:(id)arg1;
- (void)createNormalChatRoom:(id)arg1 WithMemberList:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)UICreateGroup:(id)arg1 withMemberList:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (BOOL)UIRevokeHistoryInChatRoom:(id)arg1 withMemberList:(id)arg2 withMsgData:(id)arg3 shouldRemoveMember:(BOOL)arg4 completion:(CDUnknownBlockType)arg5;
- (void)handleDelOpenIMChatRoomMemberFailed:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)deleteMemberFromOpenIMChatRoom:(id)arg1 withMemberList:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)handleDelChatRoomMemberFailed:(id)arg1 errMsg:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)deleteMemberFromChatRoom:(id)arg1 withMemberList:(id)arg2 scene:(unsigned int)arg3 completion:(CDUnknownBlockType)arg4;
- (BOOL)UIDeleteGroupMember:(id)arg1 withMemberList:(id)arg2 scene:(unsigned int)arg3 completion:(CDUnknownBlockType)arg4;
- (void)inviteNormalGroupMemberWithChatRoomName:(id)arg1 memberList:(id)arg2 historyInfo:(id)arg3 completion:(CDUnknownBlockType)arg4;
- (void)inviteOpenIMMemberWithChatRoomName:(id)arg1 memberList:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (BOOL)UIInviteGroupMemberWithChatRoomName:(id)arg1 memberList:(id)arg2 historyInfo:(id)arg3 completion:(CDUnknownBlockType)arg4;
- (void)handleAddChatRoomMemberFailed:(id)arg1;
- (void)addGroupMemberToChatRoom:(id)arg1 withMemberList:(id)arg2 withExamineContent:(id)arg3 withHistoryInfo:(id)arg4 completion:(CDUnknownBlockType)arg5;
- (void)handleAddOpenIMChatRoomMemberFailed:(id)arg1;
- (void)addGroupMemberToOpenIMChatRoom:(id)arg1 withMemberList:(id)arg2 withExamineContent:(id)arg3 completion:(CDUnknownBlockType)arg4;
- (BOOL)UIAddGroupMember:(id)arg1 withMemberList:(id)arg2 withExamineContent:(id)arg3 withHistoryInfo:(id)arg4 completion:(CDUnknownBlockType)arg5;
- (id)genAddMemberErrorString:(id)arg1;
- (id)contactWithOpenImMemberResp:(id)arg1;
- (id)contactWithMemberResp:(id)arg1;
- (void)addChatMemberNeedVerifyMsg:(id)arg1 ContactList:(id)arg2;
- (void)addCreateMsg:(id)arg1 ContactList:(id)arg2;
- (void)getOpenIMChatRoomMemberDetailWithUserName:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;
- (void)getNormalChatRoomMemberDetailWithUserName:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;
- (void)getChatroomMemberDetailWithUserName:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;
- (void)setOpenIMChatRoomAnnouncementWithUserName:(id)arg1 announceContent:(id)arg2 withCompletion:(CDUnknownBlockType)arg3;
- (void)setNormalChatRoomAnnouncementWithUserName:(id)arg1 announceContent:(id)arg2 withCompletion:(CDUnknownBlockType)arg3;
- (void)setChatRoomAnnouncementWithUserName:(id)arg1 announceContent:(id)arg2 withCompletion:(CDUnknownBlockType)arg3;
- (void)getChatRoomAnnouncementWithUserName:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;
- (BOOL)OnDelGroupContacts_Thread:(id)arg1;
- (void)OnModGroupMemberContacts_Thread:(id)arg1;
- (void)OnModGroupContacts_Thread:(id)arg1 updateBrief:(BOOL)arg2;
- (void)OnModGroupContacts_Thread:(id)arg1;
- (void)executeUpdateUGRDB:(id)arg1;
- (void)checkUpdateUGRQueue;
- (void)addUpdateUGRDataTask:(id)arg1 dbGroupMemberList:(id)arg2 modGroupMemberList:(id)arg3;
- (id)getAllCommonGroups:(id)arg1;
- (id)getUGRResult:(id)arg1;
- (BOOL)isUGRBuildSuccessed;
- (BOOL)insertBuildGURSuccesstag;
- (void)executeBuildUGRTask:(id)arg1;
- (void)buildUGRTable:(id)arg1;
- (BOOL)UpdateGroupMember:(id)arg1 propertyDict:(id)arg2;
- (BOOL)UpdateGroupMemberFlag:(id)arg1 flag:(unsigned int)arg2 isOpen:(BOOL)arg3;
- (void)realQuitGroupHandle:(BOOL)arg1 errMsg:(id)arg2 groupName:(id)arg3;
- (void)onOpenImOplogRet:(int)arg1 errMsg:(id)arg2 openImlog:(id)arg3;
- (void)onOpLogRet:(int)arg1 errMsg:(id)arg2 oplog:(id)arg3;
- (BOOL)quitOpenIMGroupChatRoom:(id)arg1 sync:(BOOL)arg2;
- (BOOL)addOpenIMChatRoomToContactBook:(id)arg1 inContactBook:(BOOL)arg2 sync:(BOOL)arg3;
- (BOOL)addOpenIMGroupSelfDisplayName:(id)arg1 DisplayName:(id)arg2 sync:(BOOL)arg3;
- (BOOL)addOpenIMChatRoomShowDislayName:(id)arg1 show:(BOOL)arg2 sync:(BOOL)arg3;
- (BOOL)addOpenIMOplogChatRoom:(id)arg1 announcement:(id)arg2 sync:(BOOL)arg3;
- (BOOL)addOpenIMOplogChatRoom:(id)arg1 withTopic:(id)arg2 sync:(BOOL)arg3;
- (BOOL)addOpenIMOplogChatRoom:(id)arg1 top:(BOOL)arg2 sync:(BOOL)arg3;
- (BOOL)addOpenIMOplogChatRoom:(id)arg1 mute:(BOOL)arg2 sync:(BOOL)arg3;
- (BOOL)addOpLog_ModifyGroupBoxSwitch:(id)arg1 bOn:(BOOL)arg2 sync:(BOOL)arg3;
- (BOOL)addOpLog_ModifyGroupBoxSwitch:(id)arg1 bOn:(BOOL)arg2;
- (BOOL)addOpLog_SetChatRoomSelfDisplayName:(id)arg1 usrName:(id)arg2 DisplayName:(id)arg3 sync:(BOOL)arg4;
- (BOOL)addOplog_ModifyShowDisplayNameWithGroupChatUserName:(id)arg1 usrName:(id)arg2 flag:(unsigned int)arg3 open:(BOOL)arg4 sync:(BOOL)arg5;
- (BOOL)addOplog_ModifyNotifyStatus:(id)arg1 withStatus:(unsigned int)arg2 sync:(BOOL)arg3;
- (unsigned int)ChatNotifyC2S:(unsigned int)arg1;
- (BOOL)addOpLog_SetGroupTopic:(id)arg1 withTopic:(id)arg2 NeedSync:(BOOL)arg3;
- (BOOL)addOplog_QuitGroup:(id)arg1 withUsrName:(id)arg2 NeedSync:(BOOL)arg3;
- (BOOL)addOpLog_ModifyGroupContact:(id)arg1 addScene:(unsigned int)arg2 sync:(BOOL)arg3;
- (BOOL)addOpLog_ModifyGroupContact:(id)arg1 sync:(BOOL)arg2;
- (void)realOperateGroupTopMessage:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;
- (void)unstickyGroupTopMessageWithTopMsg:(id)arg1 msgData:(id)arg2 opValue:(unsigned int)arg3 withCompletion:(CDUnknownBlockType)arg4;
- (void)operateGroupTopMessageWithUserName:(id)arg1 msgData:(id)arg2 opValue:(unsigned int)arg3 withCompletion:(CDUnknownBlockType)arg4;
- (void)updateCacheTopMsgArr:(id)arg1;
- (void)removeGroupTopMsgCache:(id)arg1;
- (void)setGroupTopMsgCache:(id)arg1 groupName:(id)arg2;
- (id)getGroupTopMsgArrCache:(id)arg1;
- (id)getCanShowTopMsgArr:(id)arg1;
- (id)getGroupTopMsgWithTopId:(unsigned int)arg1 userName:(id)arg2;
- (id)getGroupTopMsgWithSvrID:(unsigned long long)arg1 userName:(id)arg2;
- (id)getGroupTopMsgArr:(id)arg1 isAllResult:(BOOL)arg2;
- (BOOL)updateStatusOnTopMsgDB:(id)arg1 msgSvrID:(unsigned long long)arg2;
- (BOOL)insertTopMsgToDB:(id)arg1;
- (void)deleteDefaultGroupTopMsg:(id)arg1;
- (void)insertDefault:(id)arg1;
- (void)checkAndInsertDefault:(id)arg1;
- (void)loadNetWorkDataToDB:(id)arg1 groupName:(id)arg2;
- (void)notifyModifyGroupMemberContactOnMainThread:(id)arg1;
- (void)notifyModifyGroupContactsOnMainThread:(id)arg1;
- (void)notifyDeleteGroupContactsOnMainThread:(id)arg1;
- (BOOL)deleteMemberContactsInLocal:(id)arg1;
- (BOOL)deleteMemberContactInLocal:(id)arg1;
- (BOOL)quitGroupInLocal:(id)arg1;
- (BOOL)deleteGroupContactsInLocal:(id)arg1;
- (BOOL)deleteGroupContactInLocal:(id)arg1;
- (void)deleteGroupMember:(id)arg1 removedMemberNameList:(id)arg2;
- (BOOL)checkIsGroupNumberForQuitGroup:(id)arg1;
- (BOOL)addOrModifyGroupContactMembers:(id)arg1 onlyInsertNew:(BOOL)arg2;
- (BOOL)addOrModifyGroupContactMembers:(id)arg1;
- (BOOL)addOrModifyGroupContact:(id)arg1 arrMembersList:(id)arg2;
- (BOOL)loadGroupContactsWithType:(unsigned int)arg1;
- (void)removeGroupMemberContactsCache:(id)arg1;
- (void)removeGroupMemberContactCache:(id)arg1;
- (void)setGroupMemberContactsCache:(id)arg1;
- (void)setGroupMemberContactCache:(id)arg1;
- (id)getGroupMemberContactCache:(id)arg1;
- (unsigned long long)getGroupMemberCacheCount;
- (void)removeGroupContactsCache:(id)arg1;
- (void)removeGroupContactCache:(id)arg1;
- (void)setGroupContactsCache:(id)arg1;
- (void)setGroupContactCache:(id)arg1;
- (id)getGroupContactCacheKeys;
- (unsigned long long)getGroupContactCacheCount;
- (id)getGroupContactCache:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

