//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSPanel.h>

@class JTPopoverMenuFontSizeButton, NSEvent, NSView;
@protocol JTPopoverFontSizeMenuForWechatDelegate;

@interface JTPopoverFontSizeMenuForWechat : NSPanel
{
    id <JTPopoverFontSizeMenuForWechatDelegate> _fontSizeDelegate;
    NSEvent *_localMouseDownEventMonitor;
    NSEvent *_globalMouseDownEventMonitor;
    JTPopoverMenuFontSizeButton *_minButton;
    JTPopoverMenuFontSizeButton *_mediumButton;
    JTPopoverMenuFontSizeButton *_maxButton;
    NSView *_superView;
}

- (void).cxx_destruct;
@property(nonatomic) __weak NSView *superView; // @synthesize superView=_superView;
@property(retain, nonatomic) JTPopoverMenuFontSizeButton *maxButton; // @synthesize maxButton=_maxButton;
@property(retain, nonatomic) JTPopoverMenuFontSizeButton *mediumButton; // @synthesize mediumButton=_mediumButton;
@property(retain, nonatomic) JTPopoverMenuFontSizeButton *minButton; // @synthesize minButton=_minButton;
@property(retain, nonatomic) NSEvent *globalMouseDownEventMonitor; // @synthesize globalMouseDownEventMonitor=_globalMouseDownEventMonitor;
@property(retain, nonatomic) NSEvent *localMouseDownEventMonitor; // @synthesize localMouseDownEventMonitor=_localMouseDownEventMonitor;
@property(nonatomic) __weak id <JTPopoverFontSizeMenuForWechatDelegate> fontSizeDelegate; // @synthesize fontSizeDelegate=_fontSizeDelegate;
- (void)unregisterMouseDownEventMonitor;
- (void)registerMouseDownEventMonitor;
- (void)cancelTracking;
- (void)popUpMenuAtLocation:(struct CGPoint)arg1 inView:(id)arg2;
- (void)fontSizeDidChanged:(id)arg1;
- (void)setupButtons;
- (void)setupGaussEffect;
- (void)dealloc;
- (id)init;

@end

