//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface TRTCRemoteStatistics : NSObject
{
    unsigned int _finalLoss;
    unsigned int _width;
    unsigned int _height;
    unsigned int _frameRate;
    unsigned int _videoBitrate;
    unsigned int _audioSampleRate;
    unsigned int _audioBitrate;
    unsigned int _jitterBufferDelay;
    unsigned int _point2PointDelay;
    unsigned int _audioTotalBlockTime;
    unsigned int _audioBlockRate;
    unsigned int _videoTotalBlockTime;
    unsigned int _videoBlockRate;
    NSString *_userId;
    long long _streamType;
}

- (void).cxx_destruct;
@property(nonatomic) long long streamType; // @synthesize streamType=_streamType;
@property(nonatomic) unsigned int videoBlockRate; // @synthesize videoBlockRate=_videoBlockRate;
@property(nonatomic) unsigned int videoTotalBlockTime; // @synthesize videoTotalBlockTime=_videoTotalBlockTime;
@property(nonatomic) unsigned int audioBlockRate; // @synthesize audioBlockRate=_audioBlockRate;
@property(nonatomic) unsigned int audioTotalBlockTime; // @synthesize audioTotalBlockTime=_audioTotalBlockTime;
@property(nonatomic) unsigned int point2PointDelay; // @synthesize point2PointDelay=_point2PointDelay;
@property(nonatomic) unsigned int jitterBufferDelay; // @synthesize jitterBufferDelay=_jitterBufferDelay;
@property(nonatomic) unsigned int audioBitrate; // @synthesize audioBitrate=_audioBitrate;
@property(nonatomic) unsigned int audioSampleRate; // @synthesize audioSampleRate=_audioSampleRate;
@property(nonatomic) unsigned int videoBitrate; // @synthesize videoBitrate=_videoBitrate;
@property(nonatomic) unsigned int frameRate; // @synthesize frameRate=_frameRate;
@property(nonatomic) unsigned int height; // @synthesize height=_height;
@property(nonatomic) unsigned int width; // @synthesize width=_width;
@property(nonatomic) unsigned int finalLoss; // @synthesize finalLoss=_finalLoss;
@property(retain, nonatomic) NSString *userId; // @synthesize userId=_userId;
- (id)description;

@end

