//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MessageSender.h"

#import "ICdnComMgrExt-Protocol.h"
#import "MMCGIDelegate-Protocol.h"

@class CdnTaskInfo, NSData, NSString;

@interface ImgMessageSender : MessageSender <ICdnComMgrExt, MMCGIDelegate>
{
    CdnTaskInfo *m_oCurTaskInfo;
    NSString *m_nsMsgMd5;
    unsigned int m_uMsgCrc32;
    BOOL _needUpdateMid;
    NSData *_originImgData;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSData *originImgData; // @synthesize originImgData=_originImgData;
@property(nonatomic) BOOL needUpdateMid; // @synthesize needUpdateMid=_needUpdateMid;
@property(retain, nonatomic) CdnTaskInfo *oCurTaskInfo; // @synthesize oCurTaskInfo=m_oCurTaskInfo;
- (void)OnResponseCGI:(BOOL)arg1 sessionId:(unsigned int)arg2 cgiWrap:(id)arg3;
- (void)onUploadOrHitCheckSuccess:(id)arg1 nsAesKey:(id)arg2;
- (void)retryUploadAndNoHitCheck;
- (void)OnCdnUpload:(id)arg1;
- (void)OnCdnUploadProgress:(id)arg1;
- (void)onSendOK;
- (void)onSendFail;
- (BOOL)sendUploadImgRequest:(id)arg1 fileExists:(BOOL)arg2;
- (void)uploadSuccessByCDN:(id)arg1;
- (void)uploadFailByCDN:(int)arg1;
- (void)startUploadImgByCDNWithHitCheck:(BOOL)arg1;
- (void)startSending;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

