//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface _TtC6WeChat28SnsNotificationCellViewModel : NSObject
{
    // Error parsing type: , name: messageDetailUpdate
    // Error parsing type: , name: message
    // Error parsing type: , name: dataItem
    // Error parsing type: , name: type
    // Error parsing type: , name: nickName
    // Error parsing type: , name: height
    // Error parsing type: , name: comment
    // Error parsing type: , name: calculatHeightComment
    // Error parsing type: , name: isIgnore
    // Error parsing type: , name: isLoadingMessageDetial
}

- (void).cxx_destruct;
- (id)init;

@end

