//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC6WeChat20SnsPublishConfigView.h"

#import "NSCollectionViewDataSource-Protocol.h"
#import "NSCollectionViewDelegate-Protocol.h"

@interface _TtC6WeChat26SnsPublishAvatarConfigView : _TtC6WeChat20SnsPublishConfigView <NSCollectionViewDataSource, NSCollectionViewDelegate>
{
    // Error parsing type: , name: usernames
    // Error parsing type: , name: collectionView
    // Error parsing type: , name: scrollView
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)init;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (id)collectionView:(id)arg1 itemForRepresentedObjectAtIndexPath:(id)arg2;

@end

