//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC6WeChat26SafeModeBaseViewController.h"

@interface _TtC6WeChat28SafeModeDetectViewController : _TtC6WeChat26SafeModeBaseViewController
{
    // Error parsing type: , name: descriptionLabel
    // Error parsing type: , name: progressToast
    // Error parsing type: , name: timer
    // Error parsing type: , name: hasLoadConfig
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)onClickNextButton:(id)arg1;
- (void)viewDidAppear;
- (void)viewDidLoad;

@end

