//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@interface _TtC6WeChat26SnsFeedRowPrivateViewModel : _TtCs12_SwiftObject
{
    // Error parsing type: , name: height
    // Error parsing type: , name: isLastRow
    // Error parsing type: , name: isLiked
    // Error parsing type: , name: isFolder
    // Error parsing type: , name: dataItem
    // Error parsing type: , name: items
}

@end

