//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSView.h>

@interface _TtC6WeChat18SnsPlaceHolderView : NSView
{
    // Error parsing type: , name: retryToLoadData
    // Error parsing type: , name: descTitleField
    // Error parsing type: , name: loadingImageView
    // Error parsing type: , name: retryButton
    // Error parsing type: , name: type
}

- (void).cxx_destruct;
- (void)onRetryButtonClick;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)viewDidChangeEffectiveAppearance;
- (void)setFrameSize:(struct CGSize)arg1;

@end

