//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "PBGeneratedMessage.h"

@class NSData, NSMutableArray;

@interface BusinessServiceInfo : PBGeneratedMessage
{
    unsigned int hasTitle:1;
    unsigned int hasServiceUrl:1;
    NSData *title;
    NSData *serviceUrl;
    NSMutableArray *mutableItemFieldListList;
}

+ (id)parseFromData:(id)arg1;
- (void).cxx_destruct;
@property(retain, nonatomic) NSMutableArray *mutableItemFieldListList; // @synthesize mutableItemFieldListList;
@property(retain, nonatomic, setter=SetServiceUrl:) NSData *serviceUrl; // @synthesize serviceUrl;
@property(readonly, nonatomic) BOOL hasServiceUrl; // @synthesize hasServiceUrl;
@property(retain, nonatomic, setter=SetTitle:) NSData *title; // @synthesize title;
@property(readonly, nonatomic) BOOL hasTitle; // @synthesize hasTitle;
- (void)addItemFieldList:(id)arg1;
- (void)addItemFieldListFromArray:(id)arg1;
- (id)mergeFromCodedInputStream:(id)arg1;
- (int)serializedSize;
- (void)writeToCodedOutputStream:(id)arg1;
- (BOOL)isInitialized;
@property(retain, nonatomic) NSMutableArray *itemFieldList; // @dynamic itemFieldList;
- (id)itemFieldListList;
- (id)init;

@end

