//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class EmoticonMsgInfo, MMEmotionGroupInfo;

@protocol EmoticonDownloadMgrExt <NSObject>

@optional
- (void)storeEmoticonIconDownloadFinished:(MMEmotionGroupInfo *)arg1;
- (void)emoticonDownloadFailed:(EmoticonMsgInfo *)arg1;
- (void)emoticonDownloadFinished:(EmoticonMsgInfo *)arg1;
@end

