//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface FavoritesUtil : NSObject
{
}

+ (id)convertRecordMsg:(id)arg1 toFavDataListFromDataList:(id)arg2 withParentSourceId:(id)arg3;
+ (id)convertRecordMsg:(id)arg1 toWeWorkDataListFromDataList:(id)arg2 withParentSourceId:(id)arg3;
+ (id)safeLocalStr:(id)arg1 defaultVal:(id)arg2;
+ (id)videoDurationWithDataField:(id)arg1;
+ (id)getDataSourceId:(id)arg1;
+ (id)ConvertMsgList2FavItem:(id)arg1;

@end

