//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "PBGeneratedMessage.h"

@class BaseRequest, NSMutableArray;

@interface GetAppSettingRequest : PBGeneratedMessage
{
    unsigned int hasBaseRequest:1;
    unsigned int hasAppCount:1;
    unsigned int appCount;
    BaseRequest *baseRequest;
    NSMutableArray *mutableAppSettingReqListList;
}

+ (id)parseFromData:(id)arg1;
- (void).cxx_destruct;
@property(retain, nonatomic) NSMutableArray *mutableAppSettingReqListList; // @synthesize mutableAppSettingReqListList;
@property(nonatomic, setter=SetAppCount:) unsigned int appCount; // @synthesize appCount;
@property(readonly, nonatomic) BOOL hasAppCount; // @synthesize hasAppCount;
@property(retain, nonatomic, setter=SetBaseRequest:) BaseRequest *baseRequest; // @synthesize baseRequest;
@property(readonly, nonatomic) BOOL hasBaseRequest; // @synthesize hasBaseRequest;
- (void)addAppSettingReqList:(id)arg1;
- (void)addAppSettingReqListFromArray:(id)arg1;
- (id)mergeFromCodedInputStream:(id)arg1;
- (int)serializedSize;
- (void)writeToCodedOutputStream:(id)arg1;
- (BOOL)isInitialized;
@property(retain, nonatomic) NSMutableArray *appSettingReqList; // @dynamic appSettingReqList;
- (id)appSettingReqListList;
- (id)init;

@end

