//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "PBGeneratedMessage.h"

@class AcctTypeResource, AppIdResource, BaseResponse, NSMutableArray;

@interface GetOpenIMResourceResp : PBGeneratedMessage
{
    unsigned int hasBaseResponse:1;
    unsigned int hasAppidResource:1;
    unsigned int hasAcctTypeResource:1;
    BaseResponse *baseResponse;
    AppIdResource *appidResource;
    AcctTypeResource *acctTypeResource;
    NSMutableArray *mutableWordingIdResourceList;
}

+ (id)parseFromData:(id)arg1;
- (void).cxx_destruct;
@property(retain, nonatomic) NSMutableArray *mutableWordingIdResourceList; // @synthesize mutableWordingIdResourceList;
@property(retain, nonatomic, setter=SetAcctTypeResource:) AcctTypeResource *acctTypeResource; // @synthesize acctTypeResource;
@property(readonly, nonatomic) BOOL hasAcctTypeResource; // @synthesize hasAcctTypeResource;
@property(retain, nonatomic, setter=SetAppidResource:) AppIdResource *appidResource; // @synthesize appidResource;
@property(readonly, nonatomic) BOOL hasAppidResource; // @synthesize hasAppidResource;
@property(retain, nonatomic, setter=SetBaseResponse:) BaseResponse *baseResponse; // @synthesize baseResponse;
@property(readonly, nonatomic) BOOL hasBaseResponse; // @synthesize hasBaseResponse;
- (void)addWordingIdResource:(id)arg1;
- (void)addWordingIdResourceFromArray:(id)arg1;
- (id)mergeFromCodedInputStream:(id)arg1;
- (int)serializedSize;
- (void)writeToCodedOutputStream:(id)arg1;
- (BOOL)isInitialized;
@property(retain, nonatomic) NSMutableArray *wordingIdResource; // @dynamic wordingIdResource;
- (id)wordingIdResourceList;
- (id)init;

@end

