//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "IJSVGParserDelegate-Protocol.h"
#import "NSPasteboardWriting-Protocol.h"

@class IJSVGLayer, IJSVGParser, NSColor, NSMutableDictionary, NSString;
@protocol IJSVGDelegate;

@interface IJSVG : NSObject <NSPasteboardWriting, IJSVGParserDelegate>
{
    IJSVGParser *_group;
    double _scale;
    double _clipScale;
    id <IJSVGDelegate> _delegate;
    IJSVGLayer *_layerTree;
    struct CGRect _viewBox;
    struct CGSize _proposedViewSize;
    double _lastProposedBackingScale;
    long long _lastProposedRenderQuality;
    double _backingScale;
    NSMutableDictionary *_replacementColors;
    struct {
        unsigned int shouldHandleForeignObject:1;
        unsigned int handleForeignObject:1;
        unsigned int shouldHandleSubSVG:1;
    } _respondsTo;
    BOOL clipToViewport;
    NSColor *fillColor;
    NSColor *strokeColor;
    double strokeWidth;
    long long lineCapStyle;
    long long lineJoinStyle;
    CDUnknownBlockType renderingBackingScaleHelper;
    long long renderQuality;
}

+ (id)svgNamed:(id)arg1 useCache:(BOOL)arg2 error:(id *)arg3 delegate:(id)arg4;
+ (id)svgNamed:(id)arg1 error:(id *)arg2 delegate:(id)arg3;
+ (id)svgNamed:(id)arg1 delegate:(id)arg2;
+ (id)svgNamed:(id)arg1 useCache:(BOOL)arg2 delegate:(id)arg3;
+ (id)svgNamed:(id)arg1;
+ (id)svgNamed:(id)arg1 error:(id *)arg2;
@property(nonatomic) long long renderQuality; // @synthesize renderQuality;
@property(nonatomic) BOOL clipToViewport; // @synthesize clipToViewport;
@property(copy, nonatomic) CDUnknownBlockType renderingBackingScaleHelper; // @synthesize renderingBackingScaleHelper;
@property(nonatomic) long long lineJoinStyle; // @synthesize lineJoinStyle;
@property(nonatomic) long long lineCapStyle; // @synthesize lineCapStyle;
@property(nonatomic) double strokeWidth; // @synthesize strokeWidth;
@property(retain, nonatomic) NSColor *strokeColor; // @synthesize strokeColor;
@property(retain, nonatomic) NSColor *fillColor; // @synthesize fillColor;
- (void)svgParser:(id)arg1 handleForeignObject:(id)arg2 document:(id)arg3;
- (BOOL)svgParser:(id)arg1 shouldHandleForeignObject:(id)arg2;
- (void)svgParser:(id)arg1 foundSubSVG:(id)arg2 withSVGString:(id)arg3;
- (id)pasteboardPropertyListForType:(id)arg1;
- (id)writableTypesForPasteboard:(id)arg1;
- (void)_beginDraw:(struct CGRect)arg1;
- (void)setReplacementColors:(id)arg1;
- (void)replaceColor:(id)arg1 withColor:(id)arg2;
- (void)removeReplacementColor:(id)arg1;
- (void)removeAllReplacementColors;
- (id)visibleColors;
- (id)layer;
- (id)layerWithTree:(id)arg1;
- (void)_askHelperForBackingScale;
- (BOOL)_drawInRect:(struct CGRect)arg1 context:(struct CGContext *)arg2 error:(id *)arg3;
- (void)drawInRect:(struct CGRect)arg1 context:(struct CGContext *)arg2;
- (struct CGRect)computeRectDrawingInRect:(struct CGRect)arg1 isValid:(char *)arg2;
- (double)computeBackingScale:(double)arg1;
- (BOOL)drawInRect:(struct CGRect)arg1 error:(id *)arg2;
- (BOOL)drawInRect:(struct CGRect)arg1;
- (BOOL)drawAtPoint:(struct CGPoint)arg1 size:(struct CGSize)arg2 error:(id *)arg3;
- (BOOL)drawAtPoint:(struct CGPoint)arg1 size:(struct CGSize)arg2;
- (void)prepForDrawingInView:(id)arg1;
- (void)_endVectorDraw;
- (void)_beginVectorDraw;
- (void)beginVectorDraw;
- (void)endVectorDraw;
- (id)PDFDataWithRect:(struct CGRect)arg1 error:(id *)arg2;
- (id)PDFDataWithRect:(struct CGRect)arg1;
- (id)PDFData:(id *)arg1;
- (id)PDFData;
- (id)imageByMaintainingAspectRatioWithSize:(struct CGSize)arg1 flipped:(BOOL)arg2 error:(id *)arg3;
- (id)imageWithSize:(struct CGSize)arg1 flipped:(BOOL)arg2 error:(id *)arg3;
- (struct CGRect)computeOriginalDrawingFrameWithSize:(struct CGSize)arg1;
- (id)imageWithSize:(struct CGSize)arg1 flipped:(BOOL)arg2;
- (id)imageWithSize:(struct CGSize)arg1 error:(id *)arg2;
- (id)imageWithSize:(struct CGSize)arg1;
- (id)SVGStringWithOptions:(long long)arg1;
- (id)subSVGs:(BOOL)arg1;
- (id)glyphs;
- (BOOL)isFont;
- (id)rootNode;
- (struct CGRect)viewBox;
- (void)_checkDelegate;
- (id)identifier;
- (void)_setupBasicsFromAnyInitializer;
- (void)_setupBasicInfoFromGroup;
- (void)discardDOM;
- (id)initWithSVGString:(id)arg1 error:(id *)arg2 delegate:(id)arg3;
- (id)initWithSVGString:(id)arg1 error:(id *)arg2;
- (id)initWithSVGString:(id)arg1;
- (id)initWithFilePathURL:(id)arg1 useCache:(BOOL)arg2 error:(id *)arg3 delegate:(id)arg4;
- (id)initWithFilePathURL:(id)arg1 delegate:(id)arg2;
- (id)initWithFilePathURL:(id)arg1 useCache:(BOOL)arg2;
- (id)initWithFilePathURL:(id)arg1 error:(id *)arg2;
- (id)initWithFilePathURL:(id)arg1;
- (id)initWithFile:(id)arg1 error:(id *)arg2 delegate:(id)arg3;
- (id)initWithFile:(id)arg1 delegate:(id)arg2;
- (id)initWithFile:(id)arg1 error:(id *)arg2;
- (id)initWithFile:(id)arg1 useCache:(BOOL)arg2 error:(id *)arg3 delegate:(id)arg4;
- (id)initWithFile:(id)arg1 useCache:(BOOL)arg2;
- (id)initWithFile:(id)arg1;
- (id)initWithSVGLayer:(id)arg1 viewBox:(struct CGRect)arg2;
- (id)initWithImage:(id)arg1;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

