//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "PBGeneratedMessage.h"

@class BaseResponse, NSMutableArray;

@interface InitContactResp : PBGeneratedMessage
{
    unsigned int hasBaseResponse:1;
    unsigned int hasCurrentWxcontactSeq:1;
    unsigned int hasCurrentChatRoomContactSeq:1;
    unsigned int hasContinueFlag:1;
    unsigned int currentWxcontactSeq;
    unsigned int currentChatRoomContactSeq;
    unsigned int continueFlag;
    BaseResponse *baseResponse;
    NSMutableArray *mutableContactUsernameListList;
}

+ (id)parseFromData:(id)arg1;
- (void).cxx_destruct;
@property(retain, nonatomic) NSMutableArray *mutableContactUsernameListList; // @synthesize mutableContactUsernameListList;
@property(nonatomic, setter=SetContinueFlag:) unsigned int continueFlag; // @synthesize continueFlag;
@property(readonly, nonatomic) BOOL hasContinueFlag; // @synthesize hasContinueFlag;
@property(nonatomic, setter=SetCurrentChatRoomContactSeq:) unsigned int currentChatRoomContactSeq; // @synthesize currentChatRoomContactSeq;
@property(readonly, nonatomic) BOOL hasCurrentChatRoomContactSeq; // @synthesize hasCurrentChatRoomContactSeq;
@property(nonatomic, setter=SetCurrentWxcontactSeq:) unsigned int currentWxcontactSeq; // @synthesize currentWxcontactSeq;
@property(readonly, nonatomic) BOOL hasCurrentWxcontactSeq; // @synthesize hasCurrentWxcontactSeq;
@property(retain, nonatomic, setter=SetBaseResponse:) BaseResponse *baseResponse; // @synthesize baseResponse;
@property(readonly, nonatomic) BOOL hasBaseResponse; // @synthesize hasBaseResponse;
- (void)addContactUsernameListFromArray:(id)arg1;
- (void)addContactUsernameList:(id)arg1;
- (id)mergeFromCodedInputStream:(id)arg1;
- (int)serializedSize;
- (void)writeToCodedOutputStream:(id)arg1;
- (BOOL)isInitialized;
@property(retain, nonatomic) NSMutableArray *contactUsernameList; // @dynamic contactUsernameList;
- (id)contactUsernameListList;
- (id)init;

@end

