//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMService.h"

#import "LVLiveServiceExt-Protocol.h"
#import "MMConfigMgrExt-Protocol.h"
#import "MMService-Protocol.h"

@class LVWaitOpenLiveInfo, NSString;

@interface LiveUIControl : MMService <LVLiveServiceExt, MMService, MMConfigMgrExt>
{
    LVWaitOpenLiveInfo *_waitOpenLiveInfo;
}

- (void).cxx_destruct;
@property(retain, nonatomic) LVWaitOpenLiveInfo *waitOpenLiveInfo; // @synthesize waitOpenLiveInfo=_waitOpenLiveInfo;
- (void)onLiveExitResult:(BOOL)arg1 andLiveId:(unsigned long long)arg2;
- (id)getUnRunLive;
- (BOOL)isHaveUnRunLive;
- (void)joinNewLiveWithLiveId:(unsigned long long)arg1 andRoomId:(id)arg2 andLiveStatus:(int)arg3 andEntrance:(long long)arg4;
- (unsigned long long)getCurrentUserLiveStatus;
- (BOOL)isJoinSelfLive:(unsigned long long)arg1;
- (void)orderFrontLiveWindow;
- (void)makeKeyAndOrderFrontLiveWindow;
- (BOOL)checkCanJoinNewLiveAndShowAlert:(unsigned long long)arg1 andRoomId:(id)arg2 andEntrance:(long long)arg3;
- (BOOL)checkCanCreatNewLiveAndShowAlert:(id)arg1;
- (BOOL)isLiveWorking;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

