//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMService.h"

#import "LVLiveServiceExt-Protocol.h"
#import "LVLiveTaskExt-Protocol.h"
#import "MMService-Protocol.h"

@class NSMutableArray, NSString;

@interface LVLiveCommentDataPostEngine : MMService <LVLiveTaskExt, LVLiveServiceExt, MMService>
{
    BOOL _isPosting;
    NSMutableArray *_postTaskQueue;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSMutableArray *postTaskQueue; // @synthesize postTaskQueue=_postTaskQueue;
@property(nonatomic) BOOL isPosting; // @synthesize isPosting=_isPosting;
- (void)onPostLiveMessageResult:(id)arg1 andliveId:(unsigned long long)arg2 andRoomId:(id)arg3;
- (BOOL)applyPostLiveMessageWithPostTask:(id)arg1;
- (void)onExitLiveSuccessWithLiveTask:(id)arg1;
- (void)postNextTask;
- (void)postLiveCommentWithContent:(id)arg1 localSeq:(long long)arg2 clientMsgId:(id)arg3 taskId:(id)arg4 msgType:(unsigned int)arg5 nickName:(id)arg6;
- (void)onServiceClearData;
- (void)unRegisterExtension;
- (void)registerExtension;
- (void)onServiceInit;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

