//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class WCTDatabase;

@interface MMAppMsgBaseDB : NSObject
{
    WCTDatabase *_m_db;
}

- (void).cxx_destruct;
@property(retain, nonatomic) WCTDatabase *m_db; // @synthesize m_db=_m_db;
- (void)initDB;
- (void)dealloc;
- (void)closeDB;
- (id)init;

@end

