//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMTextMessageCellView.h"

@interface MMAppBaseMessageCellView : MMTextMessageCellView
{
}

- (void)setChoosable:(BOOL)arg1;
- (BOOL)allowChoose;
- (BOOL)allowRefer;
- (BOOL)allowMultipleSelect;
- (BOOL)allowRecall;
- (id)getSection2MenuItem;
- (id)getSection1MenuItem;
- (id)getSection0MenuItem;
- (void)prepareForReuse;
- (id)initWithFrame:(struct CGRect)arg1;

@end

