//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "MMCGIDelegate-Protocol.h"

@class MMCondition, NSString;

@interface MMCGIRequester : NSObject <MMCGIDelegate>
{
    unsigned int _cgiSessionId;
    unsigned int _functionID;
    CDUnknownBlockType _onResponse;
    MMCondition *_condition;
}

+ (id)requestCGI:(unsigned int)arg1 Body:(id)arg2 decryptKey:(id)arg3 Response:(CDUnknownBlockType)arg4;
+ (id)requestCGI:(unsigned int)arg1 Body:(id)arg2 UserData:(id)arg3 Response:(CDUnknownBlockType)arg4;
+ (id)requestCGI:(unsigned int)arg1 Body:(id)arg2 Response:(CDUnknownBlockType)arg3;
- (void).cxx_destruct;
@property(nonatomic) unsigned int functionID; // @synthesize functionID=_functionID;
@property(retain, nonatomic) MMCondition *condition; // @synthesize condition=_condition;
@property(nonatomic) unsigned int cgiSessionId; // @synthesize cgiSessionId=_cgiSessionId;
@property(copy, nonatomic) CDUnknownBlockType onResponse; // @synthesize onResponse=_onResponse;
- (void)OnResponseCGI:(BOOL)arg1 sessionId:(unsigned int)arg2 cgiWrap:(id)arg3;
- (void)waitForResponseForever;
- (BOOL)waitForResponseWithTimeout:(double)arg1;
- (void)cancel;
- (BOOL)startRequestWithFunctionID:(unsigned int)arg1 Request:(id)arg2 UserData:(id)arg3 decryptKey:(id)arg4 OnResponse:(CDUnknownBlockType)arg5;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

