//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMService.h"

#import "IMessageExt-Protocol.h"
#import "MMPackageDownloadMgrExt-Protocol.h"
#import "MMService-Protocol.h"

@class JDWebViewMenuData, NSDictionary, NSMutableDictionary, NSString;

@interface MMConfigMgr : MMService <MMPackageDownloadMgrExt, IMessageExt, MMService>
{
    NSMutableDictionary *m_dicCacheConfigSeperator;
    NSMutableDictionary *m_dicCacheConfig;
    NSMutableDictionary *m_dicConfig;
    NSMutableDictionary *m_dicDynamicConfig;
    NSMutableDictionary *m_dicDynamicConfigSplit;
    int m_iVersion;
    NSMutableDictionary *m_dicJDConfigCache;
    JDWebViewMenuData *m_JDMenuCache;
    NSDictionary *m_dicPrefetchDomains;
    BOOL m_bDomainPrefetchEnabled;
}

- (void).cxx_destruct;
@property(retain) NSMutableDictionary *m_dicCacheConfig; // @synthesize m_dicCacheConfig;
@property(retain) NSMutableDictionary *m_dicCacheConfigSeperator; // @synthesize m_dicCacheConfigSeperator;
- (id)getJDWebviewMenuData;
- (id)prefetchedDomainDictWithXMLString:(id)arg1;
- (void)loadDNSPrefetchConfig;
- (id)prefetchedDomainsForDomain:(id)arg1;
- (void)updateSignalingScenes;
- (void)updateStaticConfig:(id)arg1 withValue:(id)arg2;
- (id)getAllStaticKey;
- (unsigned int)uintFromDynamicConfigForKey:(id)arg1 defaultValue:(unsigned int)arg2;
- (unsigned int)uintFromDynamicConfigForKey:(id)arg1;
- (id)valueFromDynamicConfigForKey:(id)arg1;
- (unsigned int)uintForKey:(id)arg1 config:(id)arg2;
- (id)valueForKey:(id)arg1 config:(id)arg2;
- (id)arrSubValueForKey:(id)arg1 config:(id)arg2 seperator:(id)arg3;
- (void)onGetNewXmlMsg:(id)arg1 type:(id)arg2 msgData:(id)arg3;
- (void)onLanguageChange;
- (void)FFAddRecvFavZZ;
- (void)dealloc;
- (id)init;
- (void)onServiceReloadData;
- (void)onServiceInit;
- (void)loadData;
- (long long)getMultiAgcRxLimiter;
- (long long)getMultiAgcRxGain;
- (long long)getMultiAgcRxTarget;
- (long long)getMultiAgcRxFlag;
- (long long)getMT3dDeltaAngle:(int *)arg1 withLen:(int)arg2;
- (long long)getMT3dEchoLevel:(int *)arg1 withLen:(int)arg2;
- (long long)getMT3dAzimuths:(int *)arg1 withLen:(int)arg2;
- (long long)getMT3dFlag;
- (long long)getMultiTalkAudioUnitSubType;
- (long long)getMultiTalkAgclimiter;
- (long long)getMultiTalkAgcflag;
- (long long)getMultiTalkAgcgaindb;
- (long long)getMultiTalkAgcDnGainTHR;
- (long long)getMultiTalkAgcCompRatio;
- (long long)getMultiTalkAgctargetdb;
- (long long)getMultiTalkAgcMode;
- (long long)getMultiECModeLevel:(BOOL)arg1;
- (long long)getMultiTalkAecMode;
- (long long)getMultiTalkNsMode;
- (unsigned int)getInputLimitEmotionBufSize;
- (unsigned int)getInputLimitEmotionWidth;
- (unsigned int)getInputLimitFavEmotionCount;
- (unsigned int)getInputLimitAppMsgEmotionBufSize;
- (long long)getVoipkeyABtestConfig;
- (long long)getVoipkeyVer;
- (long long)getVoipkeyPhone;
- (long long)getVoipkeyTime;
- (long long)getVoipkeyMicadd;
- (long long)getVoipkeyMicnum;
- (long long)getVoipkeyMT3Dtype;
- (long long)getVoipkeyGtype;
- (long long)getVoipkeyStype;
- (void)saveDynamicConfigSplit;
- (void)loadDynamicConfigSplit;
- (id)getDynamicConfigSplitFilePath;
- (id)getDynamicConfigFilePath;
- (void)initCacheStaticConfig;
- (void)initStaticConfig:(id)arg1;
- (void)mergeDynamicConfig:(id)arg1;
- (void)initDynamicConfig:(id)arg1;
- (id)parseDynamicConfig:(id)arg1 type:(const char *)arg2;
- (void)initConfig:(id)arg1 for:(id)arg2;
- (BOOL)isItemSupportCountry:(id)arg1 item:(struct XmlReaderNode_t *)arg2;
- (BOOL)isItemSupportLanguage:(id)arg1 item:(struct XmlReaderNode_t *)arg2;
- (id)addConfigName:(id)arg1 forConfig:(id)arg2;
- (void)downLoadConfig;
- (void)onPackageNeedUpdate:(id)arg1 withPackIDs:(id)arg2;
- (void)onPackageListUpdated:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

