//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSView.h>

@class MMContactsPrivacyItem, MMITSwitch, NSImageView, NSTextField, SVGImageView;

@interface MMContactPrivacyCellView : NSView
{
    BOOL _bSelected;
    SVGImageView *_checkView;
    NSImageView *_iconImageView;
    NSTextField *_descTextField;
    CDUnknownBlockType _didMouseUpBlock;
    MMContactsPrivacyItem *_aItem;
    MMITSwitch *_switchButton;
}

- (void).cxx_destruct;
@property(nonatomic) BOOL bSelected; // @synthesize bSelected=_bSelected;
@property(retain, nonatomic) MMITSwitch *switchButton; // @synthesize switchButton=_switchButton;
@property(retain, nonatomic) MMContactsPrivacyItem *aItem; // @synthesize aItem=_aItem;
@property(copy, nonatomic) CDUnknownBlockType didMouseUpBlock; // @synthesize didMouseUpBlock=_didMouseUpBlock;
@property(retain, nonatomic) NSTextField *descTextField; // @synthesize descTextField=_descTextField;
@property(retain, nonatomic) NSImageView *iconImageView; // @synthesize iconImageView=_iconImageView;
@property(retain, nonatomic) SVGImageView *checkView; // @synthesize checkView=_checkView;
- (void)onCheckButtonClick;
- (void)mouseUp:(id)arg1;
- (void)updateContent:(id)arg1;
- (void)initSubView;
- (id)initWithFrame:(struct CGRect)arg1;

@end

