//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class FavoritesItemDataField;

@interface MMFavoriteFileDownloadTask : NSObject
{
    BOOL _fromRetry;
    FavoritesItemDataField *_dataField;
}

- (void).cxx_destruct;
@property(nonatomic) BOOL fromRetry; // @synthesize fromRetry=_fromRetry;
@property(retain, nonatomic) FavoritesItemDataField *dataField; // @synthesize dataField=_dataField;

@end

