//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMService.h"

#import "MMService-Protocol.h"

@class MMCache, NSString;

@interface MMFavImageCacheService : MMService <MMService>
{
    MMCache *m_innerCache;
}

- (void).cxx_destruct;
- (void)asyncCreateImageForFavThumbRequest:(id)arg1 sourceImage:(id)arg2 completionBlock:(CDUnknownBlockType)arg3;
- (id)cacheKeyWithFavThumbRequest:(id)arg1;
- (void)removeCachedImageWithFavThumbRequest:(id)arg1;
- (BOOL)hasCachedImageForFavThumbRequest:(id)arg1;
- (id)retrieveImageForFavThumbRequest:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

