//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class MMSessionInfo, WCContactData;

@protocol MMFileSplitMasterViewDelegate <NSObject>

@optional
- (void)onSplitMasterViewHasNoResult;
- (void)onSplitMasterViewKeyRightArrowDown;
- (void)onSplitMasterViewKeyLeftArrowDown;
- (void)onSplitMasterViewGroupCellClick:(int)arg1;
- (void)onSplitMasterViewChatCellClick:(MMSessionInfo *)arg1;
- (void)onSplitMasterViewSenderCellClick:(WCContactData *)arg1;
@end

