//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSView.h>

@class NSMutableArray, NSTextField;

@interface MMOpenIMContactView : NSView
{
    CDUnknownBlockType _didDescButtonClick;
    NSTextField *_keyLabel;
    NSMutableArray *_valueView;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSMutableArray *valueView; // @synthesize valueView=_valueView;
@property(retain, nonatomic) NSTextField *keyLabel; // @synthesize keyLabel=_keyLabel;
@property(copy, nonatomic) CDUnknownBlockType didDescButtonClick; // @synthesize didDescButtonClick=_didDescButtonClick;
- (void)onDescButtonClick:(id)arg1;
- (id)createIconView:(id)arg1 withContact:(id)arg2;
- (id)createLabel:(id)arg1 withContact:(id)arg2;
- (void)updateUI:(id)arg1 withContact:(id)arg2 withWidth:(double)arg3;
- (void)updateViewAdujustFont:(double)arg1 height:(double)arg2;
- (void)initUI;
- (id)initWithFrame:(struct CGRect)arg1;

@end

