//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class FavoritesItem, FavoritesItemDataField, MMQLPreviewItem, MessageData, WeNoteParagraphInfo;

@interface MMPreloadVideoInfo : NSObject
{
    MMQLPreviewItem *_previewItem;
    MessageData *_messageData;
    FavoritesItemDataField *_parentDataField;
    MessageData *_parentMessage;
    FavoritesItem *_parentFavItem;
    FavoritesItem *_favItem;
    WeNoteParagraphInfo *_paraInfo;
}

- (void).cxx_destruct;
@property(retain, nonatomic) WeNoteParagraphInfo *paraInfo; // @synthesize paraInfo=_paraInfo;
@property(retain, nonatomic) FavoritesItem *favItem; // @synthesize favItem=_favItem;
@property(retain, nonatomic) FavoritesItem *parentFavItem; // @synthesize parentFavItem=_parentFavItem;
@property(retain, nonatomic) MessageData *parentMessage; // @synthesize parentMessage=_parentMessage;
@property(retain, nonatomic) FavoritesItemDataField *parentDataField; // @synthesize parentDataField=_parentDataField;
@property(retain, nonatomic) MessageData *messageData; // @synthesize messageData=_messageData;
@property(retain, nonatomic) MMQLPreviewItem *previewItem; // @synthesize previewItem=_previewItem;

@end

