//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMPreviewWindowController.h"

#import "SDWebImageManagerDelegate-Protocol.h"

@class MMQLPreviewItem, NSProgressIndicator, NSString;

@interface MMPreviewUrlImageWindowController : MMPreviewWindowController <SDWebImageManagerDelegate>
{
    MMQLPreviewItem *_m_currentPreviewImageItem;
    NSProgressIndicator *_progressIndicator;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSProgressIndicator *progressIndicator; // @synthesize progressIndicator=_progressIndicator;
@property(retain, nonatomic) MMQLPreviewItem *m_currentPreviewImageItem; // @synthesize m_currentPreviewImageItem=_m_currentPreviewImageItem;
- (void)webImageManager:(id)arg1 didFailWithError:(id)arg2;
- (void)webImageManager:(id)arg1 didFinishWithImage:(id)arg2;
- (void)setupCurrentPreviewItemWithImage:(id)arg1;
- (id)genPreviewItemWithUrl:(id)arg1;
- (void)stopLoading;
- (void)startLoading;
- (void)previewImage;
- (void)showUrlImage;
- (void)setupPageController;
- (void)openWith;
- (void)showPreviewItem:(id)arg1 targetFrame:(struct CGRect)arg2;
- (void)show;
- (id)getCurrentPreviewItem;
- (void)windowDidLoad;
- (id)initWithUrls:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

