//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSTableCellView.h>

@class MMView, NSString, NSTextField;

@interface MMSearchTableSectionHeaderView : NSTableCellView
{
    BOOL _isExpanded;
    NSString *_descriptionString;
    NSString *_title;
    unsigned long long _resultType;
    unsigned long long _maxPreviewRowCount;
    unsigned long long _itemCount;
    MMView *_backgroundView;
    MMView *_divider;
    NSTextField *_titleField;
    NSTextField *_descriptionField;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSTextField *descriptionField; // @synthesize descriptionField=_descriptionField;
@property(retain, nonatomic) NSTextField *titleField; // @synthesize titleField=_titleField;
@property(retain, nonatomic) MMView *divider; // @synthesize divider=_divider;
@property(retain, nonatomic) MMView *backgroundView; // @synthesize backgroundView=_backgroundView;
@property(nonatomic) BOOL isExpanded; // @synthesize isExpanded=_isExpanded;
@property(nonatomic) unsigned long long itemCount; // @synthesize itemCount=_itemCount;
@property(nonatomic) unsigned long long maxPreviewRowCount; // @synthesize maxPreviewRowCount=_maxPreviewRowCount;
@property(nonatomic) unsigned long long resultType; // @synthesize resultType=_resultType;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
- (void)updateDescriptionField;
@property(retain, nonatomic) NSString *descriptionString; // @synthesize descriptionString=_descriptionString;
- (void)awakeFromNib;
- (void)viewDidChangeEffectiveAppearance;
- (id)initWithCoder:(id)arg1;

@end

