//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class MMSearchContactTableCellView, WCContactData;
@protocol NSDraggingInfo;

@protocol MMSearchContactCellDelegate <NSObject>

@optional
- (BOOL)cellView:(MMSearchContactTableCellView *)arg1 isValidOperation:(id <NSDraggingInfo>)arg2 withContact:(WCContactData *)arg3;
- (void)cellView:(MMSearchContactTableCellView *)arg1 dragOperation:(id <NSDraggingInfo>)arg2 withContact:(WCContactData *)arg3;
@end

