//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface MMSessionPickerHelper : NSObject
{
}

+ (struct CGSize)stickerDisplaySizeWithImage:(id)arg1;
+ (id)formattedPreviewSimpleTextAttrStringWithContent:(id)arg1 handleEmoji:(BOOL)arg2;
+ (id)formattedPreviewTextAttrStringWithContent:(id)arg1;
+ (id)msgPreviewSummary:(id)arg1;
+ (BOOL)shouldUsePreview:(id)arg1;
+ (id)makeLabelAttrStringAndAlignment:(id)arg1 font:(id)arg2 color:(id)arg3;
+ (id)makeLabelAttrString:(id)arg1 font:(id)arg2 color:(id)arg3;

@end

