//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "PBCoding-Protocol.h"

@class NSDate, NSString;

@interface MMSnsAppMsgShareInfo : NSObject <PBCoding>
{
    BOOL hasItemShowType;
    BOOL isNativePage;
    BOOL isPaySubscribe;
    unsigned int itemShowType;
    unsigned int duration;
    unsigned int width;
    unsigned int height;
    unsigned int funcFlag;
    NSString *digest;
    NSString *cover;
    NSDate *pubTime;
    NSString *vid;
}

+ (void)initialize;
+ (void)PBArrayAdd_isPaySubscribe;
+ (void)PBArrayAdd_funcFlag;
+ (void)PBArrayAdd_vid;
+ (void)PBArrayAdd_height;
+ (void)PBArrayAdd_width;
+ (void)PBArrayAdd_duration;
+ (void)PBArrayAdd_pubTime;
+ (void)PBArrayAdd_cover;
+ (void)PBArrayAdd_digest;
+ (void)PBArrayAdd_isNativePage;
+ (void)PBArrayAdd_itemShowType;
+ (void)PBArrayAdd_hasItemShowType;
- (void).cxx_destruct;
@property(nonatomic) BOOL isPaySubscribe; // @synthesize isPaySubscribe;
@property(nonatomic) unsigned int funcFlag; // @synthesize funcFlag;
@property(copy, nonatomic) NSString *vid; // @synthesize vid;
@property(nonatomic) unsigned int height; // @synthesize height;
@property(nonatomic) unsigned int width; // @synthesize width;
@property(nonatomic) unsigned int duration; // @synthesize duration;
@property(retain, nonatomic) NSDate *pubTime; // @synthesize pubTime;
@property(copy, nonatomic) NSString *cover; // @synthesize cover;
@property(copy, nonatomic) NSString *digest; // @synthesize digest;
@property(nonatomic) BOOL isNativePage; // @synthesize isNativePage;
@property(nonatomic) unsigned int itemShowType; // @synthesize itemShowType;
@property(nonatomic) BOOL hasItemShowType; // @synthesize hasItemShowType;
- (const map_f8690629 *)getValueTagIndexMap;
- (id)getValueTypeTable;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

