//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSWindowController.h>

#import "AVCaptureDeviceChangedExt-Protocol.h"
#import "CAAnimationDelegate-Protocol.h"
#import "IVOIPExt-Protocol.h"
#import "IVOIPModeSwitchExt-Protocol.h"
#import "IVOIPVideoDeviceDelegate-Protocol.h"
#import "NSPopoverDelegate-Protocol.h"
#import "NSWindowDelegate-Protocol.h"

@class AVAudioPlayer, MMTimer, MMVoIPDeviceController, MMVoipBaseWindow, MessageData, NSPopover, NSString, NSToolbar, WCContactData;
@protocol MMVoipBaseWindowControllerDelegate;

@interface MMVoipBaseWindowController : NSWindowController <NSWindowDelegate, CAAnimationDelegate, NSPopoverDelegate, AVCaptureDeviceChangedExt, IVOIPExt, IVOIPModeSwitchExt, IVOIPVideoDeviceDelegate>
{
    BOOL _hasHanguped;
    BOOL _isSelfSwitchToVoice;
    BOOL _hasStopBellSound;
    BOOL _forceToVoice;
    BOOL _isConnectOK;
    BOOL _isMute;
    BOOL _isStick;
    BOOL _isEndCall;
    BOOL _isFromUserNotification;
    BOOL _isMultiTalk;
    BOOL _isCaller;
    BOOL _isOpenWithCamera;
    BOOL _isNeedRestartAudioDevice;
    int _status;
    int _viewInitMode;
    unsigned int _mStartTalkingTime;
    int _orienOffset;
    int _currentMode;
    id <MMVoipBaseWindowControllerDelegate> _delegate;
    NSPopover *_popover;
    MMVoIPDeviceController *_deviceViewController;
    MessageData *_message;
    WCContactData *_contact;
    MMTimer *_actingTimer;
    MMTimer *_netStatusUpdateTimer;
    AVAudioPlayer *_player;
    double _forceToRotateDegrees;
    double _lastDegrees;
    NSToolbar *_toolBar;
}

- (void).cxx_destruct;
@property(nonatomic) BOOL isNeedRestartAudioDevice; // @synthesize isNeedRestartAudioDevice=_isNeedRestartAudioDevice;
@property(nonatomic) BOOL isOpenWithCamera; // @synthesize isOpenWithCamera=_isOpenWithCamera;
@property(retain, nonatomic) NSToolbar *toolBar; // @synthesize toolBar=_toolBar;
@property(nonatomic) BOOL isCaller; // @synthesize isCaller=_isCaller;
@property(nonatomic) int currentMode; // @synthesize currentMode=_currentMode;
@property(nonatomic) double lastDegrees; // @synthesize lastDegrees=_lastDegrees;
@property(nonatomic) int orienOffset; // @synthesize orienOffset=_orienOffset;
@property(nonatomic) double forceToRotateDegrees; // @synthesize forceToRotateDegrees=_forceToRotateDegrees;
@property(nonatomic) BOOL isMultiTalk; // @synthesize isMultiTalk=_isMultiTalk;
@property(nonatomic) BOOL isFromUserNotification; // @synthesize isFromUserNotification=_isFromUserNotification;
@property(nonatomic) unsigned int mStartTalkingTime; // @synthesize mStartTalkingTime=_mStartTalkingTime;
@property(nonatomic) BOOL isEndCall; // @synthesize isEndCall=_isEndCall;
@property(nonatomic) BOOL isStick; // @synthesize isStick=_isStick;
@property(nonatomic) BOOL isMute; // @synthesize isMute=_isMute;
@property(nonatomic) BOOL isConnectOK; // @synthesize isConnectOK=_isConnectOK;
@property(nonatomic) BOOL forceToVoice; // @synthesize forceToVoice=_forceToVoice;
@property(nonatomic) int viewInitMode; // @synthesize viewInitMode=_viewInitMode;
@property(nonatomic) int status; // @synthesize status=_status;
@property(nonatomic) BOOL hasStopBellSound; // @synthesize hasStopBellSound=_hasStopBellSound;
@property(nonatomic) BOOL isSelfSwitchToVoice; // @synthesize isSelfSwitchToVoice=_isSelfSwitchToVoice;
@property(nonatomic) BOOL hasHanguped; // @synthesize hasHanguped=_hasHanguped;
@property(retain, nonatomic) AVAudioPlayer *player; // @synthesize player=_player;
@property(retain, nonatomic) MMTimer *netStatusUpdateTimer; // @synthesize netStatusUpdateTimer=_netStatusUpdateTimer;
@property(retain, nonatomic) MMTimer *actingTimer; // @synthesize actingTimer=_actingTimer;
@property(retain, nonatomic) WCContactData *contact; // @synthesize contact=_contact;
@property(retain, nonatomic) MessageData *message; // @synthesize message=_message;
@property(retain, nonatomic) MMVoIPDeviceController *deviceViewController; // @synthesize deviceViewController=_deviceViewController;
@property(retain, nonatomic) NSPopover *popover; // @synthesize popover=_popover;
@property(nonatomic) __weak id <MMVoipBaseWindowControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)showPopoverInView:(id)arg1;
- (BOOL)isPopoverShown;
- (void)hidePopover;
- (void)popoverWillClose:(id)arg1;
- (void)popoverWillShow:(id)arg1;
- (void)popoverDidClose:(id)arg1;
- (void)onSwitchVideoButtonClick:(id)arg1;
- (void)onSwitchButtonClick:(id)arg1;
- (void)closeAudioInputAuto:(id)arg1;
- (void)closeCameraAuto:(id)arg1;
- (void)closePopover;
- (void)deviceCountChanged;
- (void)switchAudioInput;
- (void)switchCamera;
- (void)checkDeviceAuthorized;
- (void)onCurrentCaptureDeviceChanged:(id)arg1 withType:(int)arg2;
- (void)onCaptureDeviceCountChanged;
- (void)onCaptureDeviceChanged:(id)arg1 withType:(int)arg2;
- (void)formVOIPUserNotification;
- (void)formVOIPMessageWhenCallFromMyself:(BOOL)arg1;
- (void)renderOnOppsiteRenderLayer:(id)arg1 Degree:(float)arg2;
- (void)renderOnPreviewRenderLayerWith:(id)arg1;
- (void)rotateLayerToFillWindow;
- (int)getVideoOrientationWithDegrees:(double)arg1;
- (void)onOpenCameraButtonClick;
- (void)setAudioDeviceMute;
- (void)setWindowStick:(id)arg1;
- (void)startCamera;
- (void)autoUpdateMainStatusStringAndDotViewImage;
- (void)acceptVoipInvite;
- (void)switchToVoiceChat;
- (void)endCall;
- (void)cancelCall;
- (void)cancelMakeControlViewSubViewVisiable;
- (void)delayMakeControlViewSubViewsHidden;
- (void)makeControlViewSubViewsHidden:(BOOL)arg1;
- (void)mouseMoved:(id)arg1;
- (BOOL)isInitVideoMode;
- (BOOL)isVideoMode;
- (void)layoutButtonContainerAnimate:(BOOL)arg1;
- (void)layoutVoiceModeAnimateDotViewWithMode:(int)arg1;
- (void)layoutCallTimeLabelWithMode:(int)arg1;
- (void)layoutNameLabelWithContact:(id)arg1 andMode:(int)arg2;
- (void)layoutHDAvatarWithContact:(id)arg1 andMode:(int)arg2;
- (void)LayoutNameLabelAndCallTimeLabelWithAnimateAvatar:(id)arg1 andMode:(int)arg2;
- (void)layoutAvatarWithContact:(id)arg1 andMode:(int)arg2;
- (void)layoutSwitchVideoButton;
- (void)layoutSwitchAudioDeviceIndicator;
- (void)layoutActionBtnWithMode:(int)arg1;
- (void)onWCAudioSessionChangedFinished;
- (void)onWCAudioSessionDeviceIDChanged;
- (void)updateNetStatus;
- (void)clearNetStatusUpdateTimer;
- (void)startNetStatusTimerToUpdateNetSatus;
- (void)clearActingTimer;
- (void)startActingTimerToUpdateStatusLabelAndDotView;
- (void)showCurrentTips:(id)arg1;
- (void)hidePreviousTips;
- (void)layoutTipsLabelWithMode:(int)arg1;
- (void)layoutRelatedControlsWithContact:(id)arg1 andSetCurrentMode:(int)arg2;
- (void)layoutToolbarContainer;
- (void)makeHangUpBtnUnavailable;
- (void)makeRotateBtnUnavailable:(BOOL)arg1;
- (void)bringSublayerToFront:(id)arg1;
- (void)swapPreviewRenderLayerAndOppsiteRenderLayer;
- (void)changeMovableLayerFrameWhenRotated;
- (void)changeRenderLayerDisplayFromW16H9ToW9H16OnFullScreen;
- (void)changeRenderLayerDisplayFromW9H16ToW16H9OnFullScreen;
- (void)changeRenderLayerDisplayNotOnFullScreen;
- (void)playEndingSound;
- (void)resumePlaySound;
- (void)pausePlaySound;
- (void)stopPlaySound;
- (void)playSound:(id)arg1 OfType:(id)arg2 numberOfLoops:(long long)arg3;
- (void)fadeOutWindowAnimate;
- (void)adjustFrameOriginDependOnWechatMainWindow;
- (void)setWindowAndContentFrame:(struct CGRect)arg1;
- (void)orderFrontWindow;
- (void)hideWindow;
- (void)didFinishClosing:(BOOL)arg1;
- (void)willStartClosing:(BOOL)arg1;
- (BOOL)windowShouldClose:(id)arg1;
- (void)closeWindowAnimated:(BOOL)arg1;
- (void)showWindowAnimated:(BOOL)arg1;
- (void)windowWillEnterFullScreenAction:(id)arg1;
- (void)windowDidExitFullScreenAction:(id)arg1;
- (void)loadContent;
- (id)title;
- (struct CGSize)minimumSize;
- (void)adjustTitleBarButtons:(BOOL)arg1;
- (void)windowDidLoad;
- (void)dealloc;
- (id)initWithWindowNibName:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(retain) MMVoipBaseWindow *window; // @dynamic window;

@end

