//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMWindowController.h"

#import "MMWebSearchWindowDelegate-Protocol.h"
#import "NSWindowDelegate-Protocol.h"

@class MMWebSearchViewController, MMWebSearchWindow, NSString;

@interface MMWebSearchWindowController : MMWindowController <NSWindowDelegate, MMWebSearchWindowDelegate>
{
    MMWebSearchViewController *_webSearchVC;
}

- (void).cxx_destruct;
@property(retain, nonatomic) MMWebSearchViewController *webSearchVC; // @synthesize webSearchVC=_webSearchVC;
- (void)performWebSearchAction;
- (BOOL)windowShouldClose:(id)arg1;
- (void)orderFrontWindow;
- (void)closeWindowAnimated:(BOOL)arg1;
- (void)showWindowAnimated:(BOOL)arg1 keyWord:(id)arg2;
- (void)windowDidLoad;
- (id)initWithWindowNibName:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(retain, nonatomic) MMWebSearchWindow *window; // @dynamic window;

@end

