//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <WebKit/WKWebView.h>

@interface MMWKWebView : WKWebView
{
    unsigned long long _preloadStatus;
}

@property(nonatomic) unsigned long long preloadStatus; // @synthesize preloadStatus=_preloadStatus;
- (void)evaluateJavaScriptFromString:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;
- (void)willOpenMenu:(id)arg1 withEvent:(id)arg2;
- (void)customLoadRequest:(id)arg1;

@end

