//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface RACSubscriptingAssignmentTrampoline : NSObject
{
    id _target;
    id _nilValue;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) id nilValue; // @synthesize nilValue=_nilValue;
@property(readonly, nonatomic) id target; // @synthesize target=_target;
- (void)setObject:(id)arg1 forKeyedSubscript:(id)arg2;
- (id)initWithTarget:(id)arg1 nilValue:(id)arg2;

@end

