//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "PBGeneratedMessage.h"

@class BaseResponse, NSMutableArray;

@interface SnsObjectOpResponse : PBGeneratedMessage
{
    unsigned int hasBaseResponse:1;
    unsigned int hasOpCount:1;
    int opRetListMemoizedSerializedSize;
    unsigned int hasUpdateYearMonthInfo:1;
    unsigned int hasYearMonthInfoCount:1;
    unsigned int opCount;
    unsigned int updateYearMonthInfo;
    unsigned int yearMonthInfoCount;
    BaseResponse *baseResponse;
    NSMutableArray *mutableOpRetListList;
    NSMutableArray *mutableYearMonthInfoListList;
}

+ (id)parseFromData:(id)arg1;
- (void).cxx_destruct;
@property(retain, nonatomic) NSMutableArray *mutableYearMonthInfoListList; // @synthesize mutableYearMonthInfoListList;
@property(nonatomic, setter=SetYearMonthInfoCount:) unsigned int yearMonthInfoCount; // @synthesize yearMonthInfoCount;
@property(readonly, nonatomic) BOOL hasYearMonthInfoCount; // @synthesize hasYearMonthInfoCount;
@property(nonatomic, setter=SetUpdateYearMonthInfo:) unsigned int updateYearMonthInfo; // @synthesize updateYearMonthInfo;
@property(readonly, nonatomic) BOOL hasUpdateYearMonthInfo; // @synthesize hasUpdateYearMonthInfo;
@property(retain, nonatomic) NSMutableArray *mutableOpRetListList; // @synthesize mutableOpRetListList;
@property(nonatomic, setter=SetOpCount:) unsigned int opCount; // @synthesize opCount;
@property(readonly, nonatomic) BOOL hasOpCount; // @synthesize hasOpCount;
@property(retain, nonatomic, setter=SetBaseResponse:) BaseResponse *baseResponse; // @synthesize baseResponse;
@property(readonly, nonatomic) BOOL hasBaseResponse; // @synthesize hasBaseResponse;
- (void)addYearMonthInfoList:(id)arg1;
- (void)addYearMonthInfoListFromArray:(id)arg1;
- (void)addOpRetListFromArray:(id)arg1;
- (void)addOpRetList:(int)arg1;
- (id)mergeFromCodedInputStream:(id)arg1;
- (int)serializedSize;
- (void)writeToCodedOutputStream:(id)arg1;
- (BOOL)isInitialized;
@property(retain, nonatomic) NSMutableArray *yearMonthInfoList; // @dynamic yearMonthInfoList;
- (id)yearMonthInfoListList;
@property(retain, nonatomic) NSMutableArray *opRetList; // @dynamic opRetList;
- (id)opRetListList;
- (id)init;

@end

