//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SolitaireReport.h"

@class NSString;

@interface SolitaireJoinReport : SolitaireReport
{
    unsigned int _addCount;
    unsigned int _removeCount;
    unsigned long long _editScene;
    NSString *_nsPunctuation;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSString *nsPunctuation; // @synthesize nsPunctuation=_nsPunctuation;
@property(nonatomic) unsigned long long editScene; // @synthesize editScene=_editScene;
@property(nonatomic) unsigned int removeCount; // @synthesize removeCount=_removeCount;
@property(nonatomic) unsigned int addCount; // @synthesize addCount=_addCount;
- (void)report;

@end

