//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@protocol OS_dispatch_queue, OS_dispatch_source;

@interface TXCAudioVolumeEvaluator : NSObject
{
    NSObject<OS_dispatch_queue> *_queue;
    CDUnknownBlockType _evaluationCallback;
    CDUnknownBlockType _micTestCallback;
    CDUnknownBlockType _speakerTestCallback;
    NSObject<OS_dispatch_source> *_volumeTimer;
    long long _enableFlag;
    long long _interval;
}

- (void).cxx_destruct;
@property(nonatomic) long long interval; // @synthesize interval=_interval;
@property(nonatomic) long long enableFlag; // @synthesize enableFlag=_enableFlag;
@property(retain, nonatomic) NSObject<OS_dispatch_source> *volumeTimer; // @synthesize volumeTimer=_volumeTimer;
@property(copy, nonatomic) CDUnknownBlockType speakerTestCallback; // @synthesize speakerTestCallback=_speakerTestCallback;
@property(copy, nonatomic) CDUnknownBlockType micTestCallback; // @synthesize micTestCallback=_micTestCallback;
@property(copy, nonatomic) CDUnknownBlockType evaluationCallback; // @synthesize evaluationCallback=_evaluationCallback;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
- (void)onVolumeTimer;
- (void)stopVolumeTimerIfNeeded;
- (void)startVolumeTimerIfNeeded;
- (void)startVolumeTimerIfNeeded:(long long)arg1;
- (void)stopSpeakerTest;
- (void)startSpeakerTestOnTimer:(CDUnknownBlockType)arg1;
- (void)stopMicTest;
- (void)startMicTestOnTimer:(CDUnknownBlockType)arg1;
- (void)stopVolumeEvaluation;
- (void)startVolumeEvaluation:(unsigned long long)arg1 onTimer:(CDUnknownBlockType)arg2;
- (void)dealloc;
@property(readonly, nonatomic) struct AudioEngine *audioEngine;
- (id)initWithQueue:(id)arg1;

@end

