//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TXCModule.h"

@class NSArray, NSMutableDictionary, NSString;

@interface TXCDataReport : TXCModule
{
    NSMutableDictionary *_stats;
    long long _lastReport;
    long long _statusReportInterval;
    BOOL _hasReportedBegin;
    NSArray *_needCheckBeginKeys;
    unsigned int _reportPlayStatusEnterCount;
    long long _lastBlockCount;
    long long _lastBlockCount500MS;
    long long _lastLightBlockCount;
    long long _lastAudioBlockCount60MS;
    unsigned long long _lastRecvCount;
    long long _startPlayTs;
    unsigned long long _startTime;
    int _maxVideoCache;
    int _sumVideoCache;
    int _numVideoCache;
    unsigned long long _realTimePlayStartTime;
    unsigned long long _lastRecvTime;
    unsigned long long _lastAudioLoadCnt;
    BOOL _realTimeMode;
    BOOL _isp2p;
    NSString *_url;
    NSString *_realUrl;
    NSString *_rtmpproxyUserId;
}

+ (BOOL)isTencentHost:(id)arg1;
- (void).cxx_destruct;
@property(retain, nonatomic) NSString *rtmpproxyUserId; // @synthesize rtmpproxyUserId=_rtmpproxyUserId;
@property(nonatomic) BOOL isp2p; // @synthesize isp2p=_isp2p;
@property(copy, nonatomic) NSString *realUrl; // @synthesize realUrl=_realUrl;
@property(copy, nonatomic) NSString *url; // @synthesize url=_url;
@property(nonatomic) BOOL realTimeMode; // @synthesize realTimeMode=_realTimeMode;
- (id)logStrWithParams:(id)arg1;
- (CDUnknownBlockType)newBlockWith:(id)arg1 commandID:(int)arg2 needCache:(BOOL)arg3;
- (CDUnknownBlockType)newBlockWith:(id)arg1 commandID:(int)arg2;
- (void)avgWithKeys:(int)arg1 countKey:(int)arg2 curKey:(int)arg3;
- (void)updateAVGValues;
- (void)setupStats;
- (void)execGBNDNSParseTask;
- (id)getParamsFromStreamUrl:(id)arg1 streamUrl:(id)arg2;
- (id)getStringFromNumber:(id)arg1;
- (id)getStringFromValue:(long long)arg1;
- (id)getStatUserID;
- (id)getStatSessionID;
- (id)getRecvFPS;
- (void)reportCommonKeys:(CDUnknownBlockType)arg1 isEnd:(BOOL)arg2;
- (void)reportRoomInfo:(CDUnknownBlockType)arg1;
- (void)reportRealTimePlayStatisticInfo;
- (void)reportRealTimePlayFail;
- (void)reportPlayStatusInternal;
- (void)reportPlayBeginEvt;
- (void)reportPlayFailed;
- (void)reportPlayEndEvt;
- (void)reportPlayStatus;
- (void)stopPlay;
- (void)reportPushStatusInternal;
- (void)reportPushBeginEvt;
- (void)reportPushFailed;
- (void)reportPushEndEvt;
- (void)reportPushStatus;
- (void)stopPush;
- (void)getCNAME:(id)arg1;
- (long long)checkTencentStream;
- (void)resetStorage;
- (void)start;
- (void)initParam;
- (id)init;

@end

