//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TXCOutput.h"

@class NSObject;
@protocol OS_dispatch_semaphore;

@interface TXCPicture : TXCOutput
{
    struct CGSize pixelSizeOfImage;
    BOOL hasProcessedImage;
    NSObject<OS_dispatch_semaphore> *imageUpdateSemaphore;
}

- (void).cxx_destruct;
- (void)addTarget:(id)arg1 atTextureLocation:(long long)arg2;
- (struct CGSize)outputImageSize;
- (void)processImageUpToFilter:(id)arg1 withCompletionHandler:(CDUnknownBlockType)arg2;
- (BOOL)processImageWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)processImage;
- (void)removeAllTargets;
- (id)initWithCGImage:(struct CGImage *)arg1 smoothlyScaleOutput:(BOOL)arg2;
- (id)initWithImage:(id)arg1 smoothlyScaleOutput:(BOOL)arg2;
- (id)initWithCGImage:(struct CGImage *)arg1;
- (id)initWithImage:(id)arg1;
- (id)initWithData:(id)arg1;
- (id)initWithURL:(id)arg1;

@end

