//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "PBGeneratedMessage.h"

@class BaseRequest, NSMutableArray;

@interface UpdateWxaStarRecordRequest : PBGeneratedMessage
{
    unsigned int hasBaseRequest:1;
    unsigned int hasReason:1;
    unsigned int reason;
    BaseRequest *baseRequest;
    NSMutableArray *mutableOperListList;
}

+ (id)parseFromData:(id)arg1;
- (void).cxx_destruct;
@property(retain, nonatomic) NSMutableArray *mutableOperListList; // @synthesize mutableOperListList;
@property(nonatomic, setter=SetReason:) unsigned int reason; // @synthesize reason;
@property(readonly, nonatomic) BOOL hasReason; // @synthesize hasReason;
@property(retain, nonatomic, setter=SetBaseRequest:) BaseRequest *baseRequest; // @synthesize baseRequest;
@property(readonly, nonatomic) BOOL hasBaseRequest; // @synthesize hasBaseRequest;
- (void)addOperList:(id)arg1;
- (void)addOperListFromArray:(id)arg1;
- (id)mergeFromCodedInputStream:(id)arg1;
- (int)serializedSize;
- (void)writeToCodedOutputStream:(id)arg1;
- (BOOL)isInitialized;
@property(retain, nonatomic) NSMutableArray *operList; // @dynamic operList;
- (id)operListList;
- (id)init;

@end

