//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface V2TRTCUserInfo : NSObject
{
    BOOL _isAudioAvailable;
    BOOL _isVideoAvailable;
    BOOL _hasRecvFirstVideoFrame;
    BOOL _hasRecvFirstAudioFrame;
    BOOL _isAuxVideoAvailable;
    BOOL _hasRecvFirstAuxVideoFrame;
    NSString *_userId;
}

- (void).cxx_destruct;
@property(nonatomic) BOOL hasRecvFirstAuxVideoFrame; // @synthesize hasRecvFirstAuxVideoFrame=_hasRecvFirstAuxVideoFrame;
@property(nonatomic) BOOL isAuxVideoAvailable; // @synthesize isAuxVideoAvailable=_isAuxVideoAvailable;
@property(nonatomic) BOOL hasRecvFirstAudioFrame; // @synthesize hasRecvFirstAudioFrame=_hasRecvFirstAudioFrame;
@property(nonatomic) BOOL hasRecvFirstVideoFrame; // @synthesize hasRecvFirstVideoFrame=_hasRecvFirstVideoFrame;
@property(nonatomic) BOOL isVideoAvailable; // @synthesize isVideoAvailable=_isVideoAvailable;
@property(nonatomic) BOOL isAudioAvailable; // @synthesize isAudioAvailable=_isAudioAvailable;
@property(retain, nonatomic) NSString *userId; // @synthesize userId=_userId;
- (id)description;

@end

