//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "V2TXLivePlayerObserver-Protocol.h"

@class NSData;

@protocol V2TXLivePlayerObserverEx <V2TXLivePlayerObserver>
- (void)onNetworkQuality:(long long)arg1;
- (void)onRecvSEIMessage:(NSData *)arg1;
- (void)onPlayNetStatus:(id)arg1;
- (void)onPlayEvent:(long long)arg1 param:(id)arg2;
@end

