//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "PBGeneratedMessage.h"

@interface VoiceRemindInfo : PBGeneratedMessage
{
    unsigned int hasRemindId:1;
    unsigned int remindId;
}

+ (id)parseFromData:(id)arg1;
@property(nonatomic, setter=SetRemindId:) unsigned int remindId; // @synthesize remindId;
@property(readonly, nonatomic) BOOL hasRemindId; // @synthesize hasRemindId;
- (id)mergeFromCodedInputStream:(id)arg1;
- (int)serializedSize;
- (void)writeToCodedOutputStream:(id)arg1;
- (BOOL)isInitialized;
- (id)init;

@end

