//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "PBGeneratedMessage.h"

@class NSData, NSMutableArray, NSString;

@interface VoIPMtInviteMsg : PBGeneratedMessage
{
    unsigned int hasWxGroupid:1;
    unsigned int hasRoomid:1;
    unsigned int hasSdkGroupid:1;
    unsigned int hasFromOpenid:1;
    unsigned int hasToOpenid:1;
    unsigned int hasConfInviteItem:1;
    NSString *wxGroupid;
    unsigned long long roomid;
    NSString *sdkGroupid;
    NSString *fromOpenid;
    NSString *toOpenid;
    NSData *confInviteItem;
    NSMutableArray *mutableDisplayUserListList;
}

+ (id)parseFromData:(id)arg1;
- (void).cxx_destruct;
@property(retain, nonatomic) NSMutableArray *mutableDisplayUserListList; // @synthesize mutableDisplayUserListList;
@property(retain, nonatomic, setter=SetConfInviteItem:) NSData *confInviteItem; // @synthesize confInviteItem;
@property(readonly, nonatomic) BOOL hasConfInviteItem; // @synthesize hasConfInviteItem;
@property(retain, nonatomic, setter=SetToOpenid:) NSString *toOpenid; // @synthesize toOpenid;
@property(readonly, nonatomic) BOOL hasToOpenid; // @synthesize hasToOpenid;
@property(retain, nonatomic, setter=SetFromOpenid:) NSString *fromOpenid; // @synthesize fromOpenid;
@property(readonly, nonatomic) BOOL hasFromOpenid; // @synthesize hasFromOpenid;
@property(retain, nonatomic, setter=SetSdkGroupid:) NSString *sdkGroupid; // @synthesize sdkGroupid;
@property(readonly, nonatomic) BOOL hasSdkGroupid; // @synthesize hasSdkGroupid;
@property(nonatomic, setter=SetRoomid:) unsigned long long roomid; // @synthesize roomid;
@property(readonly, nonatomic) BOOL hasRoomid; // @synthesize hasRoomid;
@property(retain, nonatomic, setter=SetWxGroupid:) NSString *wxGroupid; // @synthesize wxGroupid;
@property(readonly, nonatomic) BOOL hasWxGroupid; // @synthesize hasWxGroupid;
- (void)addDisplayUserList:(id)arg1;
- (void)addDisplayUserListFromArray:(id)arg1;
- (id)mergeFromCodedInputStream:(id)arg1;
- (int)serializedSize;
- (void)writeToCodedOutputStream:(id)arg1;
- (BOOL)isInitialized;
@property(retain, nonatomic) NSMutableArray *displayUserList; // @dynamic displayUserList;
- (id)displayUserListList;
- (id)init;

@end

