//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "PBGeneratedMessage.h"

@class NSData, NSString;

@interface WARemoteDebug_DataFormat : PBGeneratedMessage
{
    unsigned int hasCmd:1;
    unsigned int hasUuid:1;
    unsigned int hasData:1;
    NSData *data_;
    unsigned int cmd;
    NSString *uuid;
}

+ (id)parseFromData:(id)arg1;
- (void).cxx_destruct;
@property(retain, nonatomic, setter=SetData:) NSData *data; // @synthesize data=data_;
@property(readonly, nonatomic) BOOL hasData; // @synthesize hasData;
@property(retain, nonatomic, setter=SetUuid:) NSString *uuid; // @synthesize uuid;
@property(readonly, nonatomic) BOOL hasUuid; // @synthesize hasUuid;
@property(nonatomic, setter=SetCmd:) unsigned int cmd; // @synthesize cmd;
@property(readonly, nonatomic) BOOL hasCmd; // @synthesize hasCmd;
- (id)mergeFromCodedInputStream:(id)arg1;
- (int)serializedSize;
- (void)writeToCodedOutputStream:(id)arg1;
- (BOOL)isInitialized;
- (id)init;

@end

