//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "IWCDumpReporterMgrExt-Protocol.h"

@class NSString;

@interface WCDumpReporter : NSObject <IWCDumpReporterMgrExt>
{
    CDUnknownBlockType _didUploadProgressBlock;
    CDUnknownBlockType _didUploadFinishedBlock;
    CDUnknownBlockType _didUploadFailedBlock;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
@property(copy, nonatomic) CDUnknownBlockType didUploadFailedBlock; // @synthesize didUploadFailedBlock=_didUploadFailedBlock;
@property(copy, nonatomic) CDUnknownBlockType didUploadFinishedBlock; // @synthesize didUploadFinishedBlock=_didUploadFinishedBlock;
@property(copy, nonatomic) CDUnknownBlockType didUploadProgressBlock; // @synthesize didUploadProgressBlock=_didUploadProgressBlock;
- (void)onDumpReporterUploadProgress:(double)arg1;
- (void)onDumpReporterUploadResult:(BOOL)arg1;
- (void)onLagReportFinished:(BOOL)arg1;
- (void)uploadLagWithDate:(id)arg1;
- (void)uploadLag;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

