//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "PBGeneratedMessage.h"

@class BaseResponse, NSData, NSMutableArray, NSString;

@interface WxaAttrSyncResponse : PBGeneratedMessage
{
    unsigned int hasBaseResponse:1;
    unsigned int hasLastAttrVersion:1;
    unsigned int hasWxaUserName:1;
    BaseResponse *baseResponse;
    NSData *lastAttrVersion;
    NSMutableArray *mutableUpdateInfoListList;
    NSString *wxaUserName;
}

+ (id)parseFromData:(id)arg1;
- (void).cxx_destruct;
@property(retain, nonatomic, setter=SetWxaUserName:) NSString *wxaUserName; // @synthesize wxaUserName;
@property(readonly, nonatomic) BOOL hasWxaUserName; // @synthesize hasWxaUserName;
@property(retain, nonatomic) NSMutableArray *mutableUpdateInfoListList; // @synthesize mutableUpdateInfoListList;
@property(retain, nonatomic, setter=SetLastAttrVersion:) NSData *lastAttrVersion; // @synthesize lastAttrVersion;
@property(readonly, nonatomic) BOOL hasLastAttrVersion; // @synthesize hasLastAttrVersion;
@property(retain, nonatomic, setter=SetBaseResponse:) BaseResponse *baseResponse; // @synthesize baseResponse;
@property(readonly, nonatomic) BOOL hasBaseResponse; // @synthesize hasBaseResponse;
- (void)addUpdateInfoList:(id)arg1;
- (void)addUpdateInfoListFromArray:(id)arg1;
- (id)mergeFromCodedInputStream:(id)arg1;
- (int)serializedSize;
- (void)writeToCodedOutputStream:(id)arg1;
- (BOOL)isInitialized;
@property(retain, nonatomic) NSMutableArray *updateInfoList; // @dynamic updateInfoList;
- (id)updateInfoListList;
- (id)init;

@end

