//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "PBGeneratedMessage.h"

@class WxaSyncBlockCgiRequestCmd, WxaSyncGetCodeCmd, WxaSyncGetContactCmd, WxaSyncIssueContactCmd, WxaSyncIssueDecryptKeyCmd, WxaSyncIssueLaunchCmd, WxaSyncUpdateVersionCmd;

@interface WxaSyncCmds : PBGeneratedMessage
{
    unsigned int hasGetContact:1;
    unsigned int hasGetCode:1;
    unsigned int hasIssueContact:1;
    unsigned int hasIssueLaunch:1;
    unsigned int hasIssueDecryptKey:1;
    unsigned int hasUpdateVersion:1;
    unsigned int hasBlockCgiRequest:1;
    WxaSyncGetContactCmd *getContact;
    WxaSyncGetCodeCmd *getCode;
    WxaSyncIssueContactCmd *issueContact;
    WxaSyncIssueLaunchCmd *issueLaunch;
    WxaSyncIssueDecryptKeyCmd *issueDecryptKey;
    WxaSyncUpdateVersionCmd *updateVersion;
    WxaSyncBlockCgiRequestCmd *blockCgiRequest;
}

+ (id)parseFromData:(id)arg1;
- (void).cxx_destruct;
@property(retain, nonatomic, setter=SetBlockCgiRequest:) WxaSyncBlockCgiRequestCmd *blockCgiRequest; // @synthesize blockCgiRequest;
@property(readonly, nonatomic) BOOL hasBlockCgiRequest; // @synthesize hasBlockCgiRequest;
@property(retain, nonatomic, setter=SetUpdateVersion:) WxaSyncUpdateVersionCmd *updateVersion; // @synthesize updateVersion;
@property(readonly, nonatomic) BOOL hasUpdateVersion; // @synthesize hasUpdateVersion;
@property(retain, nonatomic, setter=SetIssueDecryptKey:) WxaSyncIssueDecryptKeyCmd *issueDecryptKey; // @synthesize issueDecryptKey;
@property(readonly, nonatomic) BOOL hasIssueDecryptKey; // @synthesize hasIssueDecryptKey;
@property(retain, nonatomic, setter=SetIssueLaunch:) WxaSyncIssueLaunchCmd *issueLaunch; // @synthesize issueLaunch;
@property(readonly, nonatomic) BOOL hasIssueLaunch; // @synthesize hasIssueLaunch;
@property(retain, nonatomic, setter=SetIssueContact:) WxaSyncIssueContactCmd *issueContact; // @synthesize issueContact;
@property(readonly, nonatomic) BOOL hasIssueContact; // @synthesize hasIssueContact;
@property(retain, nonatomic, setter=SetGetCode:) WxaSyncGetCodeCmd *getCode; // @synthesize getCode;
@property(readonly, nonatomic) BOOL hasGetCode; // @synthesize hasGetCode;
@property(retain, nonatomic, setter=SetGetContact:) WxaSyncGetContactCmd *getContact; // @synthesize getContact;
@property(readonly, nonatomic) BOOL hasGetContact; // @synthesize hasGetContact;
- (id)mergeFromCodedInputStream:(id)arg1;
- (int)serializedSize;
- (void)writeToCodedOutputStream:(id)arg1;
- (BOOL)isInitialized;
- (id)init;

@end

