//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "MMIPCServerProtocol-Protocol.h"

@class NSString, NSXPCInterface;

@interface MMIPCServer : NSObject <MMIPCServerProtocol>
{
    NSXPCInterface *_remoteObjectInterface;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSXPCInterface *remoteObjectInterface; // @synthesize remoteObjectInterface=_remoteObjectInterface;
- (void)registerToServer:(id)arg1 pid:(id)arg2 identifier:(id)arg3 withReply:(CDUnknownBlockType)arg4;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

