//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSView.h>

@class CAShapeLayer, NSFont, NSTextField;

@interface MMAppFeedLiveView : NSView
{
    double _iconSize;
    NSFont *_font;
    NSTextField *_textFiled;
    CAShapeLayer *_shapeLayer;
    struct CGSize _viewSize;
}

- (void).cxx_destruct;
@property(nonatomic) struct CGSize viewSize; // @synthesize viewSize=_viewSize;
@property(retain, nonatomic) CAShapeLayer *shapeLayer; // @synthesize shapeLayer=_shapeLayer;
@property(retain, nonatomic) NSTextField *textFiled; // @synthesize textFiled=_textFiled;
@property(retain, nonatomic) NSFont *font; // @synthesize font=_font;
@property(nonatomic) double iconSize; // @synthesize iconSize=_iconSize;
- (struct CGPath *)badgeViewPath:(struct CGRect)arg1;
- (struct CGSize)intrinsicContentSize;
- (void)layoutSubView;
- (id)initWithFrame:(struct CGRect)arg1;

@end

