//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMChatBackupBasicLogic.h"

#import "MMChatBackupBackupHelperDelegate-Protocol.h"

@class MMChatBackupBackupHelper, MMChatLogProtoHandler, MMTimer, NSMutableSet, NSString;

@interface MMChatBackupBackupLogic : MMChatBackupBasicLogic <MMChatBackupBackupHelperDelegate>
{
    MMChatLogProtoHandler *m_protoHandler;
    MMChatBackupBackupHelper *m_chatBackupBackupHelper;
    NSString *m_deviceId;
    BOOL m_bStopService;
    unsigned long long m_totalSessionCount;
    NSMutableSet *m_sessionProgressSet;
    MMTimer *fileWriteCompleteTimer;
    unsigned long long m_receivedTagCount;
    NSString *phoneType;
}

- (void).cxx_destruct;
- (BOOL)sendData:(id)arg1;
- (void)copyLogFile;
- (void)backupFinish;
- (void)processFinishRequestData:(id)arg1;
- (void)sendDataTagResponseForDataTag:(id)arg1;
- (void)onDataTagProcessEnd:(id)arg1;
- (void)processBackupDataTagData:(id)arg1;
- (void)sendDataPushResponse:(id)arg1;
- (void)onData:(id)arg1 writeToFileFinsh:(BOOL)arg2;
- (void)processDataPushData:(id)arg1;
- (void)sendRequestSessionResponseWithDataInfoArray:(id)arg1;
- (void)onRequestSessionProcessEndWithResponse:(id)arg1;
- (void)processRequestSessionData:(id)arg1;
- (void)sendStartResponseWithStatus:(int)arg1;
- (void)processStartRequestData:(id)arg1;
- (void)stopService;
- (void)startService;
- (void)dealloc;
- (id)initWithProtoHandler:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

