//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMChatItemViewerWindow.h"

@class AVPlayer, AVPlayerView, NSURL;

@interface MMChatVideoViewerWindow : MMChatItemViewerWindow
{
    AVPlayer *_player;
    AVPlayerView *_playerView;
    NSURL *_fileUrl;
    struct CGSize _contentSize;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSURL *fileUrl; // @synthesize fileUrl=_fileUrl;
@property(retain, nonatomic) AVPlayerView *playerView; // @synthesize playerView=_playerView;
@property(nonatomic) struct CGSize contentSize; // @synthesize contentSize=_contentSize;
@property(retain, nonatomic) AVPlayer *player; // @synthesize player=_player;
- (id)contentForSharing;
- (void)openWith:(id)arg1;
- (void)exportContent:(id)arg1;
- (id)contentViewImage;
- (void)playerItemDidReachEnd:(id)arg1;
- (BOOL)isAVPlayerViewSupported;
- (void)initVideoView;
- (BOOL)initPlaying;
- (void)mouseExited:(id)arg1;
- (void)mouseEntered:(id)arg1;
- (id)supportedActions;
- (void)close;
- (void)showWindowAnimated:(BOOL)arg1;
- (struct CGSize)sizeForContent;
- (void)loadContent;
- (void)windowDidLoad;

@end

