//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMChatBaseSearchLogic.h"

@class FTSSearchTask, NSMutableDictionary, NSOperationQueue, NSRecursiveLock;

@interface MMChatFTSSearchLogic : MMChatBaseSearchLogic
{
    unsigned int _msgPageSize;
    NSOperationQueue *_m_ftsSearchQueue;
    NSRecursiveLock *_m_oLock;
    NSMutableDictionary *_m_dictForSearchTask;
    FTSSearchTask *_lastTask;
}

- (void).cxx_destruct;
@property(nonatomic) unsigned int msgPageSize; // @synthesize msgPageSize=_msgPageSize;
@property(retain, nonatomic) FTSSearchTask *lastTask; // @synthesize lastTask=_lastTask;
@property(retain, nonatomic) NSMutableDictionary *m_dictForSearchTask; // @synthesize m_dictForSearchTask=_m_dictForSearchTask;
@property(retain, nonatomic) NSRecursiveLock *m_oLock; // @synthesize m_oLock=_m_oLock;
@property(retain, nonatomic) NSOperationQueue *m_ftsSearchQueue; // @synthesize m_ftsSearchQueue=_m_ftsSearchQueue;
- (void)reportCostTime:(unsigned long long)arg1;
- (id)doAdditionalDBSearch:(id)arg1;
- (void)clearSearch;
- (void)clearSearchWithKeyword:(id)arg1 chatName:(id)arg2;
- (id)searchFromLastGlobalResults:(BOOL)arg1 nsChatName:(id)arg2;
- (void)doSearch:(id)arg1;
- (void)doSearchWithKeyword:(id)arg1 chatName:(id)arg2 realFromUser:(id)arg3 messageType:(unsigned int)arg4 minMsgCreateTime:(unsigned int)arg5 maxMsgCreateTime:(unsigned int)arg6 limitCount:(unsigned int)arg7 isFromGlobalSearch:(unsigned char)arg8 isScrollingToBottom:(unsigned char)arg9 completion:(CDUnknownBlockType)arg10;
- (void)doSearchAndLoadMessageOfNextPageWithKeyword:(id)arg1 chatName:(id)arg2 realFromUser:(id)arg3 messageType:(unsigned int)arg4 limitCount:(int)arg5 isFromGlobalSearch:(unsigned char)arg6 isScrollingToBottom:(unsigned char)arg7 completion:(CDUnknownBlockType)arg8;
- (id)init;

@end

