//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMService.h"

#import "MMCGIDelegate-Protocol.h"
#import "MMService-Protocol.h"

@class NSMutableArray, NSRecursiveLock, NSString;

@interface MMContactTagMgr : MMService <MMCGIDelegate, MMService>
{
    BOOL _bRemove;
    unsigned int _lastTimeGetAllLabelsFromServer;
    NSMutableArray *_cachedTags;
    NSRecursiveLock *_lock;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSRecursiveLock *lock; // @synthesize lock=_lock;
@property(nonatomic) BOOL bRemove; // @synthesize bRemove=_bRemove;
@property(nonatomic) unsigned int lastTimeGetAllLabelsFromServer; // @synthesize lastTimeGetAllLabelsFromServer=_lastTimeGetAllLabelsFromServer;
@property(retain, nonatomic) NSMutableArray *cachedTags; // @synthesize cachedTags=_cachedTags;
- (void)OnResponseCGI:(BOOL)arg1 sessionId:(unsigned int)arg2 cgiWrap:(id)arg3;
- (void)onResponseFromAddTags:(BOOL)arg1 cgiWrap:(id)arg2;
- (void)addTagsWithName:(id)arg1;
- (void)onResponseFromModifyContactsToTags:(BOOL)arg1 cgiWrap:(id)arg2;
- (void)updateContacts:(id)arg1 withTagIDs:(id)arg2;
- (void)updateContact:(id)arg1 withTagIDs:(id)arg2;
- (void)updateContacts:(id)arg1 withRemoveTagID:(id)arg2;
- (void)onResponseFromUpdateTagInfo:(BOOL)arg1 cgiWrap:(id)arg2;
- (void)updateTagName:(id)arg1 newName:(id)arg2;
- (void)onResponseFromDeleteTagsList:(BOOL)arg1 cgiWrap:(id)arg2;
- (void)deleteTagWithTagID:(id)arg1;
- (void)onResponseFromGetAllContactTagsList:(BOOL)arg1 cgiWrap:(id)arg2;
- (void)getAllTagsFromServer;
- (void)receiveTagsFromSyncModContacts;
- (id)getCurrentVisibleTagName:(id)arg1 withIndex:(int)arg2;
- (BOOL)isAlreadyExistTagName:(id)arg1;
- (id)tagsForUserName:(id)arg1;
- (id)tagStrForContact:(id)arg1;
- (id)tagsForContact:(id)arg1;
- (id)tagInfoForTagId:(id)arg1;
- (id)tagInfoForTagTitle:(id)arg1;
- (id)contactTagWithTagID:(id)arg1;
- (id)tagStringForTagId:(id)arg1;
- (id)tagIdForTagString:(id)arg1;
- (id)contactsWithTag:(id)arg1 inList:(id)arg2;
- (id)contactsWithTagID:(id)arg1 inList:(id)arg2;
- (void)cleanUpAllTags;
- (id)allTagsCachedForList;
- (id)allTagsCached;
- (void)saveCachedTags;
- (void)loadCachedTags;
- (id)contactTagCachePath;
- (void)onServiceClearData;
- (void)onServiceInit;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

