//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMFavImageServiceBaseHandler.h"

#import "IMMNewRecordDownloadServiceExt-Protocol.h"

@class MMThreadSafeArray, MMThreadSafeDictionary, NSString;

@interface MMFavImageServiceImageHandler : MMFavImageServiceBaseHandler <IMMNewRecordDownloadServiceExt>
{
    MMThreadSafeArray *m_downloadingTaskArray;
    MMThreadSafeDictionary *m_taskToFavThumbRequestDict;
    MMThreadSafeDictionary *m_taskToCompletionBlockDict;
}

- (void).cxx_destruct;
- (void)onCdnDownloadFinishWithTaskID:(id)arg1;
- (void)onDownloadRecordOK:(id)arg1 key:(id)arg2 context:(id)arg3;
- (void)processFavThumbRequest:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

