//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMSidebarItem.h"

@class WCContactData;

@interface MMFavoriteSidebarItem : MMSidebarItem
{
    BOOL _expanded;
    int _type;
    WCContactData *_contact;
}

+ (id)spacer;
+ (id)tagItemWithTagString:(id)arg1;
+ (id)itemWithType:(int)arg1;
- (void).cxx_destruct;
@property(nonatomic) BOOL expanded; // @synthesize expanded=_expanded;
@property(retain, nonatomic) WCContactData *contact; // @synthesize contact=_contact;
@property(readonly, nonatomic) int type; // @synthesize type=_type;
- (BOOL)expandable;
- (BOOL)isHeader;
- (void)_configureWithType:(int)arg1;
- (id)initWithType:(int)arg1;
@property(copy, nonatomic) CDUnknownBlockType actionBlock;

@end

