//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSMutableArray, NSString;

@interface MMFavoritesCollectionData : NSObject
{
    BOOL _allowMultipleItemsPreview;
    NSString *_title;
    unsigned long long _layoutStyle;
    NSArray *_sections;
    NSMutableArray *_previewItems;
}

+ (id)keyFroRow:(unsigned long long)arg1 section:(unsigned long long)arg2;
+ (id)dataWithFavoriteItems:(id)arg1 title:(id)arg2 grouping:(unsigned long long)arg3 layoutStyle:(unsigned long long)arg4;
- (void).cxx_destruct;
@property(retain, nonatomic) NSMutableArray *previewItems; // @synthesize previewItems=_previewItems;
@property(retain, nonatomic) NSArray *sections; // @synthesize sections=_sections;
@property(nonatomic) BOOL allowMultipleItemsPreview; // @synthesize allowMultipleItemsPreview=_allowMultipleItemsPreview;
@property(nonatomic) unsigned long long layoutStyle; // @synthesize layoutStyle=_layoutStyle;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
- (void)clearAllItems;
- (unsigned long long)numberOfItemsInSection:(unsigned long long)arg1;
- (id)dateSectionsWithItems:(id)arg1;
- (id)searchSectionsWithItems:(id)arg1;
- (id)resultStringWithCount:(unsigned long long)arg1;
- (id)titleForSection:(unsigned long long)arg1;
- (id)itemAtRow:(unsigned long long)arg1 forSection:(unsigned long long)arg2;
@property(readonly, nonatomic) unsigned long long numberOfGroups;
@property(readonly, nonatomic) unsigned long long totalItemsCount;
- (id)indexPathForItemLocalID:(id)arg1;

@end

