//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMMessageCellView.h"

#import "IMMFileAttrInfoExt-Protocol.h"
#import "IMessageExt-Protocol.h"
#import "IMessageServiceFileExt-Protocol.h"
#import "MMAppMgrDownloadMsgExt-Protocol.h"
#import "MessageBatchExportMgrExt-Protocol.h"

@class CAShapeLayer, MMCTTextView, MMLoadingIndicatorView, MMTextField, MMTimer, NSImageView, NSString, NSView, SVGImageView, TKStateMachine;

@interface MMFileMessageCellView : MMMessageCellView <IMessageServiceFileExt, MessageBatchExportMgrExt, IMessageExt, MMAppMgrDownloadMsgExt, IMMFileAttrInfoExt>
{
    BOOL _isStartDownloadManully;
    BOOL _needAHighLight;
    BOOL _isInTransfering;
    int _fileMessageType;
    NSImageView *_fileIcon;
    NSImageView *_fileEmptyIcon;
    NSImageView *_fileMask;
    NSView *_containerView;
    MMCTTextView *_fileTitleLabel;
    MMTextField *_subtitleLabel;
    MMTextField *_statesLabel;
    NSView *_progressContainerView;
    SVGImageView *_actionButton;
    TKStateMachine *_stateMachine;
    CAShapeLayer *_strokeLayer;
    CAShapeLayer *_highlightLayer;
    CAShapeLayer *_progressLayer;
    MMLoadingIndicatorView *_loadingView;
    MMTimer *_remainTimeTimer;
}

+ (double)cellHeightWithMessage:(id)arg1 constrainedToWidth:(double)arg2;
- (void).cxx_destruct;
@property(retain, nonatomic) MMTimer *remainTimeTimer; // @synthesize remainTimeTimer=_remainTimeTimer;
@property(retain, nonatomic) MMLoadingIndicatorView *loadingView; // @synthesize loadingView=_loadingView;
@property(retain, nonatomic) CAShapeLayer *progressLayer; // @synthesize progressLayer=_progressLayer;
@property(retain, nonatomic) CAShapeLayer *highlightLayer; // @synthesize highlightLayer=_highlightLayer;
@property(retain, nonatomic) CAShapeLayer *strokeLayer; // @synthesize strokeLayer=_strokeLayer;
@property(nonatomic) BOOL isInTransfering; // @synthesize isInTransfering=_isInTransfering;
@property(nonatomic) BOOL needAHighLight; // @synthesize needAHighLight=_needAHighLight;
@property(nonatomic) BOOL isStartDownloadManully; // @synthesize isStartDownloadManully=_isStartDownloadManully;
@property(nonatomic) int fileMessageType; // @synthesize fileMessageType=_fileMessageType;
@property(retain, nonatomic) TKStateMachine *stateMachine; // @synthesize stateMachine=_stateMachine;
@property(retain, nonatomic) SVGImageView *actionButton; // @synthesize actionButton=_actionButton;
@property(retain, nonatomic) NSView *progressContainerView; // @synthesize progressContainerView=_progressContainerView;
@property(retain, nonatomic) MMTextField *statesLabel; // @synthesize statesLabel=_statesLabel;
@property(retain, nonatomic) MMTextField *subtitleLabel; // @synthesize subtitleLabel=_subtitleLabel;
@property(retain, nonatomic) MMCTTextView *fileTitleLabel; // @synthesize fileTitleLabel=_fileTitleLabel;
@property(retain, nonatomic) NSView *containerView; // @synthesize containerView=_containerView;
@property(retain, nonatomic) NSImageView *fileMask; // @synthesize fileMask=_fileMask;
@property(retain, nonatomic) NSImageView *fileEmptyIcon; // @synthesize fileEmptyIcon=_fileEmptyIcon;
@property(retain, nonatomic) NSImageView *fileIcon; // @synthesize fileIcon=_fileIcon;
- (void)processAutoDownload;
- (BOOL)isAutoDownload;
- (void)updateAppMsgState:(id)arg1 andState:(unsigned int)arg2;
- (void)onRecvDownloadItem:(id)arg1;
- (BOOL)isFileCanOpenWithQPL;
- (void)updateCurrentFileMessageType;
- (id)getFileNameFromMsgContent:(id)arg1;
- (void)setChoosable:(BOOL)arg1;
- (BOOL)allowChoose;
- (BOOL)canShowContinueUploadMenuItem;
- (void)updateFileMessageOpTime:(id)arg1;
- (void)contextMenuContinue;
- (void)contextMenuCancle;
- (void)contextMenuDownload;
- (void)contextMenuForward;
- (void)contextMenuExport;
- (void)contextMenuEdit;
- (void)contextMenuOpen;
- (id)getSection2MenuItem;
- (id)getSection1MenuItem;
- (id)getSection0MenuItem;
- (void)writeIntoPasteboard:(id)arg1 orItem:(id)arg2 provideDataForType:(id)arg3;
- (id)draggablePasteboardTypes;
- (id)draggingImage;
- (BOOL)draggingEnabled;
- (void)mouseUp:(id)arg1;
- (void)mouseDown:(id)arg1;
- (void)mouseDragged:(id)arg1;
- (unsigned int)getFileDownloadStatus;
- (void)onNeedRefreshTransferRemainTime;
- (void)updateHighlightMaskView;
- (void)resizeSubviewsWithOldSize:(struct CGSize)arg1;
- (void)stopWait;
- (void)pause;
- (void)export:(id)arg1;
- (void)realManualDownload:(id)arg1;
- (void)realNonManualDownload:(id)arg1;
- (void)startDownload;
- (void)startAutoDownload;
- (void)startManualDownload;
- (void)retry;
- (void)ReTransferFile;
- (void)OnBatchExportStartDownloadingWithMessage:(id)arg1;
- (void)onFileDidCancelUploadWithMessage:(id)arg1;
- (void)onFileDidFinishUploadWithMessage:(id)arg1 isSuccess:(BOOL)arg2;
- (void)onFileUploaded:(int)arg1 of:(int)arg2 withMessage:(id)arg3;
- (void)onFileDidCancelDownloadWithMessage:(id)arg1;
- (void)onFileDidFailDownloadWithMessage:(id)arg1;
- (void)onFileDidFinishDownloadWithMessage:(id)arg1 isPredownload:(BOOL)arg2;
- (void)onFileDownloaded:(int)arg1 of:(int)arg2 withMessage:(id)arg3;
- (void)continueSendMessage;
- (void)resendMessage;
- (void)_fireStateEvent:(id)arg1;
- (struct CGRect)fileIconFrame;
- (struct CGRect)bubbleFrame;
- (struct CGRect)clickableArea;
- (void)_switchToProgressState;
- (void)_switchToWaitingState;
- (void)_switchToNormal;
- (void)hideAllChangeableViews;
- (void)_layoutMainViews;
- (void)updateProgressByValue:(double)arg1;
- (void)updateSubTitle:(id)arg1 states:(id)arg2 stress:(BOOL)arg3;
- (void)updateMessageLayer;
- (BOOL)accessibilityPerformPress;
- (id)accessibilityContent;
- (void)layoutFileAttrInfoIfNeeded;
- (void)onMessageFileAttrInfoUpdated:(id)arg1;
- (void)layoutWaitingAccessories;
- (void)populateWithMessage:(id)arg1;
- (void)prepareForReuse;
- (void)_setupStateMachine;
- (void)viewDidChangeEffectiveAppearance;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

