//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface MMGetA8KeyConfig : NSObject
{
    BOOL _useFullUrl;
    unsigned int _scene;
    int _reason;
    unsigned int _contentType;
    unsigned int _appMsgInnerType;
    NSString *_username;
    NSString *_msgId;
    NSString *_msgUserName;
}

- (void).cxx_destruct;
@property(nonatomic) unsigned int appMsgInnerType; // @synthesize appMsgInnerType=_appMsgInnerType;
@property(nonatomic) unsigned int contentType; // @synthesize contentType=_contentType;
@property(retain, nonatomic) NSString *msgUserName; // @synthesize msgUserName=_msgUserName;
@property(retain, nonatomic) NSString *msgId; // @synthesize msgId=_msgId;
@property(nonatomic) int reason; // @synthesize reason=_reason;
@property(copy, nonatomic) NSString *username; // @synthesize username=_username;
@property(nonatomic) BOOL useFullUrl; // @synthesize useFullUrl=_useFullUrl;
@property(nonatomic) unsigned int scene; // @synthesize scene=_scene;
- (id)description;

@end

