//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSView.h>

#import "MMImageEditTailorItemDelegate-Protocol.h"

@class MMImageEditTailorSelectItem, MMTextView, NSColor, NSString, NSTrackingArea;
@protocol MMImageEditTailorViewDelegate;

@interface MMImageEditTailorView : NSView <MMImageEditTailorItemDelegate>
{
    BOOL _needScreenCapture;
    BOOL _selectComfirmed;
    BOOL _needDrawControlPoints;
    BOOL _needDrawSelectedItem;
    unsigned char _isShowTips;
    id <MMImageEditTailorViewDelegate> _delegate;
    MMImageEditTailorSelectItem *_selectedItem;
    NSColor *_backgroundMaskColor;
    NSColor *_tipsBackgroundColor;
    NSTrackingArea *_trackingArea;
    unsigned long long _selectedItemType;
    unsigned long long _cursorType;
    MMTextView *_tipsView;
    struct CGPoint _startPoint;
    struct CGPoint _endPoint;
}

- (void).cxx_destruct;
@property(retain, nonatomic) MMTextView *tipsView; // @synthesize tipsView=_tipsView;
@property(nonatomic) unsigned char isShowTips; // @synthesize isShowTips=_isShowTips;
@property(nonatomic) unsigned long long cursorType; // @synthesize cursorType=_cursorType;
@property(nonatomic) struct CGPoint endPoint; // @synthesize endPoint=_endPoint;
@property(nonatomic) struct CGPoint startPoint; // @synthesize startPoint=_startPoint;
@property(nonatomic) unsigned long long selectedItemType; // @synthesize selectedItemType=_selectedItemType;
@property(retain, nonatomic) NSTrackingArea *trackingArea; // @synthesize trackingArea=_trackingArea;
@property(retain, nonatomic) NSColor *tipsBackgroundColor; // @synthesize tipsBackgroundColor=_tipsBackgroundColor;
@property(retain, nonatomic) NSColor *backgroundMaskColor; // @synthesize backgroundMaskColor=_backgroundMaskColor;
@property(retain, nonatomic) MMImageEditTailorSelectItem *selectedItem; // @synthesize selectedItem=_selectedItem;
@property(nonatomic) BOOL needDrawSelectedItem; // @synthesize needDrawSelectedItem=_needDrawSelectedItem;
@property(nonatomic) BOOL needDrawControlPoints; // @synthesize needDrawControlPoints=_needDrawControlPoints;
@property(nonatomic) BOOL selectComfirmed; // @synthesize selectComfirmed=_selectComfirmed;
@property(nonatomic) BOOL needScreenCapture; // @synthesize needScreenCapture=_needScreenCapture;
@property(nonatomic) __weak id <MMImageEditTailorViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void)finishCapture;
- (void)prepareForCapture;
- (void)selectionDidChange;
- (void)handelMouseDraggedWithFixedPoint:(struct CGPoint)arg1 lastDraggedPoint:(struct CGPoint)arg2 draggedPoint:(struct CGPoint)arg3;
- (void)updateCursorWithMousePoint:(struct CGPoint)arg1;
- (BOOL)updateSelectedItemType:(unsigned long long *)arg1 cursorType:(unsigned long long *)arg2 fixedPoint:(struct CGPoint *)arg3 byMousePoint:(struct CGPoint)arg4;
- (struct CGRect)pixelSelectedRectInWindow;
- (void)drawRect:(struct CGRect)arg1;
- (void)mouseExited:(id)arg1;
- (void)mouseEntered:(id)arg1;
- (void)mouseMoved:(id)arg1;
- (void)mouseDown:(id)arg1;
- (void)updateTrackingAreas;
- (struct CGRect)selectedRect;
- (void)cursorUpdate:(id)arg1;
- (BOOL)acceptsFirstMouse:(id)arg1;
- (void)configAppearanceAndLayout;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

