//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSTextAttachmentCell.h>

@class NSAttributedString;

@interface MMMetionTextAttachmentCell : NSTextAttachmentCell
{
    NSAttributedString *_attrString;
    struct CGSize _textSize;
}

- (void).cxx_destruct;
@property(nonatomic) struct CGSize textSize; // @synthesize textSize=_textSize;
@property(retain, nonatomic) NSAttributedString *attrString; // @synthesize attrString=_attrString;
- (void)drawWithFrame:(struct CGRect)arg1 inView:(id)arg2;
- (struct CGSize)cellSize;
- (id)init;

@end

