//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMService.h"

#import "MMService-Protocol.h"

@class MMCache, NSObject, NSString;
@protocol OS_dispatch_queue;

@interface MMPreviewImageFileService : MMService <MMService>
{
    MMCache *_innerCache;
    NSObject<OS_dispatch_queue> *_cacheQueue;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *cacheQueue; // @synthesize cacheQueue=_cacheQueue;
@property(retain, nonatomic) MMCache *innerCache; // @synthesize innerCache=_innerCache;
- (void)fetchAvatar:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)fetchImage:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)fetchImageIgnoreCache:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)prepareImageDataWithPreviewItem:(id)arg1;
- (void)asyncImageDataCache:(id)arg1 ForKey:(id)arg2;
- (BOOL)isImageInCached:(id)arg1;
- (void)removeImageDataFromCache:(id)arg1;
- (id)loadImageDataFromCache:(id)arg1;
- (void)onServiceClearData;
- (void)onServiceWillSleep;
- (void)onServiceInit;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

