//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSTouchBarDelegate-Protocol.h"

@class NSString, _TtC6WeChat13WCMPlayerView, _TtC6WeChat9WCMPlayer;
@protocol MMPreviewVideoPlayerDelegate;

@interface MMPreviewVideoPlayerControl : NSObject <NSTouchBarDelegate>
{
    id <MMPreviewVideoPlayerDelegate> _delegate;
    _TtC6WeChat13WCMPlayerView *_playerView;
    _TtC6WeChat9WCMPlayer *_player;
    NSString *_currentPath;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSString *currentPath; // @synthesize currentPath=_currentPath;
@property(retain, nonatomic) _TtC6WeChat9WCMPlayer *player; // @synthesize player=_player;
@property(retain, nonatomic) _TtC6WeChat13WCMPlayerView *playerView; // @synthesize playerView=_playerView;
@property(nonatomic) __weak id <MMPreviewVideoPlayerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)popupVideoInfo;
- (id)makeSurePlayerView;
- (id)getPlayer;
- (id)getPlayerView;
- (BOOL)isVisiable:(id)arg1;
- (void)remove;
- (void)onSpacePressed;
- (id)capture;
- (void)releasePlayer;
- (void)pause;
- (void)play;
- (void)hide:(BOOL)arg1;
- (void)load:(id)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)initPlayView;
- (void)destroy;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

