//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSViewController.h>

@class MMPreviewSnsVideoPlayerView, MMPreviewVideoPlayerView, MMQLPreviewPageInfo, MMTimer, NSImageView, NSView, _TtC6WeChat16PreviewImageView, _TtC6WeChat17PreviewScrollView;

@interface MMPreviewViewController : NSViewController
{
    BOOL _isSwapingMouse;
    BOOL _isTouchEdge;
    BOOL _shouldPlayVideo;
    BOOL _isRestore;
    BOOL _bDidResized;
    int _rotateDegrees;
    int _reflectRotateDegrees;
    CDUnknownBlockType _zoomImageBlock;
    CDUnknownBlockType _restoreImageBlock;
    CDUnknownBlockType _restoreActionBlock;
    CDUnknownBlockType _retryDownloadImageBlock;
    CDUnknownBlockType _finishDownloadVideoBlock;
    MMQLPreviewPageInfo *_pageInfo;
    _TtC6WeChat17PreviewScrollView *_scrollView;
    _TtC6WeChat16PreviewImageView *_flipView;
    NSImageView *_thumbImageView;
    MMPreviewVideoPlayerView *_videoPlayerView;
    MMPreviewSnsVideoPlayerView *_snsVideoPlayerView;
    double _originZoomFactor;
    MMTimer *_scrollEndtimer;
    NSView *_maskView;
    struct CGSize _originContentSizeBeforeResize;
    struct CGRect _originFrameBeforeFullScreen;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSView *maskView; // @synthesize maskView=_maskView;
@property(retain, nonatomic) MMTimer *scrollEndtimer; // @synthesize scrollEndtimer=_scrollEndtimer;
@property(nonatomic) BOOL bDidResized; // @synthesize bDidResized=_bDidResized;
@property(nonatomic) struct CGSize originContentSizeBeforeResize; // @synthesize originContentSizeBeforeResize=_originContentSizeBeforeResize;
@property(nonatomic) struct CGRect originFrameBeforeFullScreen; // @synthesize originFrameBeforeFullScreen=_originFrameBeforeFullScreen;
@property(nonatomic) int reflectRotateDegrees; // @synthesize reflectRotateDegrees=_reflectRotateDegrees;
@property(nonatomic) int rotateDegrees; // @synthesize rotateDegrees=_rotateDegrees;
@property(nonatomic) double originZoomFactor; // @synthesize originZoomFactor=_originZoomFactor;
@property(nonatomic) BOOL isRestore; // @synthesize isRestore=_isRestore;
@property(nonatomic) BOOL shouldPlayVideo; // @synthesize shouldPlayVideo=_shouldPlayVideo;
@property(nonatomic) BOOL isTouchEdge; // @synthesize isTouchEdge=_isTouchEdge;
@property(nonatomic) BOOL isSwapingMouse; // @synthesize isSwapingMouse=_isSwapingMouse;
@property(retain, nonatomic) MMPreviewSnsVideoPlayerView *snsVideoPlayerView; // @synthesize snsVideoPlayerView=_snsVideoPlayerView;
@property(retain, nonatomic) MMPreviewVideoPlayerView *videoPlayerView; // @synthesize videoPlayerView=_videoPlayerView;
@property(retain, nonatomic) NSImageView *thumbImageView; // @synthesize thumbImageView=_thumbImageView;
@property(retain, nonatomic) _TtC6WeChat16PreviewImageView *flipView; // @synthesize flipView=_flipView;
@property __weak _TtC6WeChat17PreviewScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(retain, nonatomic) MMQLPreviewPageInfo *pageInfo; // @synthesize pageInfo=_pageInfo;
@property(copy, nonatomic) CDUnknownBlockType finishDownloadVideoBlock; // @synthesize finishDownloadVideoBlock=_finishDownloadVideoBlock;
@property(copy, nonatomic) CDUnknownBlockType retryDownloadImageBlock; // @synthesize retryDownloadImageBlock=_retryDownloadImageBlock;
@property(copy, nonatomic) CDUnknownBlockType restoreActionBlock; // @synthesize restoreActionBlock=_restoreActionBlock;
@property(copy, nonatomic) CDUnknownBlockType restoreImageBlock; // @synthesize restoreImageBlock=_restoreImageBlock;
@property(copy, nonatomic) CDUnknownBlockType zoomImageBlock; // @synthesize zoomImageBlock=_zoomImageBlock;
- (void)stopScrollTimer;
- (void)resetScrollTimer;
- (void)disableScrollViewDrag;
- (void)enableScrollViewDrag;
- (void)disableScrollViewScroll;
- (void)enableScrollViewScroll;
- (void)goBackToFeed;
- (BOOL)onSpacePressed;
- (void)hiddenMaskView;
- (void)showMaskView;
- (void)setupSnsVideoPlayerView;
- (void)setupSnsVideoMode;
- (void)setupVideoPlayerView;
- (void)setupVideoMode;
- (void)setupAvatarImageView;
- (void)setupImagePageInfo;
- (void)setupImageMode;
- (BOOL)shouldRotateWithResizeFrame;
- (void)updatePreviewImageView;
- (void)refreshOriginImageWithPageInfo:(id)arg1 ignoreCache:(BOOL)arg2;
- (void)refreshOriginImageWithPageInfo:(id)arg1;
- (void)setupWithPageInfo:(id)arg1;
- (void)addFullScreenToolBar:(id)arg1;
- (void)layoutSnsVideoView;
- (void)layoutVideoView;
- (BOOL)inRotateWithoutMagnify;
- (void)layoutImageViews;
- (void)layoutThumbImageView;
- (void)dealloc;
- (void)viewWillDisappear;
- (void)viewWillAppear;
- (void)viewDidLoad;
- (id)getOriginFilePath;
- (unsigned int)getOriginDataSize;
- (id)updateToOriginFileInfo:(id)arg1;
- (BOOL)isLargeImageForLoad;
- (BOOL)isDelayLoadOriginImage;
- (void)setupOriginImage:(id)arg1;
- (void)setupThumbImageView:(id)arg1 withResize:(struct CGSize)arg2;
- (void)setupImageUrlPageInfo;
- (void)setupSNSPageInfo;
- (void)setupRecordPageInfo;
- (void)setupFavPageInfo;
- (void)setupMessagePageInfo;
- (void)handleImageWhenRecallOrDel;
- (void)updateDidExitFullScreen;
- (void)updateWillEnterFullScreen;
- (void)removeThumbWhenResizing;
- (void)resizePreviewImageView;
- (void)updatePreviewImageWhenResizing;
- (void)rotateImageAndReflect:(BOOL)arg1 withAnimation:(BOOL)arg2;
- (void)doAnimatedRotateImage:(struct CGRect)arg1 withFlag:(int)arg2 complete:(CDUnknownBlockType)arg3;
- (void)doAnimatedRotateRestoreImage:(struct CGRect)arg1 withFlag:(int)arg2 withContentSize:(struct CGSize)arg3;
- (void)flipViewRotateAndSetFrame:(struct CGRect)arg1;
- (void)doImageAnimationInAnchorPoint:(struct CGPoint)arg1 complete:(CDUnknownBlockType)arg2;
- (void)updateScrollPointWithLongImage:(BOOL)arg1;
- (void)updateRestoreImageStatusWithOriginal:(BOOL)arg1;
- (void)standardizeImage;
- (void)restoreImage:(BOOL)arg1;
- (struct CGSize)getRealRestoreImageSize;
- (struct CGSize)getOriginImageDisplaySize;
- (double)maxMagnification;
- (double)minMagnification;
- (void)updateZoomInOutStatus;
- (void)updateZoomImageStatus;
- (void)standardSize;
- (void)zoomOut;
- (void)zoomIn;
- (void)zoomActionWithFactor:(double)arg1;
- (void)resetAdjust;
- (void)reset;

@end

