//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMChatLogWebPageCellView.h"

#import "IMMRecordNestedDownloadMgrExt-Protocol.h"

@class NSString;

@interface MMRecordChatLogWebPageCellView : MMChatLogWebPageCellView <IMMRecordNestedDownloadMgrExt>
{
}

- (void)OnDownloadRecordNestedDataFieldOK:(id)arg1 DataId:(id)arg2 bThumb:(BOOL)arg3;
- (void)populateWithFavItemDataField:(id)arg1 parentDataField:(id)arg2;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

