//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMService.h"

#import "MMService-Protocol.h"

@class MMRevokeMsgDB, NSMutableSet, NSString;

@interface MMRevokeMsgService : MMService <MMService>
{
    MMRevokeMsgDB *_db;
    NSMutableSet *_revokingMessages;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSMutableSet *revokingMessages; // @synthesize revokingMessages=_revokingMessages;
@property(retain, nonatomic) MMRevokeMsgDB *db; // @synthesize db=_db;
- (BOOL)isMsgOutOfDate:(id)arg1;
- (BOOL)isRevokeMsgEditable:(id)arg1;
- (void)reEditRevokeMessageData:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)deleteRevokeMsgNode:(id)arg1;
- (void)reloadRevokeMsgNode:(id)arg1;
- (void)addRevokeMessageData:(id)arg1;
- (BOOL)recallMsgWithChatName:(id)arg1 msgData:(id)arg2 erroHandler:(CDUnknownBlockType)arg3;
- (void)onServiceInit;
- (void)onServiceClearData;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

