//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "PBCoding-Protocol.h"

@class NSString;

@interface MMSnsStreamVideoInfo : NSObject <PBCoding>
{
    unsigned int uiStreamVideoTime;
    NSString *streamVideoUrl;
    NSString *streamVideoTitle;
    NSString *streamVideoWording;
    NSString *streamVideoWebUrl;
    NSString *streamVideoThumbUrl;
    NSString *streamVideoPublishId;
    NSString *streamVideoAdUxInfo;
}

+ (void)initialize;
+ (void)PBArrayAdd_streamVideoAdUxInfo;
+ (void)PBArrayAdd_streamVideoPublishId;
+ (void)PBArrayAdd_streamVideoThumbUrl;
+ (void)PBArrayAdd_uiStreamVideoTime;
+ (void)PBArrayAdd_streamVideoWebUrl;
+ (void)PBArrayAdd_streamVideoWording;
+ (void)PBArrayAdd_streamVideoTitle;
+ (void)PBArrayAdd_streamVideoUrl;
- (void).cxx_destruct;
@property(retain, nonatomic) NSString *streamVideoAdUxInfo; // @synthesize streamVideoAdUxInfo;
@property(retain, nonatomic) NSString *streamVideoPublishId; // @synthesize streamVideoPublishId;
@property(retain, nonatomic) NSString *streamVideoThumbUrl; // @synthesize streamVideoThumbUrl;
@property(nonatomic) unsigned int uiStreamVideoTime; // @synthesize uiStreamVideoTime;
@property(retain, nonatomic) NSString *streamVideoWebUrl; // @synthesize streamVideoWebUrl;
@property(retain, nonatomic) NSString *streamVideoWording; // @synthesize streamVideoWording;
@property(retain, nonatomic) NSString *streamVideoTitle; // @synthesize streamVideoTitle;
@property(retain, nonatomic) NSString *streamVideoUrl; // @synthesize streamVideoUrl;
- (BOOL)isValid;
- (const void *)getValueTagIndexMap;
- (id)getValueTypeTable;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

