//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class MMSnsUserComment, NSString;

@interface MMSnsMessage : NSObject
{
    BOOL hasRead;
    unsigned int delStatus;
    NSString *feedID;
    NSString *commentID;
    MMSnsUserComment *comment;
    MMSnsUserComment *refComment;
}

+ (id)fromSnsActionGroup:(id)arg1;
- (void).cxx_destruct;
@property(nonatomic) unsigned int delStatus; // @synthesize delStatus;
@property(nonatomic) BOOL hasRead; // @synthesize hasRead;
@property(retain, nonatomic) MMSnsUserComment *refComment; // @synthesize refComment;
@property(retain, nonatomic) MMSnsUserComment *comment; // @synthesize comment;
@property(retain, nonatomic) NSString *commentID; // @synthesize commentID;
@property(retain, nonatomic) NSString *feedID; // @synthesize feedID;
- (BOOL)isWCDataItemDeleted;
- (BOOL)isWCMessageDeleted;
- (id)description;
- (id)init;

@end

