//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface MMSnsXmlParser : NSObject
{
}

+ (long long)serverMediaSubTypeToLocalType:(long long)arg1 serverSubType:(long long)arg2;
+ (id)mediaListFromXmlNode:(struct XmlReaderNode_t *)arg1;
+ (id)mediaItemFromXmlNode:(struct XmlReaderNode_t *)arg1;
+ (id)urlFromXmlNode:(struct XmlReaderNode_t *)arg1;
+ (void)setAppMsgShareInfo:(id)arg1 byXmlNode:(struct XmlReaderNode_t *)arg2;
+ (void)setWeAppInfo:(id)arg1 byXmlNode:(struct XmlReaderNode_t *)arg2;
+ (void)setStreamVideoInfo:(id)arg1 byXmlNode:(struct XmlReaderNode_t *)arg2;
+ (void)setMusicInfo:(id)arg1 byXmlNode:(struct XmlReaderNode_t *)arg2;
+ (void)setActionInfo:(id)arg1 byXmlNode:(struct XmlReaderNode_t *)arg2;
+ (void)setAppInfo:(id)arg1 byXmlNode:(struct XmlReaderNode_t *)arg2;
+ (void)setLocationInfo:(id)arg1 byXmlNode:(struct XmlReaderNode_t *)arg2;
+ (id)xmlOfStreamVideoInfo:(id)arg1;
+ (id)xmlOfWeAppInfo:(id)arg1;
+ (id)xmlOfMusicInfo:(id)arg1;
+ (id)xmlOfActionInfo:(id)arg1;
+ (id)xmlOfAppInfo:(id)arg1;
+ (id)xmlOfLocationInfo:(id)arg1;
+ (void)setSnsContentItem:(id)arg1 byXmlNode:(struct XmlReaderNode_t *)arg2;
+ (BOOL)setDataItem:(id)arg1 byXml:(id)arg2;

@end

