//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "PBCoding-Protocol.h"

@class MMMusicShareItem, MMSnsAppMsgShareInfo, MMSnsFinderLiveShareItem, MMSnsFinderShareToMomentsItem, MMSnsMegaVideoShareItem, MMTingListenCategoryItem, MMTingListenItem, NSMutableArray, NSString;

@interface MMSnsContentItem : NSObject <PBCoding>
{
    int type;
    int subType;
    int flag;
    unsigned int createtime;
    NSString *title;
    NSString *desc;
    NSString *linkUrl;
    NSString *username;
    NSString *nickname;
    NSMutableArray *mediaList;
    MMSnsAppMsgShareInfo *appMsgShareInfo;
    NSString *emojiMd5;
    MMSnsFinderShareToMomentsItem *finderShareToMomentsItem;
    MMSnsMegaVideoShareItem *finderLongVideoShareItem;
    MMSnsFinderLiveShareItem *finderLiveShareItem;
    MMTingListenItem *tingListenItem;
    MMTingListenCategoryItem *tingCategoryItem;
    MMMusicShareItem *musicShareItem;
    NSString *_titlePattern;
    NSString *_descPattern;
}

+ (void)initialize;
+ (void)PBArrayAdd_musicShareItem;
+ (void)PBArrayAdd_tingCategoryItem;
+ (void)PBArrayAdd_tingListenItem;
+ (void)PBArrayAdd_finderLiveShareItem;
+ (void)PBArrayAdd_finderLongVideoShareItem;
+ (void)PBArrayAdd_finderShareToMomentsItem;
+ (void)PBArrayAdd_emojiMd5;
+ (void)PBArrayAdd_appMsgShareInfo;
+ (void)PBArrayAdd_mediaList;
+ (void)PBArrayAdd_createtime;
+ (void)PBArrayAdd_nickname;
+ (void)PBArrayAdd_username;
+ (void)PBArrayAdd_flag;
+ (void)PBArrayAdd_subType;
+ (void)PBArrayAdd_type;
+ (void)PBArrayAdd_linkUrl;
+ (void)PBArrayAdd_desc;
+ (void)PBArrayAdd_title;
- (void).cxx_destruct;
@property(retain, nonatomic) NSString *descPattern; // @synthesize descPattern=_descPattern;
@property(retain, nonatomic) NSString *titlePattern; // @synthesize titlePattern=_titlePattern;
@property(retain, nonatomic) MMMusicShareItem *musicShareItem; // @synthesize musicShareItem;
@property(retain, nonatomic) MMTingListenCategoryItem *tingCategoryItem; // @synthesize tingCategoryItem;
@property(retain, nonatomic) MMTingListenItem *tingListenItem; // @synthesize tingListenItem;
@property(retain, nonatomic) MMSnsFinderLiveShareItem *finderLiveShareItem; // @synthesize finderLiveShareItem;
@property(retain, nonatomic) MMSnsMegaVideoShareItem *finderLongVideoShareItem; // @synthesize finderLongVideoShareItem;
@property(retain, nonatomic) MMSnsFinderShareToMomentsItem *finderShareToMomentsItem; // @synthesize finderShareToMomentsItem;
@property(retain, nonatomic) NSString *emojiMd5; // @synthesize emojiMd5;
@property(retain, nonatomic) MMSnsAppMsgShareInfo *appMsgShareInfo; // @synthesize appMsgShareInfo;
@property(retain, nonatomic) NSMutableArray *mediaList; // @synthesize mediaList;
@property(nonatomic) unsigned int createtime; // @synthesize createtime;
@property(retain, nonatomic) NSString *nickname; // @synthesize nickname;
@property(retain, nonatomic) NSString *username; // @synthesize username;
@property(nonatomic) int flag; // @synthesize flag;
@property(nonatomic) int subType; // @synthesize subType;
@property(nonatomic) int type; // @synthesize type;
@property(retain, nonatomic) NSString *linkUrl; // @synthesize linkUrl;
@property(retain, nonatomic) NSString *desc; // @synthesize desc;
@property(retain, nonatomic) NSString *title; // @synthesize title;
- (BOOL)isValid;
- (const void *)getValueTagIndexMap;
- (id)getValueTypeTable;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

