//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSTableRowView.h>

@class CAShapeLayer, NSTextField;

@interface MMTagSearchCellView : NSTableRowView
{
    BOOL _bSelected;
    NSTextField *_titleTextField;
    CAShapeLayer *_backgroudLayer;
}

- (void).cxx_destruct;
@property(retain, nonatomic) CAShapeLayer *backgroudLayer; // @synthesize backgroudLayer=_backgroudLayer;
@property(nonatomic) BOOL bSelected; // @synthesize bSelected=_bSelected;
@property(retain, nonatomic) NSTextField *titleTextField; // @synthesize titleTextField=_titleTextField;
- (void)viewChangedEffectiveAppearance;
- (id)GenHightLightedAttrString:(id)arg1 withKeyWord:(id)arg2;
- (BOOL)isContainEmoji:(id)arg1;
- (void)updateContent:(id)arg1 withKeyWord:(id)arg2;
- (void)initSubView;
- (void)prepareForReuse;
- (id)initWithFrame:(struct CGRect)arg1;

@end

