//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "RBLPopoverBackgroundView.h"

@protocol MMTokenSearchPopoverBackgroundViewDelegate;

@interface MMTokenSearchPopoverBackgroundView : RBLPopoverBackgroundView
{
    id <MMTokenSearchPopoverBackgroundViewDelegate> _delegate;
}

- (void).cxx_destruct;
@property(nonatomic) __weak id <MMTokenSearchPopoverBackgroundViewDelegate> delegate; // @synthesize delegate=_delegate;
- (struct CGSize)sizeForBackgroundViewWithContentSize:(struct CGSize)arg1 popoverEdge:(unsigned int)arg2;

@end

