//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface MessageHelper : NSObject
{
}

+ (id)getFileAttrInfoWithPath:(id)arg1;
+ (id)imageMessageFileNameWithExt:(id)arg1;
+ (id)fileMessageExt:(id)arg1;
+ (void)locateMessageInChatMessageList:(id)arg1;
+ (void)reportChatManagerAction:(unsigned int)arg1 isGlobal:(BOOL)arg2 isGroupChat:(BOOL)arg3;
+ (void)reportFileUploadLog:(id)arg1 action:(unsigned int)arg2;
+ (void)reportFileLog:(id)arg1 action:(unsigned int)arg2;
+ (void)doReportWithAction:(unsigned long long)arg1 msgData:(id)arg2 resId:(id)arg3;
+ (void)SendOpReportWithMsgData:(id)arg1 resId:(id)arg2;
+ (void)ForwardOpReportWithMsgData:(id)arg1 resId:(id)arg2;

@end

