//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class MessageData, MessageTransferReportItem, NSString;
@protocol MessageSenderDelegate;

@interface MessageSender : NSObject
{
    NSString *m_nsChatName;
    unsigned long long m_taskId;
    MessageData *m_msgData;
    unsigned int m_cgiSessionId;
    BOOL m_uploadMediaOnly;
    id <MessageSenderDelegate> m_delegate;
    BOOL _m_didRetryForEmptyAeskey;
    MessageTransferReportItem *_reportItem;
}

- (void).cxx_destruct;
@property(retain, nonatomic) MessageTransferReportItem *reportItem; // @synthesize reportItem=_reportItem;
@property BOOL m_didRetryForEmptyAeskey; // @synthesize m_didRetryForEmptyAeskey=_m_didRetryForEmptyAeskey;
@property(nonatomic) __weak id <MessageSenderDelegate> delegate; // @synthesize delegate=m_delegate;
@property(nonatomic) BOOL uploadMediaOnly; // @synthesize uploadMediaOnly=m_uploadMediaOnly;
@property(retain, nonatomic) MessageData *msgData; // @synthesize msgData=m_msgData;
@property(nonatomic) unsigned long long taskId; // @synthesize taskId=m_taskId;
@property(retain, nonatomic) NSString *chatName; // @synthesize chatName=m_nsChatName;
- (void)onUploadOrHitCheckSuccess:(id)arg1 nsAesKey:(id)arg2;
- (void)retryUploadAndNoHitCheck:(id)arg1;
- (void)checkMd5:(id)arg1;
- (BOOL)checkContinueSend:(id)arg1;
- (BOOL)isEqual:(id)arg1;
- (void)startSending;
- (id)init;
- (void)onCheckTpMediaMd5Finish:(BOOL)arg1;
- (void)onCheckTpMediaMd5Success:(id)arg1 aesKey:(id)arg2;
- (void)checkTpMediaMd5:(id)arg1;

@end

