//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "PBGeneratedMessage.h"

@class NSMutableArray, NSString;

@interface SnsCommentInfo : PBGeneratedMessage
{
    unsigned int hasUsername:1;
    unsigned int hasNickname:1;
    unsigned int hasSource:1;
    unsigned int hasType:1;
    unsigned int hasContent:1;
    unsigned int hasCreateTime:1;
    unsigned int hasCommentId:1;
    unsigned int hasReplyCommentId:1;
    unsigned int hasReplyUsername:1;
    unsigned int hasIsNotRichText:1;
    unsigned int hasReplyCommentId2:1;
    unsigned int hasCommentId2:1;
    unsigned int hasDeleteFlag:1;
    unsigned int hasCommentFlag:1;
    unsigned int hasSnsEmojiInfoCount:1;
    unsigned int source;
    unsigned int type;
    unsigned int createTime;
    int commentId;
    int replyCommentId;
    unsigned int isNotRichText;
    unsigned int deleteFlag;
    unsigned int commentFlag;
    unsigned int snsEmojiInfoCount;
    NSString *username;
    NSString *nickname;
    NSString *content;
    NSString *replyUsername;
    unsigned long long replyCommentId2;
    unsigned long long commentId2;
    NSMutableArray *mutableSnsEmojiInfoList;
}

+ (id)parseFromData:(id)arg1;
- (void).cxx_destruct;
@property(nonatomic, setter=SetSnsEmojiInfoCount:) unsigned int snsEmojiInfoCount; // @synthesize snsEmojiInfoCount;
@property(readonly, nonatomic) BOOL hasSnsEmojiInfoCount; // @synthesize hasSnsEmojiInfoCount;
@property(retain, nonatomic) NSMutableArray *mutableSnsEmojiInfoList; // @synthesize mutableSnsEmojiInfoList;
@property(nonatomic, setter=SetCommentFlag:) unsigned int commentFlag; // @synthesize commentFlag;
@property(readonly, nonatomic) BOOL hasCommentFlag; // @synthesize hasCommentFlag;
@property(nonatomic, setter=SetDeleteFlag:) unsigned int deleteFlag; // @synthesize deleteFlag;
@property(readonly, nonatomic) BOOL hasDeleteFlag; // @synthesize hasDeleteFlag;
@property(nonatomic, setter=SetCommentId2:) unsigned long long commentId2; // @synthesize commentId2;
@property(readonly, nonatomic) BOOL hasCommentId2; // @synthesize hasCommentId2;
@property(nonatomic, setter=SetReplyCommentId2:) unsigned long long replyCommentId2; // @synthesize replyCommentId2;
@property(readonly, nonatomic) BOOL hasReplyCommentId2; // @synthesize hasReplyCommentId2;
@property(nonatomic, setter=SetIsNotRichText:) unsigned int isNotRichText; // @synthesize isNotRichText;
@property(readonly, nonatomic) BOOL hasIsNotRichText; // @synthesize hasIsNotRichText;
@property(retain, nonatomic, setter=SetReplyUsername:) NSString *replyUsername; // @synthesize replyUsername;
@property(readonly, nonatomic) BOOL hasReplyUsername; // @synthesize hasReplyUsername;
@property(nonatomic, setter=SetReplyCommentId:) int replyCommentId; // @synthesize replyCommentId;
@property(readonly, nonatomic) BOOL hasReplyCommentId; // @synthesize hasReplyCommentId;
@property(nonatomic, setter=SetCommentId:) int commentId; // @synthesize commentId;
@property(readonly, nonatomic) BOOL hasCommentId; // @synthesize hasCommentId;
@property(nonatomic, setter=SetCreateTime:) unsigned int createTime; // @synthesize createTime;
@property(readonly, nonatomic) BOOL hasCreateTime; // @synthesize hasCreateTime;
@property(retain, nonatomic, setter=SetContent:) NSString *content; // @synthesize content;
@property(readonly, nonatomic) BOOL hasContent; // @synthesize hasContent;
@property(nonatomic, setter=SetType:) unsigned int type; // @synthesize type;
@property(readonly, nonatomic) BOOL hasType; // @synthesize hasType;
@property(nonatomic, setter=SetSource:) unsigned int source; // @synthesize source;
@property(readonly, nonatomic) BOOL hasSource; // @synthesize hasSource;
@property(retain, nonatomic, setter=SetNickname:) NSString *nickname; // @synthesize nickname;
@property(readonly, nonatomic) BOOL hasNickname; // @synthesize hasNickname;
@property(retain, nonatomic, setter=SetUsername:) NSString *username; // @synthesize username;
@property(readonly, nonatomic) BOOL hasUsername; // @synthesize hasUsername;
- (void)addSnsEmojiInfo:(id)arg1;
- (void)addSnsEmojiInfoFromArray:(id)arg1;
- (id)mergeFromCodedInputStream:(id)arg1;
- (int)serializedSize;
- (void)writeToCodedOutputStream:(id)arg1;
- (BOOL)isInitialized;
@property(retain, nonatomic) NSMutableArray *snsEmojiInfo; // @dynamic snsEmojiInfo;
- (id)snsEmojiInfoList;
- (id)init;

@end

