//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "PBGeneratedMessage.h"

@class BaseRequest, NSString;

@interface BindBlackberryPPIDRequest : PBGeneratedMessage
{
    unsigned int hasBaseRequest:1;
    unsigned int hasOpcode:1;
    unsigned int hasBbppid:1;
    unsigned int hasBbpin:1;
    unsigned int hasBbmnickName:1;
    unsigned int hasForce:1;
    unsigned int opcode;
    unsigned int force;
    BaseRequest *baseRequest;
    NSString *bbppid;
    NSString *bbpin;
    NSString *bbmnickName;
}

+ (id)parseFromData:(id)arg1;
- (void).cxx_destruct;
@property(nonatomic, setter=SetForce:) unsigned int force; // @synthesize force;
@property(readonly, nonatomic) BOOL hasForce; // @synthesize hasForce;
@property(retain, nonatomic, setter=SetBbmnickName:) NSString *bbmnickName; // @synthesize bbmnickName;
@property(readonly, nonatomic) BOOL hasBbmnickName; // @synthesize hasBbmnickName;
@property(retain, nonatomic, setter=SetBbpin:) NSString *bbpin; // @synthesize bbpin;
@property(readonly, nonatomic) BOOL hasBbpin; // @synthesize hasBbpin;
@property(retain, nonatomic, setter=SetBbppid:) NSString *bbppid; // @synthesize bbppid;
@property(readonly, nonatomic) BOOL hasBbppid; // @synthesize hasBbppid;
@property(nonatomic, setter=SetOpcode:) unsigned int opcode; // @synthesize opcode;
@property(readonly, nonatomic) BOOL hasOpcode; // @synthesize hasOpcode;
@property(retain, nonatomic, setter=SetBaseRequest:) BaseRequest *baseRequest; // @synthesize baseRequest;
@property(readonly, nonatomic) BOOL hasBaseRequest; // @synthesize hasBaseRequest;
- (id)mergeFromCodedInputStream:(id)arg1;
- (int)serializedSize;
- (void)writeToCodedOutputStream:(id)arg1;
- (BOOL)isInitialized;
- (id)init;

@end

