//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "V2TRTCCloudObserver-Protocol.h"
#import "V2TXLivePlayer-Protocol.h"

@class NSString, NSView, V2TRTCCloud;
@protocol V2TXLivePlayer, V2TXLivePlayerObserver;

@interface TXTRTCPlayerImpl : NSObject <V2TRTCCloudObserver, V2TXLivePlayer>
{
    BOOL _hasPauseAudio;
    BOOL _hasPauseVideo;
    BOOL _enableCustomRendering;
    BOOL _mShowDebugView;
    id <V2TXLivePlayerObserver> _playerObserver;
    NSView *_mRenderView;
    long long _mRenderRotation;
    long long _mRenderFillMode;
    unsigned long long _mPlayoutVolume;
    double _minCacheTime;
    double _maxCacheTime;
    unsigned long long _volumeEvaluationInterval;
    long long _pixelFormat;
    long long _bufferType;
    V2TRTCCloud *_trtcCloud;
    NSString *_remoteUserId;
    long long _streamType;
    NSString *_url;
    NSString *_strRoomId;
    id <V2TXLivePlayer> _mV2player;
}

+ (long long)checkPlay:(id)arg1 urlParam:(id)arg2;
- (void).cxx_destruct;
@property(nonatomic) __weak id <V2TXLivePlayer> mV2player; // @synthesize mV2player=_mV2player;
@property(retain, nonatomic) NSString *strRoomId; // @synthesize strRoomId=_strRoomId;
@property(retain, nonatomic) NSString *url; // @synthesize url=_url;
@property(nonatomic) long long streamType; // @synthesize streamType=_streamType;
@property(retain, nonatomic) NSString *remoteUserId; // @synthesize remoteUserId=_remoteUserId;
@property(retain, nonatomic) V2TRTCCloud *trtcCloud; // @synthesize trtcCloud=_trtcCloud;
@property(nonatomic) BOOL mShowDebugView; // @synthesize mShowDebugView=_mShowDebugView;
@property(nonatomic) BOOL enableCustomRendering; // @synthesize enableCustomRendering=_enableCustomRendering;
@property(nonatomic) long long bufferType; // @synthesize bufferType=_bufferType;
@property(nonatomic) long long pixelFormat; // @synthesize pixelFormat=_pixelFormat;
@property(nonatomic) unsigned long long volumeEvaluationInterval; // @synthesize volumeEvaluationInterval=_volumeEvaluationInterval;
@property(nonatomic) double maxCacheTime; // @synthesize maxCacheTime=_maxCacheTime;
@property(nonatomic) double minCacheTime; // @synthesize minCacheTime=_minCacheTime;
@property(nonatomic) unsigned long long mPlayoutVolume; // @synthesize mPlayoutVolume=_mPlayoutVolume;
@property(nonatomic) BOOL hasPauseVideo; // @synthesize hasPauseVideo=_hasPauseVideo;
@property(nonatomic) BOOL hasPauseAudio; // @synthesize hasPauseAudio=_hasPauseAudio;
@property(nonatomic) long long mRenderFillMode; // @synthesize mRenderFillMode=_mRenderFillMode;
@property(nonatomic) long long mRenderRotation; // @synthesize mRenderRotation=_mRenderRotation;
@property(retain, nonatomic) NSView *mRenderView; // @synthesize mRenderView=_mRenderView;
@property(nonatomic) __weak id <V2TXLivePlayerObserver> playerObserver; // @synthesize playerObserver=_playerObserver;
- (void)onTRTCRemoteUserIdAvailable:(id)arg1;
- (void)onExitRoomByServer:(long long)arg1;
- (void)onEnterRoomFailed:(long long)arg1;
- (void)dealloc;
- (void)showDebugView:(BOOL)arg1;
- (long long)enableCustomRendering:(BOOL)arg1 pixelFormat:(long long)arg2 bufferType:(long long)arg3;
- (long long)snapshot;
- (long long)enableVolumeEvaluation:(unsigned long long)arg1;
- (long long)setCacheParams:(double)arg1 maxTime:(double)arg2;
- (long long)setPlayoutVolume:(unsigned long long)arg1;
- (long long)resumeVideo;
- (long long)pauseVideo;
- (long long)resumeAudio;
- (long long)pauseAudio;
- (int)isPlaying;
- (long long)stopPlayInner;
- (long long)stopPlay;
- (long long)startPlay:(id)arg1;
- (void)applyParams;
- (long long)setRenderFillMode:(long long)arg1;
- (long long)setRenderRotation:(long long)arg1;
- (long long)setRenderView:(id)arg1;
- (long long)setProperty:(id)arg1 value:(id)arg2;
- (void)setObserver:(id)arg1;
- (void)setV2player:(id)arg1;
- (id)init;
- (id)initWithURL:(id)arg1 player:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

