//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "PBGeneratedMessage.h"

@class NSData, NSMutableArray, NSString;

@interface UploadEmojiInfoReq : PBGeneratedMessage
{
    unsigned int hasMd5:1;
    unsigned int hasStartPos:1;
    unsigned int hasTotalLen:1;
    unsigned int hasEmojiBuffer:1;
    unsigned int hasIsSelfie:1;
    unsigned int isSelfie_:1;
    unsigned int hasAttachedText:1;
    unsigned int hasFollowingEmojiMd5:1;
    unsigned int hasPannelType:1;
    int startPos;
    int totalLen;
    unsigned int pannelType;
    NSString *md5;
    NSData *emojiBuffer;
    NSMutableArray *mutableAttachedEmojiMd5ListList;
    NSString *attachedText;
    NSString *followingEmojiMd5;
}

+ (id)parseFromData:(id)arg1;
- (void).cxx_destruct;
@property(nonatomic, setter=SetPannelType:) unsigned int pannelType; // @synthesize pannelType;
@property(readonly, nonatomic) BOOL hasPannelType; // @synthesize hasPannelType;
@property(retain, nonatomic, setter=SetFollowingEmojiMd5:) NSString *followingEmojiMd5; // @synthesize followingEmojiMd5;
@property(readonly, nonatomic) BOOL hasFollowingEmojiMd5; // @synthesize hasFollowingEmojiMd5;
@property(retain, nonatomic, setter=SetAttachedText:) NSString *attachedText; // @synthesize attachedText;
@property(readonly, nonatomic) BOOL hasAttachedText; // @synthesize hasAttachedText;
@property(retain, nonatomic) NSMutableArray *mutableAttachedEmojiMd5ListList; // @synthesize mutableAttachedEmojiMd5ListList;
@property(readonly, nonatomic) BOOL hasIsSelfie; // @synthesize hasIsSelfie;
@property(retain, nonatomic, setter=SetEmojiBuffer:) NSData *emojiBuffer; // @synthesize emojiBuffer;
@property(readonly, nonatomic) BOOL hasEmojiBuffer; // @synthesize hasEmojiBuffer;
@property(nonatomic, setter=SetTotalLen:) int totalLen; // @synthesize totalLen;
@property(readonly, nonatomic) BOOL hasTotalLen; // @synthesize hasTotalLen;
@property(nonatomic, setter=SetStartPos:) int startPos; // @synthesize startPos;
@property(readonly, nonatomic) BOOL hasStartPos; // @synthesize hasStartPos;
@property(retain, nonatomic, setter=SetMd5:) NSString *md5; // @synthesize md5;
@property(readonly, nonatomic) BOOL hasMd5; // @synthesize hasMd5;
- (void)addAttachedEmojiMd5ListFromArray:(id)arg1;
- (void)addAttachedEmojiMd5List:(id)arg1;
- (id)mergeFromCodedInputStream:(id)arg1;
- (int)serializedSize;
- (void)writeToCodedOutputStream:(id)arg1;
- (BOOL)isInitialized;
@property(retain, nonatomic) NSMutableArray *attachedEmojiMd5List; // @dynamic attachedEmojiMd5List;
- (id)attachedEmojiMd5ListList;
@property(nonatomic, setter=SetIsSelfie:) BOOL isSelfie; // @synthesize isSelfie=isSelfie_;
- (id)init;

@end

