//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSViewController.h>

@class _TtC6WeChat31SnsPublishRightWindowController;

@interface _TtC6WeChat29SnsPublishRightViewController : NSViewController
{
    // Error parsing type: , name: windowController
    // Error parsing type: , name: titleTextField
    // Error parsing type: , name: confirmButton
    // Error parsing type: , name: cancelButton
    // Error parsing type: , name: separatorView
    // Error parsing type: , name: rightSelectView
    // Error parsing type: , name: stackView
    // Error parsing type: , name: currentRight
    // Error parsing type: , name: currentList
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)onClickCancel:(id)arg1;
- (void)onClickConfirm:(id)arg1;
- (void)performClose:(id)arg1;
- (void)onSelectPartAgainst:(id)arg1;
- (void)onSelectPart:(id)arg1;
- (void)onSelectPrivate:(id)arg1;
- (void)onSelectPublic:(id)arg1;
- (void)viewWillAppear;
- (void)viewDidLoad;
- (void)loadView;
@property(nonatomic) __weak _TtC6WeChat31SnsPublishRightWindowController *windowController; // @synthesize windowController;

@end

