//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSViewController.h>

@interface _TtC6WeChat30SnsAlbumCalendarViewController : NSViewController
{
    // Error parsing type: , name: didCloseBlock
    // Error parsing type: , name: disposeBag
    // Error parsing type: , name: selectItem
    // Error parsing type: , name: selectYear
    // Error parsing type: , name: browerYearMonthInfo
    // Error parsing type: , name: preButton
    // Error parsing type: , name: nextButton
    // Error parsing type: , name: titleField
    // Error parsing type: , name: divider
    // Error parsing type: , name: buttonArray
    // Error parsing type: , name: yearsArray
    // Error parsing type: , name: rblPopover
    // Error parsing type: , name: backgroundView
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)viewDidLoad;

@end

