//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMMouseEventView.h"

@interface _TtC6WeChat17SnsAlbumThumbView : MMMouseEventView
{
    // Error parsing type: , name: disposeBag
    // Error parsing type: , name: MAXCOUNT
    // Error parsing type: , name: contact
    // Error parsing type: , name: imgArr
    // Error parsing type: , name: realImageCount
}

- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)setFrameSize:(struct CGSize)arg1;
- (void)reloadData:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)dealloc;
- (id)init:(id)arg1;
- (id)init;

@end

