//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC6WeChat15SnsTrackingView.h"

@interface _TtC6WeChat25SnsPublishRightSelectView : _TtC6WeChat15SnsTrackingView
{
    // Error parsing type: , name: viewModel
    // Error parsing type: , name: checkBox
    // Error parsing type: , name: titleTextField
    // Error parsing type: , name: subTitleTextField
    // Error parsing type: , name: nextIcon
    // Error parsing type: , name: separatorView
}

- (void).cxx_destruct;
- (id)accessibilityRole;
- (BOOL)isAccessibilityElement;
- (id)accessibilityLabel;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithCoder:(id)arg1;
- (id)init;

@end

