//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMService.h"

@interface _TtC6WeChat17SnsResourceCenter : MMService
{
    // Error parsing type: , name: downloadManager
    // Error parsing type: , name: backgroundImageManager
    // Error parsing type: , name: cacheManager
    // Error parsing type: , name: videoDownloadManager
    // Error parsing type: , name: videoPlayerManager
}

- (void).cxx_destruct;
- (void)dealloc;
- (id)init;

@end

