//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMTextView.h"

@interface _TtC6WeChat18SnsComposeTextView : MMTextView
{
    // Error parsing type: , name: sendMsgShortCutType
    // Error parsing type: , name: textContentHeight
    // Error parsing type: , name: attributedPlaceHolderString
    // Error parsing type: , name: textContentHeightChange
    // Error parsing type: , name: textContentCountChange
    // Error parsing type: , name: textContextChange
    // Error parsing type: , name: messageSend
    // Error parsing type: , name: placeHolderString
}

- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1 textContainer:(id)arg2;
- (void)didChangeText;
- (void)SettingsDidChangeSendMessageShortcut;
- (void)drawRect:(struct CGRect)arg1;
- (id)initWithCoder:(id)arg1;

@end

