//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSTextAttachmentCell.h>

@class NSString;

@interface EmoticonRichTextAttachmentCell : NSTextAttachmentCell
{
    NSString *_keyValue;
    struct CGSize _desiredDisplaySize;
}

- (void).cxx_destruct;
@property(copy, nonatomic) NSString *keyValue; // @synthesize keyValue=_keyValue;
@property(nonatomic) struct CGSize desiredDisplaySize; // @synthesize desiredDisplaySize=_desiredDisplaySize;
- (struct CGSize)cellSize;
- (struct CGPoint)cellBaselineOffset;

@end

