//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMService.h"

#import "AccountServiceExt-Protocol.h"
#import "IMMCacheCleanerExt-Protocol.h"
#import "IMessageExt-Protocol.h"
#import "MMEmoticonFavoriteMgrLogicDelegate-Protocol.h"
#import "MMEmotionCustomMgrLogicDelegate-Protocol.h"
#import "MMResourceMgrExt-Protocol.h"
#import "MMService-Protocol.h"

@class MMCustomEmoticonMgrLogic, MMEmoticonDB, MMEmotionGroupInfo, MMFavoriteEmoticonMgrLogic, MMMsgEmoticonMgrLogic, MMThreadSafeArray, NSData, NSMutableArray, NSMutableDictionary, NSMutableSet, NSRecursiveLock, NSString;

@interface EmoticonMgr : MMService <MMEmoticonFavoriteMgrLogicDelegate, MMResourceMgrExt, AccountServiceExt, MMEmotionCustomMgrLogicDelegate, IMMCacheCleanerExt, IMessageExt, MMService>
{
    unsigned char _isGetting;
    MMEmoticonDB *_db;
    NSMutableArray *_cachedEmojiGroups;
    NSMutableArray *_cachedStickerGroups;
    NSRecursiveLock *_cachedGroupsLock;
    NSMutableArray *_needDownloadEmoticonStoreIconList;
    NSMutableArray *_needDownloadEmoticonStoreItemList;
    NSMutableArray *_allEmoticonStoreItemList;
    NSMutableSet *_storeItemMd5;
    NSMutableDictionary *_dictCaptions;
    NSData *_currReqBuf;
    NSMutableArray *_emoticonStoreItemServerList;
    unsigned long long _retryCount;
    MMThreadSafeArray *_serverNotifyTaskList;
    MMFavoriteEmoticonMgrLogic *_favoriteEmoticonMgrLogic;
    MMEmotionGroupInfo *_favEmoticonGroup;
    MMCustomEmoticonMgrLogic *_customEmoticonMgrLogic;
    MMEmotionGroupInfo *_customEmoticonGroup;
    MMMsgEmoticonMgrLogic *_msgEmoticonMgrLogic;
}

+ (id)MMKVKeyForEmoticonResWithSubType:(unsigned int)arg1;
+ (id)dirPathOfEmoticonResForSubType:(unsigned int)arg1;
+ (id)dirPathAfterUnzipIfNeedUpdateForSubType:(unsigned int)arg1;
- (void).cxx_destruct;
@property(retain, nonatomic) MMMsgEmoticonMgrLogic *msgEmoticonMgrLogic; // @synthesize msgEmoticonMgrLogic=_msgEmoticonMgrLogic;
@property(retain, nonatomic) MMEmotionGroupInfo *customEmoticonGroup; // @synthesize customEmoticonGroup=_customEmoticonGroup;
@property(retain, nonatomic) MMCustomEmoticonMgrLogic *customEmoticonMgrLogic; // @synthesize customEmoticonMgrLogic=_customEmoticonMgrLogic;
@property(retain, nonatomic) MMEmotionGroupInfo *favEmoticonGroup; // @synthesize favEmoticonGroup=_favEmoticonGroup;
@property(retain, nonatomic) MMFavoriteEmoticonMgrLogic *favoriteEmoticonMgrLogic; // @synthesize favoriteEmoticonMgrLogic=_favoriteEmoticonMgrLogic;
@property(retain, nonatomic) MMThreadSafeArray *serverNotifyTaskList; // @synthesize serverNotifyTaskList=_serverNotifyTaskList;
@property(nonatomic) unsigned long long retryCount; // @synthesize retryCount=_retryCount;
@property(nonatomic) unsigned char isGetting; // @synthesize isGetting=_isGetting;
@property(retain, nonatomic) NSMutableArray *emoticonStoreItemServerList; // @synthesize emoticonStoreItemServerList=_emoticonStoreItemServerList;
@property(retain, nonatomic) NSData *currReqBuf; // @synthesize currReqBuf=_currReqBuf;
@property(retain) NSMutableDictionary *dictCaptions; // @synthesize dictCaptions=_dictCaptions;
@property(retain, nonatomic) NSMutableSet *storeItemMd5; // @synthesize storeItemMd5=_storeItemMd5;
@property(retain) NSMutableArray *allEmoticonStoreItemList; // @synthesize allEmoticonStoreItemList=_allEmoticonStoreItemList;
@property(retain, nonatomic) NSMutableArray *needDownloadEmoticonStoreItemList; // @synthesize needDownloadEmoticonStoreItemList=_needDownloadEmoticonStoreItemList;
@property(retain, nonatomic) NSMutableArray *needDownloadEmoticonStoreIconList; // @synthesize needDownloadEmoticonStoreIconList=_needDownloadEmoticonStoreIconList;
@property(retain, nonatomic) NSRecursiveLock *cachedGroupsLock; // @synthesize cachedGroupsLock=_cachedGroupsLock;
@property(retain, nonatomic) NSMutableArray *cachedStickerGroups; // @synthesize cachedStickerGroups=_cachedStickerGroups;
@property(retain, nonatomic) NSMutableArray *cachedEmojiGroups; // @synthesize cachedEmojiGroups=_cachedEmojiGroups;
@property(retain, nonatomic) MMEmoticonDB *db; // @synthesize db=_db;
- (void)runNotifyTask;
- (void)onGetNewXmlMsg:(id)arg1 type:(id)arg2 msgData:(id)arg3;
- (void)onComputeCacheSize;
- (void)onCleanCache;
- (void)resetCachedEmojiGroups;
- (void)resetCachedStickerGroups;
- (void)manualCleanEmoticonCache;
- (void)autoCleanEmoticonCache;
- (void)beforeUserLogout;
- (void)updateEmoticonFromServer;
- (BOOL)isJsbOrDiceEmoticonMd5:(id)arg1;
- (BOOL)isGameEmoticonWith:(id)arg1;
- (BOOL)resetEmoticonDB;
- (BOOL)hasDBFlag;
- (void)insertDBFlag;
- (void)checkEmotionEncryptKeyFromFileWithCompletion:(CDUnknownBlockType)arg1;
- (void)emojiBase64tools;
- (void)unZipResWithPath:(id)arg1 forSubType:(unsigned int)arg2;
- (void)onResUpdateFinish:(long long)arg1 resType:(unsigned int)arg2 subResType:(unsigned int)arg3;
- (unsigned char)removeFailStoreEmoticonFromList:(id)arg1;
- (BOOL)removeInstalledStickerPackWithID:(id)arg1;
- (BOOL)unzipPackageAtPath:(id)arg1 withPid:(id)arg2;
- (void)installPackageFromZip:(id)arg1 storeInfo:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)dealWithResponse:(id)arg1;
- (void)handleGetEmoticonListFailed;
- (void)fetchAndDownloadPurchasedStickerStoreListWithCompletion:(CDUnknownBlockType)arg1;
- (void)updatePurchasedStickerStoreList;
- (id)_storeItemsFromResponse:(id)arg1;
- (id)_emotionListRequestWithType:(int)arg1;
- (BOOL)stickerPackExistsWithID:(id)arg1;
- (BOOL)isStickerTouchLimitCount;
- (BOOL)isStickerTouchLimitSize:(id)arg1;
- (void)setStickerToastViewDelegate:(id)arg1;
- (void)addFavEmoticon:(id)arg1;
- (void)onCustomEmoticonChanged;
- (void)onFavEmoticonChanged;
- (void)onFavEmoticonMD5Updated;
- (void)addEmotionWithMd5Object:(id)arg1;
- (void)deleteEmotionWithMd5Object:(id)arg1;
- (void)refreshEmoticonsWithType:(unsigned long long)arg1;
- (void)refreshEmoticonsIfNeeded;
- (id)favoritesGroup;
- (void)cancelDownloadEmoticonWithMessageData:(id)arg1;
- (void)downloadEmoticonWithMessageData:(id)arg1;
- (id)getHistoryEncryptKey;
- (void)downloadEmotionWithEmotionData:(id)arg1;
- (id)getEmoticonDescWithMD5:(id)arg1;
- (id)getEmotionThumbWithPackageID:(id)arg1;
- (id)getEmotionThumbWithMD5:(id)arg1;
- (id)getEmotionImgWithMD5:(id)arg1;
- (id)getEmotionDataWithMD5:(id)arg1;
- (BOOL)updateEmotionThumbCacheWithMD5:(id)arg1;
- (id)_localizedStickerCaption:(id)arg1;
- (void)_updateCachedStickerGroupsIfNeeded;
- (void)_addCustomEmoticonGroupToCachedStickerGroupsIfNeeded;
- (id)_obtainCachedStickerGroups;
- (id)_obtainCachedEmojiGroups;
- (id)emoticonGroupsWithType:(long long)arg1;
- (BOOL)isEmoticonMD5InFavorites:(id)arg1;
- (BOOL)isFavoriteEmoticonsLoaded;
- (BOOL)allowAddToFavorites;
- (void)configWxAMEnableSetting;
- (void)loadEmoticonData;
- (void)onServiceClearData;
- (void)onServiceInit;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

