//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "CdnBaseMediaInfo.h"

@interface CdnFavMediaInfo : CdnBaseMediaInfo
{
    BOOL _m_bStreamMedia;
    BOOL _m_bFromRetry;
}

@property(nonatomic) BOOL m_bFromRetry; // @synthesize m_bFromRetry=_m_bFromRetry;
@property(nonatomic) BOOL m_bStreamMedia; // @synthesize m_bStreamMedia=_m_bStreamMedia;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

