//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "PBGeneratedMessage.h"

@class NSString;

@interface ServiceNotifyItem : PBGeneratedMessage
{
    unsigned int hasUsername:1;
    unsigned int hasIsOpen:1;
    unsigned int isOpen_:1;
    unsigned int hasNickname:1;
    unsigned int hasAvatarurl:1;
    NSString *username;
    NSString *nickname;
    NSString *avatarurl;
}

+ (id)parseFromData:(id)arg1;
- (void).cxx_destruct;
@property(retain, nonatomic, setter=SetAvatarurl:) NSString *avatarurl; // @synthesize avatarurl;
@property(readonly, nonatomic) BOOL hasAvatarurl; // @synthesize hasAvatarurl;
@property(retain, nonatomic, setter=SetNickname:) NSString *nickname; // @synthesize nickname;
@property(readonly, nonatomic) BOOL hasNickname; // @synthesize hasNickname;
@property(readonly, nonatomic) BOOL hasIsOpen; // @synthesize hasIsOpen;
@property(retain, nonatomic, setter=SetUsername:) NSString *username; // @synthesize username;
@property(readonly, nonatomic) BOOL hasUsername; // @synthesize hasUsername;
- (id)mergeFromCodedInputStream:(id)arg1;
- (int)serializedSize;
- (void)writeToCodedOutputStream:(id)arg1;
- (BOOL)isInitialized;
@property(nonatomic, setter=SetIsOpen:) BOOL isOpen; // @synthesize isOpen=isOpen_;
- (id)init;

@end

