//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WebviewJSEventHandlerBase.h"

#import "IContactMgrExt-Protocol.h"
#import "MMCGIDelegate-Protocol.h"

@class MMTimer, NSString;

@interface WebviewJSEventHandler_quicklyAddBrandContact : WebviewJSEventHandlerBase <MMCGIDelegate, IContactMgrExt>
{
    BOOL _isWaitingContactSync;
    MMTimer *_contactSyncTimer;
    NSString *_currentUserName;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSString *currentUserName; // @synthesize currentUserName=_currentUserName;
@property(retain, nonatomic) MMTimer *contactSyncTimer; // @synthesize contactSyncTimer=_contactSyncTimer;
@property(nonatomic) BOOL isWaitingContactSync; // @synthesize isWaitingContactSync=_isWaitingContactSync;
- (void)onModifyContacts:(id)arg1;
- (void)OnResponseCGI:(BOOL)arg1 sessionId:(unsigned int)arg2 cgiWrap:(id)arg3;
- (void)onContactAddFail:(id)arg1;
- (void)onContactAddOK;
- (void)onContactSyncTimeout:(id)arg1;
- (void)resetContactSyncTimer;
- (void)startContactSyncTimer;
- (void)handleQuicklyAddBrandContact:(BOOL)arg1 cgiWrap:(id)arg2;
- (void)createVerify:(id)arg1 scene:(unsigned int)arg2 reportInfo:(id)arg3;
- (void)handleJSEvent:(id)arg1 HandlerFacade:(id)arg2 ExtraData:(id)arg3;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

