//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TXCFilter.h"

@class NSString;

@interface TXCGreenScreenFilter : TXCFilter
{
    BOOL _mirror;
    long long _fillMode;
    NSString *_greenPath;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSString *greenPath; // @synthesize greenPath=_greenPath;
@property(nonatomic) long long fillMode; // @synthesize fillMode=_fillMode;
@property(nonatomic) BOOL mirror; // @synthesize mirror=_mirror;
- (id)initWithPath:(id)arg1;

@end

